# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

DEFAULT_WEBLATE_GPG_IDENTITY = None
DEFAULT_WEBLATE_GPG_ALGO = "default"

DEFAULT_RATELIMIT_ATTEMPTS = 5
DEFAULT_RATELIMIT_WINDOW = 300
DEFAULT_RATELIMIT_LOCKOUT = 600

DEFAULT_RATELIMIT_SEARCH_ATTEMPTS = 30
DEFAULT_RATELIMIT_SEARCH_WINDOW = 60
DEFAULT_RATELIMIT_SEARCH_LOCKOUT = 60

DEFAULT_RATELIMIT_COMMENT_ATTEMPTS = 30
DEFAULT_RATELIMIT_COMMENT_WINDOW = 60

DEFAULT_RATELIMIT_TRANSLATE_ATTEMPTS = 30
DEFAULT_RATELIMIT_TRANSLATE_WINDOW = 60

DEFAULT_RATELIMIT_GLOSSARY_ATTEMPTS = 30
DEFAULT_RATELIMIT_GLOSSARY_WINDOW = 60

DEFAULT_RATELIMIT_LANGUAGE_ATTEMPTS = 2
DEFAULT_RATELIMIT_LANGUAGE_WINDOW = 300
DEFAULT_RATELIMIT_LANGUAGE_LOCKOUT = 600

DEFAULT_RATELIMIT_MESSAGE_ATTEMPTS = 2

DEFAULT_RATELIMIT_TRIAL_ATTEMPTS = 1
DEFAULT_RATELIMIT_TRIAL_WINDOW = 60
DEFAULT_RATELIMIT_TRIAL_LOCKOUT = 600

DEFAULT_RATELIMIT_PROJECT_ATTEMPTS = 5
DEFAULT_RATELIMIT_PROJECT_WINDOW = 600
DEFAULT_RATELIMIT_PROJECT_LOCKOUT = 600

DEFAULT_SENTRY_DSN = None
DEFAULT_SENTRY_SECURITY = None
DEFAULT_SENTRY_ENVIRONMENT = "devel"
DEFAULT_SENTRY_MONITOR_BEAT_TASKS = True
DEFAULT_SENTRY_TOKEN = None
DEFAULT_SENTRY_SEND_PII = False
DEFAULT_SENTRY_PROJECTS: tuple[str, ...] = ("weblate",)
DEFAULT_SENTRY_RELEASES_API_URL = (
    "https://sentry.io/api/0/organizations/4507304895905792/releases/"
)
DEFAULT_SENTRY_EXTRA_ARGS: dict = {}
DEFAULT_SENTRY_TRACES_SAMPLE_RATE = 0
DEFAULT_SENTRY_PROFILES_SAMPLE_RATE = 1.0
DEFAULT_GOOGLE_CLOUD_ERROR_REPORTING: dict[str, object] | None = None
DEFAULT_OPENTELEMETRY_ENABLED = False
DEFAULT_OPENTELEMETRY_SERVICE_NAME = "weblate"
DEFAULT_OPENTELEMETRY_EXPORTER_OTLP_ENDPOINT = None
DEFAULT_OPENTELEMETRY_EXPORTER_OTLP_HEADERS: dict[str, str] = {}
DEFAULT_OPENTELEMETRY_TRACES_SAMPLE_RATE = 0
DEFAULT_OPENTELEMETRY_EXTRA_RESOURCE_ATTRIBUTES: dict[str, str] = {}

DEFAULT_ZAMMAD_URL = None

DEFAULT_CELERY_TASK_ALWAYS_EAGER = True
DEFAULT_CELERY_BROKER_URL = "memory://"

DEFAULT_STATS_LAZY = False
DEFAULT_DATABASE_BACKUP = "plain"
DEFAULT_BORG_EXTRA_ARGS = None

DEFAULT_VERSION_DISPLAY = None
DEFAULT_HIDE_VERSION = False

DEFAULT_CSP_SCRIPT_SRC: tuple[str, ...] = ()
DEFAULT_CSP_IMG_SRC: tuple[str, ...] = ()
DEFAULT_CSP_CONNECT_SRC: tuple[str, ...] = ()
DEFAULT_CSP_STYLE_SRC: tuple[str, ...] = ()
DEFAULT_CSP_FONT_SRC: tuple[str, ...] = ()
DEFAULT_CSP_FORM_SRC: tuple[str, ...] = ()

DEFAULT_PROJECT_NAME_RESTRICT_RE = None
DEFAULT_PROJECT_WEB_RESTRICT_RE = None
DEFAULT_PROJECT_WEB_RESTRICT_HOST: frozenset[str] = frozenset({"localhost"})
DEFAULT_PROJECT_WEB_RESTRICT_ALLOWLIST: frozenset[str] = frozenset()
DEFAULT_PROJECT_WEB_RESTRICT_NUMERIC = True
DEFAULT_PROJECT_WEB_RESTRICT_PRIVATE = True
DEFAULT_WEBHOOK_RESTRICT_PRIVATE = True
DEFAULT_WEBHOOK_PRIVATE_ALLOWLIST: tuple[str, ...] = ()

DEFAULT_LOCALE_FILTER_FILES = True

DEFAULT_ALLOWED_ASSET_DOMAINS: tuple[str, ...] = ("*",)
DEFAULT_ASSET_RESTRICT_PRIVATE = True
DEFAULT_ASSET_PRIVATE_ALLOWLIST: tuple[str, ...] = ()
DEFAULT_ALLOWED_MACHINERY_DOMAINS: tuple[str, ...] = ()
DEFAULT_ALLOWED_ASSET_SIZE = 10_000_000
DEFAULT_TRANSLATION_UPLOAD_MAX_SIZE = 50_000_000
DEFAULT_COMPONENT_ZIP_UPLOAD_MAX_SIZE = 50_000_000
DEFAULT_PROJECT_BACKUP_UPLOAD_MAX_SIZE = 512 * 1024 * 1024
