# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# mypy: disable-error-code="var-annotated"

from __future__ import annotations

from typing import ClassVar

from appconf import AppConf

from weblate.utils import defaults
from weblate.utils.version_display import (
    VERSION_DISPLAY_HIDE,
    normalize_version_display,
)


class WeblateConf(AppConf):
    WEBLATE_GPG_IDENTITY = defaults.DEFAULT_WEBLATE_GPG_IDENTITY
    WEBLATE_GPG_ALGO = defaults.DEFAULT_WEBLATE_GPG_ALGO

    RATELIMIT_ATTEMPTS = defaults.DEFAULT_RATELIMIT_ATTEMPTS
    RATELIMIT_WINDOW = defaults.DEFAULT_RATELIMIT_WINDOW
    RATELIMIT_LOCKOUT = defaults.DEFAULT_RATELIMIT_LOCKOUT

    RATELIMIT_SEARCH_ATTEMPTS = defaults.DEFAULT_RATELIMIT_SEARCH_ATTEMPTS
    RATELIMIT_SEARCH_WINDOW = defaults.DEFAULT_RATELIMIT_SEARCH_WINDOW
    RATELIMIT_SEARCH_LOCKOUT = defaults.DEFAULT_RATELIMIT_SEARCH_LOCKOUT

    RATELIMIT_COMMENT_ATTEMPTS = defaults.DEFAULT_RATELIMIT_COMMENT_ATTEMPTS
    RATELIMIT_COMMENT_WINDOW = defaults.DEFAULT_RATELIMIT_COMMENT_WINDOW

    RATELIMIT_TRANSLATE_ATTEMPTS = defaults.DEFAULT_RATELIMIT_TRANSLATE_ATTEMPTS
    RATELIMIT_TRANSLATE_WINDOW = defaults.DEFAULT_RATELIMIT_TRANSLATE_WINDOW

    RATELIMIT_GLOSSARY_ATTEMPTS = defaults.DEFAULT_RATELIMIT_GLOSSARY_ATTEMPTS
    RATELIMIT_GLOSSARY_WINDOW = defaults.DEFAULT_RATELIMIT_GLOSSARY_WINDOW

    RATELIMIT_LANGUAGE_ATTEMPTS = defaults.DEFAULT_RATELIMIT_LANGUAGE_ATTEMPTS
    RATELIMIT_LANGUAGE_WINDOW = defaults.DEFAULT_RATELIMIT_LANGUAGE_WINDOW
    RATELIMIT_LANGUAGE_LOCKOUT = defaults.DEFAULT_RATELIMIT_LANGUAGE_LOCKOUT

    RATELIMIT_MESSAGE_ATTEMPTS = defaults.DEFAULT_RATELIMIT_MESSAGE_ATTEMPTS

    RATELIMIT_TRIAL_ATTEMPTS = defaults.DEFAULT_RATELIMIT_TRIAL_ATTEMPTS
    RATELIMIT_TRIAL_WINDOW = defaults.DEFAULT_RATELIMIT_TRIAL_WINDOW
    RATELIMIT_TRIAL_LOCKOUT = defaults.DEFAULT_RATELIMIT_TRIAL_LOCKOUT

    RATELIMIT_PROJECT_ATTEMPTS = defaults.DEFAULT_RATELIMIT_PROJECT_ATTEMPTS
    RATELIMIT_PROJECT_WINDOW = defaults.DEFAULT_RATELIMIT_PROJECT_WINDOW
    RATELIMIT_PROJECT_LOCKOUT = defaults.DEFAULT_RATELIMIT_PROJECT_LOCKOUT

    RATELIMIT_GITHUB_SETUP_ATTEMPTS = defaults.DEFAULT_RATELIMIT_GITHUB_SETUP_ATTEMPTS
    RATELIMIT_GITHUB_SETUP_WINDOW = defaults.DEFAULT_RATELIMIT_GITHUB_SETUP_WINDOW

    SENTRY_DSN = defaults.DEFAULT_SENTRY_DSN
    SENTRY_SECURITY = defaults.DEFAULT_SENTRY_SECURITY
    SENTRY_ENVIRONMENT = defaults.DEFAULT_SENTRY_ENVIRONMENT
    SENTRY_MONITOR_BEAT_TASKS = defaults.DEFAULT_SENTRY_MONITOR_BEAT_TASKS
    SENTRY_TOKEN = defaults.DEFAULT_SENTRY_TOKEN
    SENTRY_SEND_PII = defaults.DEFAULT_SENTRY_SEND_PII
    SENTRY_PROJECTS: ClassVar[list[str]] = list(defaults.DEFAULT_SENTRY_PROJECTS)
    SENTRY_RELEASES_API_URL = defaults.DEFAULT_SENTRY_RELEASES_API_URL
    SENTRY_EXTRA_ARGS: ClassVar[dict] = dict(defaults.DEFAULT_SENTRY_EXTRA_ARGS)
    SENTRY_TRACES_SAMPLE_RATE = defaults.DEFAULT_SENTRY_TRACES_SAMPLE_RATE
    SENTRY_PROFILES_SAMPLE_RATE = defaults.DEFAULT_SENTRY_PROFILES_SAMPLE_RATE
    GOOGLE_CLOUD_ERROR_REPORTING: ClassVar[dict[str, object] | None] = (
        defaults.DEFAULT_GOOGLE_CLOUD_ERROR_REPORTING
    )
    OPENTELEMETRY_ENABLED = defaults.DEFAULT_OPENTELEMETRY_ENABLED
    OPENTELEMETRY_SERVICE_NAME = defaults.DEFAULT_OPENTELEMETRY_SERVICE_NAME
    OPENTELEMETRY_EXPORTER_OTLP_ENDPOINT = (
        defaults.DEFAULT_OPENTELEMETRY_EXPORTER_OTLP_ENDPOINT
    )
    OPENTELEMETRY_EXPORTER_OTLP_HEADERS: ClassVar[dict[str, str]] = dict(
        defaults.DEFAULT_OPENTELEMETRY_EXPORTER_OTLP_HEADERS
    )
    OPENTELEMETRY_TRACES_SAMPLE_RATE = defaults.DEFAULT_OPENTELEMETRY_TRACES_SAMPLE_RATE
    OPENTELEMETRY_EXTRA_RESOURCE_ATTRIBUTES: ClassVar[dict[str, str]] = dict(
        defaults.DEFAULT_OPENTELEMETRY_EXTRA_RESOURCE_ATTRIBUTES
    )

    ZAMMAD_URL = defaults.DEFAULT_ZAMMAD_URL

    CELERY_TASK_ALWAYS_EAGER = defaults.DEFAULT_CELERY_TASK_ALWAYS_EAGER
    CELERY_BROKER_URL = defaults.DEFAULT_CELERY_BROKER_URL

    STATS_LAZY = defaults.DEFAULT_STATS_LAZY

    DATABASE_BACKUP = defaults.DEFAULT_DATABASE_BACKUP

    BORG_EXTRA_ARGS = defaults.DEFAULT_BORG_EXTRA_ARGS

    VERSION_DISPLAY = defaults.DEFAULT_VERSION_DISPLAY
    HIDE_VERSION = defaults.DEFAULT_HIDE_VERSION

    CSP_SCRIPT_SRC: ClassVar[list[str]] = list(defaults.DEFAULT_CSP_SCRIPT_SRC)
    CSP_IMG_SRC: ClassVar[list[str]] = list(defaults.DEFAULT_CSP_IMG_SRC)
    CSP_CONNECT_SRC: ClassVar[list[str]] = list(defaults.DEFAULT_CSP_CONNECT_SRC)
    CSP_STYLE_SRC: ClassVar[list[str]] = list(defaults.DEFAULT_CSP_STYLE_SRC)
    CSP_FONT_SRC: ClassVar[list[str]] = list(defaults.DEFAULT_CSP_FONT_SRC)
    CSP_FORM_SRC: ClassVar[list[str]] = list(defaults.DEFAULT_CSP_FORM_SRC)

    PROJECT_NAME_RESTRICT_RE = defaults.DEFAULT_PROJECT_NAME_RESTRICT_RE
    PROJECT_WEB_RESTRICT_RE = defaults.DEFAULT_PROJECT_WEB_RESTRICT_RE
    PROJECT_WEB_RESTRICT_HOST: ClassVar[set[str]] = set(
        defaults.DEFAULT_PROJECT_WEB_RESTRICT_HOST
    )
    PROJECT_WEB_RESTRICT_ALLOWLIST: ClassVar[set[str]] = set(
        defaults.DEFAULT_PROJECT_WEB_RESTRICT_ALLOWLIST
    )
    PROJECT_WEB_RESTRICT_NUMERIC = defaults.DEFAULT_PROJECT_WEB_RESTRICT_NUMERIC
    PROJECT_WEB_RESTRICT_PRIVATE = defaults.DEFAULT_PROJECT_WEB_RESTRICT_PRIVATE
    WEBHOOK_RESTRICT_PRIVATE = defaults.DEFAULT_WEBHOOK_RESTRICT_PRIVATE
    WEBHOOK_PRIVATE_ALLOWLIST: ClassVar[list[str]] = list(
        defaults.DEFAULT_WEBHOOK_PRIVATE_ALLOWLIST
    )

    LOCALE_FILTER_FILES = defaults.DEFAULT_LOCALE_FILTER_FILES

    ALLOWED_ASSET_DOMAINS: ClassVar[list[str]] = list(
        defaults.DEFAULT_ALLOWED_ASSET_DOMAINS
    )
    ASSET_RESTRICT_PRIVATE = defaults.DEFAULT_ASSET_RESTRICT_PRIVATE
    ASSET_PRIVATE_ALLOWLIST: ClassVar[list[str]] = list(
        defaults.DEFAULT_ASSET_PRIVATE_ALLOWLIST
    )
    ALLOWED_MACHINERY_DOMAINS: ClassVar[list[str]] = list(
        defaults.DEFAULT_ALLOWED_MACHINERY_DOMAINS
    )
    ALLOWED_ASSET_SIZE: ClassVar[int] = defaults.DEFAULT_ALLOWED_ASSET_SIZE
    TRANSLATION_UPLOAD_MAX_SIZE: ClassVar[int] = (
        defaults.DEFAULT_TRANSLATION_UPLOAD_MAX_SIZE
    )
    COMPONENT_ZIP_UPLOAD_MAX_SIZE: ClassVar[int] = (
        defaults.DEFAULT_COMPONENT_ZIP_UPLOAD_MAX_SIZE
    )
    PROJECT_BACKUP_UPLOAD_MAX_SIZE: ClassVar[int] = (
        defaults.DEFAULT_PROJECT_BACKUP_UPLOAD_MAX_SIZE
    )

    def configure(self):
        data = AppConf.configure(self).copy()
        data["VERSION_DISPLAY"] = normalize_version_display(
            data["VERSION_DISPLAY"], data["HIDE_VERSION"]
        )
        data["HIDE_VERSION"] = data["VERSION_DISPLAY"] == VERSION_DISPLAY_HIDE
        return data

    class Meta:
        prefix = ""
