#!/bin/sh
# Fake key scan program to return SSH key
if [ "$1" = "1.2.3.4" ]; then
    exit 1
elif [ "$1" = "2001:0db8:85a3:0000:0000:8a2e:0370:7334" ]; then
    echo test error >&2
    exit 2
fi
echo '# github.com SSH-2.0-libssh-0.7.0'
echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
echo '# github.com SSH-2.0-libssh-0.7.0'
echo 'no hostkey alg'
