# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.3 on 2024-04-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_squashed_weblate_5"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="display_limit_hosted_strings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="limit_hosted_strings",
            field=models.IntegerField(default=0),
        ),
    ]
