# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_squashed_0016_remove_billing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='in_limits',
            field=models.BooleanField(default=True, editable=False, verbose_name='In limits'),
        ),
        migrations.AddField(
            model_name='billing',
            name='paid',
            field=models.BooleanField(default=False, editable=False, verbose_name='Paid'),
        ),
        migrations.AddField(
            model_name='billing',
            name='trial_expiry',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Trial expiry date'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Plan', verbose_name='Billing plan'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='projects',
            field=models.ManyToManyField(blank=True, to='trans.Project', verbose_name='Billed projects'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='state',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Trial'), (2, 'Expired')], default=0, verbose_name='Billing state'),
        ),
    ]
