# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_auto_20180905_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='owners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Billing owners'),
        ),
    ]
