# Generated by Django 3.1.2 on 2020-11-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_remove_billing_grace_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="state",
            field=models.IntegerField(
                choices=[(0, "Active"), (1, "Trial"), (3, "Terminated")],
                default=0,
                verbose_name="Billing state",
            ),
        ),
    ]
