# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-21 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("billing", "0003_billing_owners")]

    operations = [
        migrations.RenameField(
            model_name="billing", old_name="trial_expiry", new_name="expiry"
        )
    ]
