# Generated by Django 3.2 on 2021-05-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_replace_expired"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billing",
            options={
                "verbose_name": "Customer billing",
                "verbose_name_plural": "Customer billings",
            },
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"verbose_name": "Invoice", "verbose_name_plural": "Invoices"},
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={
                "verbose_name": "Billing plan",
                "verbose_name_plural": "Billing plans",
            },
        ),
    ]
