# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billing_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='display_limit_languages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='display_limit_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='display_limit_repositories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='display_limit_strings',
            field=models.IntegerField(default=0),
        ),
    ]
