# Generated by Django 1.11.9 on 2018-10-21 10:56

from django.db import migrations

import weblate.utils.fields


class Migration(migrations.Migration):

    dependencies = [("billing", "0005_auto_20181021_1254")]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="payment",
            field=weblate.utils.fields.JSONField(default="", editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment",
            field=weblate.utils.fields.JSONField(editable=False),
        ),
    ]
