# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20160106_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('payment', models.IntegerField()),
                ('currency', models.IntegerField(choices=[(0, 'EUR'), (1, 'BTC')], default=1)),
                ('ref', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Billing')),
            ],
        ),
    ]
