# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_alter_billing_payment_alter_invoice_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="payment_new",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_new",
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
