# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0006_auto_20181021_1256")]

    operations = [
        migrations.AddField(
            model_name="plan", name="public", field=models.BooleanField(default=False)
        )
    ]
