# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.10 on 2026-01-22 11:46

from django.db import migrations

from weblate.auth.data import (
    SELECTION_ALL,
    SELECTION_ALL_PROTECTED,
    SELECTION_ALL_PUBLIC,
    SELECTION_COMPONENT_LIST,
    SELECTION_MANUAL,
)

# Copied from weblate/trans/models/project.py
ACCESS_PUBLIC = 0
ACCESS_PROTECTED = 1


def migrate_owners(apps, schema_editor) -> None:
    User = apps.get_model("weblate_auth", "User")
    Project = apps.get_model("trans", "Project")

    all_projects = Project.objects.all()
    all_protected_projects = Project.objects.filter(access_control=ACCESS_PROTECTED)
    all_public_projects = Project.objects.filter(access_control=ACCESS_PUBLIC)

    projects_cache = {}

    for user in User.objects.filter(
        groups__roles__permissions__codename="billing.view"
    ):
        for group in user.groups.filter(roles__permissions__codename="billing.view"):
            # Iterate over projects
            if group.id in projects_cache:
                projects = projects_cache[group.id]
            else:
                if group.project_selection == SELECTION_COMPONENT_LIST:
                    continue
                if group.project_selection == SELECTION_ALL:
                    projects = all_projects
                elif group.project_selection == SELECTION_ALL_PROTECTED:
                    projects = all_protected_projects
                elif group.project_selection == SELECTION_ALL_PUBLIC:
                    projects = all_public_projects
                elif group.project_selection == SELECTION_MANUAL:
                    projects = group.projects.all()
                else:
                    msg = f"Unsupported {group.project_selection=}"
                    raise ValueError(msg)
                projects_cache[group.id] = projects

            for project in projects:
                for billing in project.billing_set.all():
                    billing.owners.add(user)


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_billinglog_details_alter_billinglog_event"),
    ]

    operations = [
        migrations.RunPython(migrate_owners, migrations.RunPython.noop, elidable=True),
    ]
