# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.11 on 2026-02-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_migrate_owners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billinglog",
            name="event",
            field=models.IntegerField(
                choices=[
                    (1, "Outbound e-mail"),
                    (2, "Trial expired"),
                    (3, "Projects removed"),
                    (4, "Payment received"),
                    (5, "Unpaid billing"),
                    (6, "Created billing"),
                    (7, "Disabled recurring payment"),
                    (8, "Requested Libre hosting"),
                    (9, "Approved Libre hosting"),
                    (10, "Billing terminated"),
                    (11, "Trial extended"),
                    (12, "Project backed up"),
                    (13, "Admin added"),
                    (14, "Admin added on project removal"),
                    (15, "Admin removed"),
                ],
                verbose_name="Billing event",
            ),
        ),
    ]
