# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='state',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Trial'), (2, 'Expired')], default=0),
        ),
    ]
