# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.4 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0008_alter_billinglog_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="inactive_recurring_disable",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Scheduled recurring payment disablement",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="inactive_recurring_latest_commit",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Latest upstream commit",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="inactive_recurring_oldest_pending_change",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Oldest pending Weblate change",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="inactive_recurring_push_failure",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Push failure alert",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="inactive_recurring_repository_changes",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Repository changes alert",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="inactive_recurring_notification",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Inactive recurring payment notification",
            ),
        ),
        migrations.AlterField(
            model_name="billinglog",
            name="event",
            field=models.IntegerField(
                choices=[
                    (1, "Outbound e-mail"),
                    (2, "Trial expired"),
                    (3, "Projects removed"),
                    (4, "Payment received"),
                    (5, "Unpaid billing"),
                    (6, "Created billing"),
                    (7, "Disabled recurring payment"),
                    (8, "Requested Libre hosting"),
                    (9, "Approved Libre hosting"),
                    (10, "Billing terminated"),
                    (11, "Trial extended"),
                    (12, "Project backed up"),
                    (13, "Admin added"),
                    (14, "Admin added on project removal"),
                    (15, "Admin removed"),
                    (16, "Scheduled recurring payment disablement"),
                    (17, "Cleared recurring payment disablement"),
                ],
                verbose_name="Billing event",
            ),
        ),
    ]
