# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billing_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='trial',
        ),
    ]
