# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_billing_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.IntegerField(choices=[(0, 'EUR'), (1, 'mBTC')], default=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment',
            field=models.FloatField(),
        ),
    ]
