# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-04 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0009_remove_billing_payment_remove_invoice_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billing",
            old_name="payment_new",
            new_name="payment",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="payment_new",
            new_name="payment",
        ),
    ]
