# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.5 on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0009_billing_inactive_recurring"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="customer_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Customer name"
            ),
        ),
    ]
