# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django on 2026-05-22

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def get_workspace_name(billing, projects, owners) -> str:
    if billing.customer_name:
        return billing.customer_name[:100]

    project_names = [project.name for project in projects[:2]]
    if project_names:
        return ", ".join(project_names)[:100]

    owner_names = [owner.username for owner in owners[:2]]
    if owner_names:
        return f"Billing for {', '.join(owner_names)}"[:100]

    return "Billing"


def migrate_billing_workspaces(apps, schema_editor) -> None:
    Billing = apps.get_model("billing", "Billing")
    Project = apps.get_model("trans", "Project")
    Workspace = apps.get_model("workspaces", "Workspace")

    db_alias = schema_editor.connection.alias
    through = Billing.projects.through
    duplicates = list(
        through.objects.using(db_alias)
        .values("project_id")
        .annotate(billing_count=Count("billing_id"))
        .filter(billing_count__gt=1)
        .values_list("project_id", flat=True)[:10]
    )
    if duplicates:
        msg = (
            "Can not migrate billing projects to workspaces because some projects "
            f"belong to multiple billings: {duplicates}"
        )
        raise RuntimeError(msg)

    for billing in Billing.objects.using(db_alias).prefetch_related(
        "owners", "projects"
    ):
        projects = sorted(billing.projects.all(), key=lambda project: project.name)
        owners = sorted(billing.owners.all(), key=lambda owner: owner.username)
        name = get_workspace_name(billing, projects, owners)
        workspace = Workspace.objects.using(db_alias).create(
            name=name, name_managed=True
        )
        Billing.objects.using(db_alias).filter(pk=billing.pk).update(
            workspace=workspace
        )
        Project.objects.using(db_alias).filter(
            pk__in=[project.pk for project in projects]
        ).update(workspace=workspace)


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_billing_customer_name"),
        ("trans", "0080_project_workspace"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="workspace",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing",
                to="workspaces.workspace",
                verbose_name="Workspace",
            ),
        ),
        migrations.RunPython(
            migrate_billing_workspaces, migrations.RunPython.noop, elidable=True
        ),
        migrations.AlterField(
            model_name="billing",
            name="workspace",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing",
                to="workspaces.workspace",
                verbose_name="Workspace",
            ),
        ),
        migrations.RemoveField(
            model_name="billing",
            name="projects",
        ),
    ]
