# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-08 11:52

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_rename_payment_new_billing_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="payment",
            field=models.JSONField(
                default=dict,
                editable=False,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
