# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0010_invoice_amount")]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="grace_period",
            field=models.IntegerField(
                default=0, verbose_name="Grace period for payments"
            ),
        )
    ]
