# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.5 on 2023-09-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0011_alter_billing_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="expiry",
            field=models.DateTimeField(
                blank=True,
                help_text="After expiry removal with 15 days grace period is scheduled.",
                null=True,
                verbose_name="Trial expiry date",
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="removal",
            field=models.DateTimeField(
                blank=True,
                help_text="This is automatically set after trial expiry.",
                null=True,
                verbose_name="Scheduled removal",
            ),
        ),
    ]
