# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20160210_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['billing', '-start']},
        ),
    ]
