# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0012_auto_20181207_0843")]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="paid",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="Paid"
            ),
        )
    ]
