# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20160816_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.IntegerField(choices=[(0, 'EUR'), (1, 'mBTC'), (2, 'USD'), (3, 'CZK')], default=0),
        ),
    ]
