# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0013_auto_20190208_1452")]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="removal",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Scheduled removal"
            ),
        )
    ]
