# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170816164241 on 2017-10-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20170601_1116'),
    ]

    run_before = [
        ('weblate_auth', '0010_auto_20180509_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='change_access_control',
            field=models.BooleanField(default=True),
        ),
    ]
