# Generated by Django 2.2 on 2019-05-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("billing", "0014_billing_removal")]

    operations = [
        migrations.AlterModelOptions(name="invoice", options={}),
        migrations.AlterModelOptions(name="plan", options={}),
    ]
