# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_plan_change_access_control'),
    ]

    operations = [
    ]
