# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20180509_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user',
        ),
    ]
