# Generated by Django 2.2.5 on 2019-09-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("billing", "0015_auto_20190516_1159")]

    operations = [
        migrations.RemoveField(model_name="plan", name="display_limit_repositories"),
        migrations.RemoveField(model_name="plan", name="limit_repositories"),
    ]
