# Generated by Django 3.0.4 on 2020-03-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_auto_20190919_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="slug",
            field=models.SlugField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
