# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.9 on 2024-02-19 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_auth", "0003_alter_autogroup_options_alter_autogroup_group_and_more"),
        ("weblate_auth", "0003_fixup_teams"),
    ]

    operations = []
