# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblate_auth', '0004_auto_20180508_1032'),
    ]

    operations = [
    ]
