# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import weblate.trans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weblate_auth', '0005_groups'),
        ('permissions', '0010_auto_20180508_1210'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='AutoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', weblate.trans.fields.RegexField(default='^.*$', help_text='Regular expression which is used to match user email.', max_length=200, verbose_name='Email regular expression')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group to assign')),
            ],
            options={
                'ordering': ('group__name',),
                'verbose_name': 'Automatic group assignment',
                'verbose_name_plural': 'Automatic group assignments',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
