# Generated by Django 3.0.5 on 2020-04-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0073_auto_20200403_1329"),
        ("weblate_auth", "0006_auto_20190905_1139"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="components",
            field=models.ManyToManyField(
                blank=True, to="trans.Component", verbose_name="Components"
            ),
        ),
    ]
