# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblate_auth', '0006_autogroup'),
    ]

    operations = [
    ]
