# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.6 on 2025-10-01 10:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_auth", "0006_group_enforced_2fa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_expires",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="The account will be disabled after the expiry.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(django.utils.timezone.now)
                ],
                verbose_name="Expires",
            ),
        ),
    ]
