# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.8 on 2025-11-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblate_auth", "0007_alter_user_date_expires"),
    ]

    operations = [
        migrations.AddField(
            model_name="userblock",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Internal notes regarding blocking the user that are not visible to the user.",
                verbose_name="Block note",
            ),
        ),
    ]
