# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 13:49
from __future__ import unicode_literals

import os
import binascii

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblate_auth', '0007_auto_20180509_0739'),
    ]

    operations = [
    ]
