# Generated by Django 3.0.7 on 2020-06-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0086_auto_20200609_1134"),
        ("weblate_auth", "0007_group_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="componentlists",
            field=models.ManyToManyField(
                blank=True, to="trans.ComponentList", verbose_name="Component lists"
            ),
        ),
    ]
