# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import weblate.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('weblate_auth', '0007_auto_20180509_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='project_selection',
            field=models.IntegerField(choices=[(0, 'As defined'), (1, 'All projects'), (3, 'All public projects'), (4, 'All protected projects'), (2, 'From component list')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[weblate.utils.validators.validate_email], verbose_name='Email'),
        ),
    ]
