# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblate_auth', '0009_auto_20180509_1552'),
    ]

    operations = [
    ]
