# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 05:39
#
# This is basically copy of 0007_auto_20180509_0739.py, to fix possible breakage
# on migration to 3.0. It just doesn't migrate groups (there is no need to do that)

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblate_auth', '0010_auto_20180509_1630'),
    ]

    operations = [
    ]
