# Generated by Django 3.2.4 on 2021-06-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0135_component_local_revision"),
        ("weblate_auth", "0015_userblock"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userblock",
            unique_together={("user", "project")},
        ),
    ]
