# Generated by Django 3.2.4 on 2021-07-21 06:47

from django.db import migrations

import weblate.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("weblate_auth", "0016_alter_userblock_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=weblate.utils.fields.EmailField(
                max_length=190, null=True, unique=True, verbose_name="E-mail"
            ),
        ),
    ]
