# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
    ]
