# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import weblate.trans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('permissions', '0002_auto_20170317_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', weblate.trans.fields.RegexField(default='^.*$', help_text='Regular expression which is used to match user email.', max_length=200, verbose_name='Email regular expression')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group to assign')),
            ],
            options={
                'ordering': ('group__name',),
                'verbose_name': 'Automatic group assignment',
                'verbose_name_plural': 'Automatic group assignments',
            },
        ),
    ]
