# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_auto_20170317_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupacl',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Filtered permissions'),
        ),
    ]
