# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_groupacl_permissions'),
        ('trans', '0083_auto_20170404_1633'),
        ('screenshots', '0003_auto_20170215_1633'),
        ('contenttypes', '0001_initial'),
        ('auth', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
    ]
