# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_auto_20170404_1637'),
    ]

    operations = [
    ]
