# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_auto_20170510_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupacl',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='The GroupACL will affect only selected permissions.', to='auth.Permission', verbose_name='Filtered permissions'),
        ),
    ]
