# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0011_auto_20180215_1158'),
        ('trans', '0130_auto_20180416_1503'),
        ('permissions', '0008_auto_20170605_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupacl',
            old_name='subproject',
            new_name='component',
        ),
        migrations.AlterUniqueTogether(
            name='groupacl',
            unique_together=set([('project', 'component', 'language')]),
        ),
    ]
