# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0009_auto_20180416_1610'),
        ('weblate_auth', '0005_groups'),
    ]

    database_operations = [migrations.AlterModelTable('AutoGroup', 'weblate_auth_autogroup')]

    state_operations = [migrations.DeleteModel('AutoGroup')]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
    ]
