# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 3.1.1 on 2020-10-19 12:16

from __future__ import annotations

import os
from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.state import StateApps


def alter_role(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    if (
        schema_editor.connection.vendor != "postgresql"
        or "PYTEST_XDIST_TESTRUNUID" in os.environ
    ):
        return

    settings = schema_editor.connection.settings_dict

    template = f"ALTER ROLE {schema_editor.quote_name(settings.get('ALTER_ROLE', settings['USER']))} SET {{}} = {{}}"

    schema_editor.execute(template.format("timezone", "UTC"))


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(alter_role, migrations.RunPython.noop, elidable=False)
    ]
