# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0037_auto_20180416_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uploaded',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
