# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.6 on 2023-10-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_new_string_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="activity",
            field=models.CharField(
                choices=[
                    ("accepted", "accepted"),
                    ("auth-connect", "auth-connect"),
                    ("auth-disconnect", "auth-disconnect"),
                    ("autocreated", "autocreated"),
                    ("blocked", "blocked"),
                    ("connect", "connect"),
                    ("disabled", "disabled"),
                    ("email", "email"),
                    ("enabled", "enabled"),
                    ("failed-auth", "failed-auth"),
                    ("full_name", "full_name"),
                    ("invited", "invited"),
                    ("locked", "locked"),
                    ("login", "login"),
                    ("login-new", "login-new"),
                    ("password", "password"),
                    ("register", "register"),
                    ("removal-request", "removal-request"),
                    ("removed", "removed"),
                    ("reset", "reset"),
                    ("reset-request", "reset-request"),
                    ("sent-email", "sent-email"),
                    ("tos", "tos"),
                    ("trial", "trial"),
                    ("username", "username"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
