# Generated by Django 3.0.7 on 2020-08-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20200630_1321"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="commented",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
