# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.6 on 2023-10-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_auditlog_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="twitter",
            field=models.SlugField(
                blank=True, db_index=False, verbose_name="X username"
            ),
        ),
    ]
