# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.9 on 2024-01-26 12:12

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_profile_twitter"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="verifiedemail",
            index=models.Index(
                django.db.models.functions.text.Upper("email"),
                name="accounts_verifiedemail_email",
            ),
        ),
    ]
