# Generated by Django 3.1.1 on 2020-09-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20200904_0840"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="codesite",
            field=models.URLField(
                blank=True,
                help_text="Link to your code profile for services like Codeberg or GitLab.",
                verbose_name="Code site URL",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="fediverse",
            field=models.URLField(
                blank=True,
                help_text="Link to your Fediverse profile for federated services like Mastodon or diaspora*.",
                verbose_name="Fediverse URL",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="liberapay",
            field=models.SlugField(
                blank=True,
                help_text="Liberapay is a platform to donate money to teams, organizations and individuals.",
                verbose_name="Liberapay username",
            ),
        ),
    ]
