# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.3 on 2024-04-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_auditlog_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dashboard_view",
            field=models.IntegerField(
                choices=[
                    (1, "Watched translations"),
                    (6, "Component lists"),
                    (4, "Component list"),
                    (5, "Suggested translations"),
                    (7, "Managed projects"),
                ],
                default=1,
                verbose_name="Default dashboard view",
            ),
        ),
    ]
