# Generated by Django 3.1.1 on 2020-09-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0104_update_source_unit_source"),
        ("accounts", "0008_auto_20200923_1216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dashboard_component_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trans.componentlist",
                verbose_name="Default component list",
            ),
        ),
    ]
