# Generated by Django 2.2 on 2019-05-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0009_profile_zen_mode")]

    operations = [migrations.AlterModelOptions(name="auditlog", options={})]
