# Generated by Django 3.1.3 on 2020-12-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_auto_20200923_2023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="scope",
            field=models.IntegerField(
                choices=[
                    (0, "All"),
                    (10, "Watched"),
                    (20, "Administered"),
                    (30, "Project"),
                    (40, "Component"),
                ]
            ),
        ),
    ]
