# Generated by Django 2.2.3 on 2019-08-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0011_auto_20190721_1810")]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="notification",
            field=models.CharField(
                choices=[
                    ("MergeFailureNotification", "Merge failure"),
                    ("ParseErrorNotification", "Parse error"),
                    ("NewStringNotificaton", "New string"),
                    ("NewContributorNotificaton", "New contributor"),
                    ("NewSuggestionNotificaton", "New suggestion"),
                    ("LastAuthorCommentNotificaton", "Comment on own translation"),
                    ("MentionCommentNotificaton", "Mentioned in comment"),
                    ("NewCommentNotificaton", "New comment"),
                    ("ChangedStringNotificaton", "Changed string"),
                    ("NewTranslationNotificaton", "New language"),
                    ("NewComponentNotificaton", "New translation component"),
                    ("NewWhiteboardMessageNotificaton", "New whiteboard message"),
                    ("NewAlertNotificaton", "New alert"),
                    ("PendingSuggestionsNotification", "Pending suggestions"),
                    ("ToDoStringsNotification", "Strings needing action"),
                ],
                max_length=100,
            ),
        )
    ]
