# Generated by Django 2.2.5 on 2019-09-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0012_auto_20190805_1248")]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="activity",
            field=models.CharField(
                choices=[
                    ("auth-connect", "auth-connect"),
                    ("auth-disconnect", "auth-disconnect"),
                    ("connect", "connect"),
                    ("email", "email"),
                    ("failed-auth", "failed-auth"),
                    ("full_name", "full_name"),
                    ("locked", "locked"),
                    ("login", "login"),
                    ("login-new", "login-new"),
                    ("password", "password"),
                    ("register", "register"),
                    ("removed", "removed"),
                    ("reset", "reset"),
                    ("reset-request", "reset-request"),
                    ("tos", "tos"),
                    ("username", "username"),
                ],
                db_index=True,
                max_length=20,
            ),
        )
    ]
