# Generated by Django 2.2.5 on 2019-09-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0013_auto_20190916_1203")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dashboard_view",
            field=models.IntegerField(
                choices=[
                    (1, "Watched translations"),
                    (6, "Component lists"),
                    (4, "Component list"),
                    (5, "Suggested translations"),
                ],
                default=1,
                verbose_name="Default dashboard view",
            ),
        )
    ]
