# Generated by Django 3.2 on 2021-05-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_auto_20210217_1653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.SlugField(
                blank=True, db_index=False, verbose_name="GitHub username"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="liberapay",
            field=models.SlugField(
                blank=True,
                db_index=False,
                help_text="Liberapay is a platform to donate money to teams, organizations and individuals.",
                verbose_name="Liberapay username",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=models.SlugField(
                blank=True,
                db_index=False,
                help_text="Your LinkedIn profile name from linkedin.com/in/profilename",
                verbose_name="LinkedIn profile name",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter",
            field=models.SlugField(
                blank=True, db_index=False, verbose_name="Twitter username"
            ),
        ),
    ]
