# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0058_componentlist'),
        ('accounts', '0013_auto_20151222_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dashboard_component_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trans.ComponentList', verbose_name='Default component list'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dashboard_view',
            field=models.IntegerField(choices=[(1, 'Your subscriptions'), (2, 'Your languages'), (3, 'All projects'), (4, 'Component list')], default=1, verbose_name='Default dashboard view'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('az', 'Az\u0259rbaycan'), ('be', '\u0411\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f'), ('be@latin', 'Bie\u0142aruskaja'), ('br', 'Brezhoneg'), ('ca', 'Catal\xe0'), ('cs', '\u010ce\u0161tina'), ('da', 'Dansk'), ('de', 'Deutsch'), ('en', 'English'), ('el', '\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac'), ('es', 'Espa\xf1ol'), ('fi', 'Suomi'), ('fr', 'Fran\xe7ais'), ('fy', 'Frysk'), ('gl', 'Galego'), ('he', '\u05e2\u05d1\u05e8\u05d9\u05ea'), ('hu', 'Magyar'), ('id', 'Indonesia'), ('it', 'Italiano'), ('ja', '\u65e5\u672c\u8a9e'), ('ko', '\ud55c\uad6d\uc5b4'), ('ksh', 'K\xf6lsch'), ('nl', 'Nederlands'), ('pl', 'Polski'), ('pt', 'Portugu\xeas'), ('pt-br', 'Portugu\xeas brasileiro'), ('ru', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'), ('sk', 'Sloven\u010dina'), ('sl', 'Sloven\u0161\u010dina'), ('sr', '\u0421\u0440\u043f\u0441\u043a\u0438'), ('sv', 'Svenska'), ('tr', 'T\xfcrk\xe7e'), ('uk', '\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430'), ('zh-hans', '\u7b80\u4f53\u5b57'), ('zh-hant', '\u6b63\u9ad4\u5b57')], max_length=10, verbose_name='Interface Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondary_languages',
            field=models.ManyToManyField(blank=True, help_text='Choose languages you can understand, strings in those languages will be shown in addition to the source string.', related_name='secondary_profile_set', to='lang.Language', verbose_name='Secondary languages'),
        ),
    ]
