# Generated by Django 3.2 on 2021-05-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20210506_1421"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "verbose_name": "Audit log entry",
                "verbose_name_plural": "Audit log entries",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "User profile",
                "verbose_name_plural": "User profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "verbose_name": "Notification subscription",
                "verbose_name_plural": "Notification subscriptions",
            },
        ),
        migrations.AlterModelOptions(
            name="verifiedemail",
            options={
                "verbose_name": "Verified e-mail",
                "verbose_name_plural": "Verified e-mails",
            },
        ),
    ]
