# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.1.4 on 2024-12-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_subscription_unique_together_and_more"),
        ("trans", "0025_alter_announcement_notify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="watched",
            field=models.ManyToManyField(
                blank=True,
                help_text="You can receive notifications for watched projects and they are shown on the dashboard by default. You can right click on a project above to inspect it, before choosing.",
                to="trans.project",
                verbose_name="Watched projects",
            ),
        ),
    ]
