# Generated by Django 2.2.5 on 2019-09-22 17:48

from django.db import migrations


def migrate_dashboard(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    db_alias = schema_editor.connection.alias
    Profile.objects.using(db_alias).filter(dashboard_view=2).update(dashboard_view=1)


class Migration(migrations.Migration):

    dependencies = [("accounts", "0014_auto_20190922_1947")]

    operations = [
        migrations.RunPython(
            migrate_dashboard, migrations.RunPython.noop, elidable=True
        )
    ]
