# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import weblate.trans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
        ('accounts', '0014_auto_20160302_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', weblate.trans.fields.RegexField(default='^.*$', help_text='Regular expression which is used to match user email.', max_length=200, verbose_name='Email regular expression')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group to assign')),
            ],
            options={
                'ordering': ('group__name',),
                'verbose_name': 'Automatic group assignment',
                'verbose_name_plural': 'Automatic group assignments',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, help_text='You can receive notifications for subscribed projects and they are shown on dashboard by default.', to='trans.Project', verbose_name='Subscribed projects'),
        ),
    ]
