# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.1 on 2025-05-20 09:23

from django.db import migrations, models

import weblate.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_auditlog_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contact",
            field=models.URLField(
                blank=True,
                help_text="Link to contact you online using services like Signal, SimpleX or Telegram.",
                validators=[weblate.utils.validators.WeblateURLValidator()],
                verbose_name="Contact URL",
            ),
        ),
    ]
