# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20160304_1418'),
        ('authtoken', '0001_initial'),
        ('auth', '0001_initial'),
    ]

    operations = [
    ]
