# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20160304_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dashboard_view',
            field=models.IntegerField(choices=[(1, 'Your subscriptions'), (2, 'Your languages'), (3, 'All projects'), (4, 'Component list'), (5, 'Manager dashboard')], default=1, verbose_name='Default dashboard view'),
        ),
    ]
