# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add-api-keys'),
        ('auth', '0001_initial'),
    ]

    operations = [
    ]
