# Generated by Django 3.0.4 on 2020-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_auto_20191115_2020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="notification",
            field=models.CharField(
                choices=[
                    ("MergeFailureNotification", "Repository failure"),
                    ("RepositoryNotification", "Repository operation"),
                    ("ParseErrorNotification", "Parse error"),
                    ("NewStringNotificaton", "New string"),
                    ("NewContributorNotificaton", "New contributor"),
                    ("NewSuggestionNotificaton", "New suggestion"),
                    ("LastAuthorCommentNotificaton", "Comment on own translation"),
                    ("MentionCommentNotificaton", "Mentioned in comment"),
                    ("NewCommentNotificaton", "New comment"),
                    ("ChangedStringNotificaton", "Changed string"),
                    ("NewTranslationNotificaton", "New language"),
                    ("NewComponentNotificaton", "New translation component"),
                    ("NewAnnouncementNotificaton", "New announcement"),
                    ("NewAlertNotificaton", "New alert"),
                    ("PendingSuggestionsNotification", "Pending suggestions"),
                    ("ToDoStringsNotification", "Strings needing action"),
                ],
                max_length=100,
            ),
        ),
    ]
