# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 5.2.1 on 2025-05-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_profile_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contribute_personal_tm",
            field=models.BooleanField(
                default=True,
                help_text="Allow your translations to be added to your personal translation memory.",
                verbose_name="Contribute to personal translation memory",
            ),
        ),
    ]
