# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.4 on 2025-07-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_profile_contribute_personal_tm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dashboard_view",
            field=models.IntegerField(
                choices=[
                    (1, "Watched translations"),
                    (6, "All component lists"),
                    (4, "Component list"),
                    (5, "Suggested translations"),
                    (7, "Managed projects"),
                ],
                default=1,
                verbose_name="Default dashboard view",
            ),
        ),
    ]
