# Generated by Django 3.0.4 on 2020-03-18 10:21

from django.db import migrations


def migrate_announcement(apps, schema_editor):
    Subscription = apps.get_model("accounts", "Subscription")
    db_alias = schema_editor.connection.alias

    Subscription.objects.using(db_alias).filter(
        notification="NewWhiteboardMessageNotificaton"
    ).update(notification="NewAnnouncementNotificaton")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_auto_20200318_1014"),
    ]

    operations = [
        migrations.RunPython(
            migrate_announcement, migrations.RunPython.noop, elidable=True
        )
    ]
