# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_anonymous_profile'),
    ]

    operations = [
    ]
