# Generated by Django 3.0.5 on 2020-04-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_announcement_rename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="activity",
            field=models.CharField(
                choices=[
                    ("auth-connect", "auth-connect"),
                    ("auth-disconnect", "auth-disconnect"),
                    ("connect", "connect"),
                    ("email", "email"),
                    ("failed-auth", "failed-auth"),
                    ("full_name", "full_name"),
                    ("invited", "invited"),
                    ("locked", "locked"),
                    ("login", "login"),
                    ("login-new", "login-new"),
                    ("password", "password"),
                    ("register", "register"),
                    ("removed", "removed"),
                    ("reset", "reset"),
                    ("reset-request", "reset-request"),
                    ("tos", "tos"),
                    ("username", "username"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
