# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20160520_1358'),
    ]

    operations = [
    ]
