# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 11:58
from __future__ import unicode_literals

from django.db import migrations


def remove_projects_dashboard(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.filter(
        # Profile.DASHBOARD_ALL
        dashboard_view=3
    ).update(
        # Profile.DASHBOARD_SUBSCRIPTIONS
        dashboard_view=1
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20160520_1358'),
    ]

    operations = [
        migrations.RunPython(remove_projects_dashboard),
    ]
