# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.6 on 2025-10-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_alter_auditlog_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="activity",
            field=models.CharField(
                choices=[
                    ("accepted", "accepted"),
                    ("admin-locked", "admin-locked"),
                    ("auth-connect", "auth-connect"),
                    ("auth-disconnect", "auth-disconnect"),
                    ("autocreated", "autocreated"),
                    ("blocked", "blocked"),
                    ("connect", "connect"),
                    ("disabled", "disabled"),
                    ("disabled-expiry", "disabled-expiry"),
                    ("donate", "donate"),
                    ("email", "email"),
                    ("enabled", "enabled"),
                    ("failed-auth", "failed-auth"),
                    ("full_name", "full_name"),
                    ("invited", "invited"),
                    ("locked", "locked"),
                    ("login", "login"),
                    ("login-new", "login-new"),
                    ("password", "password"),
                    ("recovery-generate", "recovery-generate"),
                    ("recovery-show", "recovery-show"),
                    ("register", "register"),
                    ("removal-request", "removal-request"),
                    ("removed", "removed"),
                    ("reset", "reset"),
                    ("reset-request", "reset-request"),
                    ("sent-email", "sent-email"),
                    ("team-add", "team-add"),
                    ("team-remove", "team-remove"),
                    ("tos", "tos"),
                    ("trial", "trial"),
                    ("twofactor-add", "twofactor-add"),
                    ("twofactor-failed", "twofactor-failed"),
                    ("twofactor-login", "twofactor-login"),
                    ("twofactor-remove", "twofactor-remove"),
                    ("username", "username"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
