# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.10 on 2026-01-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_audit_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="commit_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Commit name",
            ),
        ),
    ]
