# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.10 on 2026-01-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_audit_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="commit_name",
            field=models.IntegerField(
                choices=[
                    (0, "Use global default"),
                    (1, "Public"),
                    (2, "Private"),
                ],
                default=0,
                verbose_name="Commit name",
            ),
        ),
    ]
