# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20160520_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dashboard_view',
            field=models.IntegerField(choices=[(1, 'Watched'), (2, 'Your languages'), (4, 'Component list'), (5, 'Suggested translations')], default=1, verbose_name='Default dashboard view'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, help_text='You can receive notifications for watched projects and they are shown on dashboard by default.', to='trans.Project', verbose_name='Watched projects'),
        ),
    ]
