# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.11 on 2026-02-09 16:00

from django.db import migrations, models

import weblate.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_add_commit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="contribute_personal_tm",
            field=models.BooleanField(
                default=weblate.accounts.models.get_default_contribute_personal_tm,
                help_text="Allow your translations to be added to your personal translation memory.",
                verbose_name="Contribute to personal translation memory",
            ),
        ),
    ]
