# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:09
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import weblate.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('accounts', '0024_auto_20161024_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeblateAnonymousUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='editor_link',
            field=models.CharField(blank=True, default='', help_text='Enter custom URL to be used as link to open source code. You can use %(branch)s for branch, %(file)s and %(line)s as filename and line placeholders. Usually something like editor://open/?file=%(file)s&line=%(line)s is good option.', max_length=200, validators=[weblate.utils.validators.validate_repoweb], verbose_name='Editor link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('az', 'Az\u0259rbaycan'), ('be', '\u0411\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f'), ('be@latin', 'Bie\u0142aruskaja'), ('bg', '\u0411\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438'), ('br', 'Brezhoneg'), ('ca', 'Catal\xe0'), ('cs', '\u010ce\u0161tina'), ('da', 'Dansk'), ('de', 'Deutsch'), ('en', 'English'), ('el', '\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac'), ('es', 'Espa\xf1ol'), ('fi', 'Suomi'), ('fr', 'Fran\xe7ais'), ('fy', 'Frysk'), ('gl', 'Galego'), ('he', '\u05e2\u05d1\u05e8\u05d9\u05ea'), ('hu', 'Magyar'), ('id', 'Indonesia'), ('it', 'Italiano'), ('ja', '\u65e5\u672c\u8a9e'), ('ko', '\ud55c\uad6d\uc5b4'), ('ksh', 'K\xf6lsch'), ('nb', 'Norsk bokm\xe5l'), ('nl', 'Nederlands'), ('pl', 'Polski'), ('pt', 'Portugu\xeas'), ('pt-br', 'Portugu\xeas brasileiro'), ('ru', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'), ('sk', 'Sloven\u010dina'), ('sl', 'Sloven\u0161\u010dina'), ('sr', '\u0421\u0440\u043f\u0441\u043a\u0438'), ('sv', 'Svenska'), ('tr', 'T\xfcrk\xe7e'), ('uk', '\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430'), ('zh-hans', '\u7b80\u4f53\u5b57'), ('zh-hant', '\u6b63\u9ad4\u5b57')], max_length=10, verbose_name='Interface Language'),
        ),
    ]
