# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.1 on 2023-06-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_profile_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="notification",
            field=models.CharField(
                choices=[
                    ("RepositoryNotification", "Repository operation"),
                    ("LockNotification", "Component locking"),
                    ("LicenseNotification", "Changed license"),
                    ("ParseErrorNotification", "Parse error"),
                    ("NewStringNotificaton", "New string"),
                    ("NewContributorNotificaton", "New contributor"),
                    ("NewSuggestionNotificaton", "New suggestion"),
                    ("NewCommentNotificaton", "New comment"),
                    ("MentionCommentNotificaton", "Mentioned in comment"),
                    ("LastAuthorCommentNotificaton", "Comment on own translation"),
                    ("TranslatedStringNotificaton", "Translated string"),
                    ("ChangedStringNotificaton", "Changed string"),
                    ("ApprovedStringNotificaton", "Approved string"),
                    ("NewTranslationNotificaton", "New language"),
                    ("NewComponentNotificaton", "New translation component"),
                    ("NewAnnouncementNotificaton", "New announcement"),
                    ("NewAlertNotificaton", "New alert"),
                    ("MergeFailureNotification", "Repository failure"),
                    ("PendingSuggestionsNotification", "Pending suggestions"),
                    ("ToDoStringsNotification", "Unfinished strings"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="notification",
            field=models.CharField(
                choices=[
                    ("RepositoryNotification", "Repository operation"),
                    ("LockNotification", "Component locking"),
                    ("LicenseNotification", "Changed license"),
                    ("ParseErrorNotification", "Parse error"),
                    ("NewStringNotificaton", "New string"),
                    ("NewContributorNotificaton", "New contributor"),
                    ("NewSuggestionNotificaton", "New suggestion"),
                    ("NewCommentNotificaton", "New comment"),
                    ("MentionCommentNotificaton", "Mentioned in comment"),
                    ("LastAuthorCommentNotificaton", "Comment on own translation"),
                    ("TranslatedStringNotificaton", "Translated string"),
                    ("ApprovedStringNotificaton", "Approved string"),
                    ("ChangedStringNotificaton", "Changed string"),
                    ("NewTranslationNotificaton", "New language"),
                    ("NewComponentNotificaton", "New translation component"),
                    ("NewAnnouncementNotificaton", "New announcement"),
                    ("NewAlertNotificaton", "New alert"),
                    ("MergeFailureNotification", "Repository failure"),
                    ("PendingSuggestionsNotification", "Pending suggestions"),
                    ("ToDoStringsNotification", "Unfinished strings"),
                ],
                max_length=100,
            ),
        ),
    ]
