# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20170211_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='special_chars',
            field=models.CharField(blank=True, default='', help_text='You can specify additional special characters to be shown in the visual keyboard while translating. It can be useful for chars you use frequently but are hard to type on your keyboard.', max_length=30, verbose_name='Special characters'),
        ),
    ]
