# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.3 on 2026-04-23

from django.db import migrations, models

import weblate.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_alter_auditlog_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="contact",
            field=models.URLField(
                blank=True,
                help_text="Link to contact you online using services like Signal, SimpleX or Telegram.",
                validators=[
                    weblate.utils.validators.WeblateURLValidator(),
                    weblate.utils.validators.validate_contact_url,
                ],
                verbose_name="Contact URL",
            ),
        ),
    ]
