# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.1 on 2023-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_alter_subscription_notification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="notification",
            field=models.CharField(
                choices=[
                    ("RepositoryNotification", "Repository operation"),
                    ("LockNotification", "Component locking"),
                    ("LicenseNotification", "Changed license"),
                    ("ParseErrorNotification", "Parse error"),
                    ("NewStringNotificaton", "New string"),
                    ("NewContributorNotificaton", "New contributor"),
                    ("NewSuggestionNotificaton", "New suggestion"),
                    ("NewCommentNotificaton", "New comment"),
                    ("MentionCommentNotificaton", "Mentioned in comment"),
                    ("LastAuthorCommentNotificaton", "Comment on own translation"),
                    ("TranslatedStringNotificaton", "Edited string"),
                    ("ApprovedStringNotificaton", "Approved string"),
                    ("ChangedStringNotificaton", "Changed string"),
                    ("NewTranslationNotificaton", "New language"),
                    ("NewComponentNotificaton", "New translation component"),
                    ("NewAnnouncementNotificaton", "New announcement"),
                    ("NewAlertNotificaton", "New alert"),
                    ("MergeFailureNotification", "Repository failure"),
                    ("PendingSuggestionsNotification", "Pending suggestions"),
                    ("ToDoStringsNotification", "Unfinished strings"),
                ],
                max_length=100,
            ),
        ),
    ]
