# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.3 on 2026-04-23

from django.db import migrations, models

import weblate.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_alter_profile_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="codesite",
            field=models.URLField(
                blank=True,
                help_text="Link to your code profile for services like Codeberg or GitLab.",
                validators=[
                    weblate.utils.validators.WeblateURLValidator(),
                    weblate.utils.validators.validate_code_site_url,
                ],
                verbose_name="Code site URL",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fediverse",
            field=models.URLField(
                blank=True,
                help_text="Link to your Fediverse profile for federated services like Mastodon or diaspora*.",
                validators=[
                    weblate.utils.validators.WeblateURLValidator(),
                    weblate.utils.validators.validate_fediverse_url,
                ],
                verbose_name="Fediverse URL",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.URLField(
                blank=True,
                validators=[
                    weblate.utils.validators.WeblateURLValidator(),
                    weblate.utils.validators.validate_profile_url,
                ],
                verbose_name="Website URL",
            ),
        ),
    ]
