# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_alter_subscription_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="params_new",
            field=models.JSONField(default=dict),
        ),
    ]
