# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import weblate.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0028_auto_20170323_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='editor_link',
            field=models.CharField(blank=True, default='', help_text='Enter custom URL to be used as link to open source code. You can use %(branch)s for branch, %(file)s and %(line)s as filename and line placeholders. Usually something like editor://open/?file=%(file)s&line=%(line)s is good option.', max_length=200, validators=[weblate.utils.validators.validate_editor], verbose_name='Editor link'),
        ),
    ]
