# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='activity',
            field=models.CharField(choices=[('auth-connect', 'auth-connect'), ('auth-disconnect', 'auth-disconnect'), ('connect', 'connect'), ('failed-auth', 'failed-auth'), ('locked', 'locked'), ('login', 'login'), ('password', 'password'), ('register', 'register'), ('reset', 'reset')], db_index=True, max_length=20),
        ),
    ]
