# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-04 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0030_remove_auditlog_params"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditlog",
            old_name="params_new",
            new_name="params",
        ),
    ]
