# -*- coding: utf-8 -*-
# Generated by Django 1.11.8.dev20171123183638 on 2017-11-29 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20171025_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='activity',
            field=models.CharField(choices=[('auth-connect', 'auth-connect'), ('auth-disconnect', 'auth-disconnect'), ('connect', 'connect'), ('failed-auth', 'failed-auth'), ('locked', 'locked'), ('login', 'login'), ('login-new', 'login-new'), ('password', 'password'), ('register', 'register'), ('removed', 'removed'), ('reset', 'reset'), ('reset-request', 'reset-request'), ('tos', 'tos')], db_index=True, max_length=20),
        ),
    ]
