# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 08:44
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20171129_1438'),
    ]

    operations = [
    ]
