# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

from django.db import migrations
from django.db.models import Count, F, Max, Min


def deduplicate_totp_devices(apps, schema_editor) -> None:
    """Preserve replay protection when merging equivalent authenticators."""
    device_model = apps.get_model("otp_totp", "TOTPDevice")
    devices = device_model.objects.using(schema_editor.connection.alias)
    # Drift adapts during verification, and tolerance only controls acceptance;
    # neither changes the sequence generated by an authenticator.
    fields = ("user_id", "key", "step", "t0", "digits")
    duplicates = (
        devices.filter(confirmed=True)
        .order_by()
        .values(*fields)
        .annotate(
            count=Count("pk"),
            keep=Min("pk"),
            last_t=Max("last_t"),
            last_used_at=Max("last_used_at"),
            failure_count=Max("throttling_failure_count"),
            failure_timestamp=Max("throttling_failure_timestamp"),
        )
        .filter(count__gt=1)
    )
    for duplicate in duplicates.iterator():
        matching = devices.filter(
            confirmed=True, **{field: duplicate[field] for field in fields}
        )
        # Use the most recently verified clock offset. If usage timestamps are
        # unavailable, prefer the highest consumed timestep, then the oldest ID.
        drift = matching.order_by(
            F("last_used_at").desc(nulls_last=True), "-last_t", "pk"
        ).values_list("drift", flat=True)[0]
        devices.filter(pk=duplicate["keep"]).update(
            drift=drift,
            last_t=duplicate["last_t"],
            last_used_at=duplicate["last_used_at"],
            throttling_failure_count=duplicate["failure_count"],
            throttling_failure_timestamp=duplicate["failure_timestamp"],
        )
        matching.exclude(pk=duplicate["keep"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0035_profile_listing_columns"),
        ("otp_totp", "0003_add_timestamps"),
    ]

    operations = [
        migrations.RunPython(deduplicate_totp_devices, migrations.RunPython.noop),
    ]
