# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20180201_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dashboard_view',
            field=models.IntegerField(choices=[(1, 'Watched translations'), (2, 'Your languages'), (6, 'Component lists'), (4, 'Component list'), (5, 'Suggested translations')], default=1, verbose_name='Default dashboard view'),
        ),
    ]
