# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0069_source_screenshot'),
    ]

    operations = [
    ]
