#!/bin/sh

# Simple wrapper to start/stop celery workers

python -m celery -A weblate multi $1 \
    search notify celery memory backup \
    --pidfile=weblate-%n.pid \
    --logfile=weblate-%n%I.log --loglevel=DEBUG \
    --beat:celery --concurrency:celery=4 --queues:celery=celery --prefetch-multiplier:celery=4 \
    --concurrency:notify=4 --queues:notify=notify --prefetch-multiplier:notify=4 \
    --concurrency:search=1 --queues:search=search --prefetch-multiplier:search=2000 \
    --concurrency:memory=1 --queues:memory=memory --prefetch-multiplier:memory=2000 \
    --concurrency:backup=1 --queues:backup=backup 
