#!/bin/sh

# Simple wrapper to start/stop celery workers

python -m celery -A weblate.utils multi $1 \
    search notify celery memory backup translate \
    --pidfile=$PWD/weblate-%n.pid \
    --logfile=$PWD/weblate-%n%I.log --loglevel=DEBUG \
    --beat:celery --concurrency:celery=4 --queues:celery=celery --prefetch-multiplier:celery=4 \
    --concurrency:notify=4 --queues:notify=notify --prefetch-multiplier:notify=10 \
    --concurrency:memory=1 --queues:memory=memory --prefetch-multiplier:memory=4 \
    --concurrency:translate=2 --queues:translate=translate --prefetch-multiplier:translate=4 \
    --concurrency:backup=1 --queues:backup=backup  --prefetch-multiplier:backup=2
