#!/bin/sh
#
# Copyright © 2014 Daniel Tschan <tschan@puzzle.ch>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Upgrade pip and install wheel to allow installation of wheels
pip install --no-cache-dir --upgrade pip wheel
# Pin Django version to 1.12 to avoid surprises when 1.12 comes out.
pip install 'Django>=1.11,<1.12'

# Show install/update page, will be replaced with app by install.sh
# Link sources below $OPENSHIFT_REPO_DIR must be relative or they will be invalid after restore/clone operations
mkdir -p $OPENSHIFT_REPO_DIR/wsgi
ln -sf ../openshift/wsgi_install.py $OPENSHIFT_REPO_DIR/wsgi/application
