# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

SPDX-PackageDownloadLocation = "https://weblate.org/"
SPDX-PackageName = "Weblate"
SPDX-PackageSupplier = "Michal Čihař <michal@weblate.org>"
version = 1

[[annotations]]
path = [
  "AGENTS.md",
  "BACKERS.rst",
  "ci/README.rst",
  "CONTACT.md",
  "CONTRIBUTING.md",
  "dev-docker/README.rst",
  "docs/**.html",
  "docs/**.png",
  "docs/**.rst",
  "docs/**.webp",
  "docs/specs/openapi.yaml",
  "README.rst"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["docs/contributing/code_of_conduct.rst"]
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
  "docs/specs/schemas/**.json"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "docs/locales/*/LC_MESSAGES/docs.po",
  "docs/locales/docs.pot",
  "weblate/locale/*/LC_MESSAGES/django.po",
  "weblate/locale/*/LC_MESSAGES/djangojs.po",
  "weblate/locale/django.pot",
  "weblate/locale/djangojs.pot"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "weblate/billing/test-data/00000.pdf",
  "weblate/trans/fixtures/simple-project.json",
  "weblate/trans/tests/data/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  "weblate/legal/templates/**",
  "weblate/templates/**",
  "weblate/wladmin/templates/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  ".dclintrc",
  ".editorconfig",
  ".gitattributes",
  ".gitignore",
  ".gitmodules",
  ".imgbotconfig",
  ".pre-commit-config.yaml",
  ".pylintrc",
  ".readthedocs.yml",
  ".weblate",
  ".well-known/funding-manifest-urls",
  "biome.json",
  "codecov.yml",
  "dev-docker/environment",
  "docs/requirements.txt",
  "MANIFEST.in",
  "pyproject.toml",
  "redocly.yaml",
  "scripts/codespell.txt",
  "security.yaml",
  "setup.cfg",
  "uv.lock",
  "weblate/examples/*"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  "docs/images/logo-text.svg",
  "weblate/static/access/**.svg",
  "weblate/static/email-logo**.png",
  "weblate/static/favicon.ico",
  "weblate/static/logo-**.png",
  "weblate/static/weblate**.png",
  "weblate/static/weblate**.svg",
  "weblate/static/widget-images/**.png"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "weblate/static/auth/**.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  "weblate/static/anubis/**.svg",
  "weblate/static/anubis/**.webp"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  "weblate/static/api-*.png",
  "weblate/static/icons/**.svg",
  "weblate/static/sort/**.svg",
  "weblate/static/state/**.svg"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Pictogrammers"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "weblate/static/priorities/**.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "Samuel Gomes <samuel.esteves.gomes@tecnico.ulisboa.pt>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "weblate/static/vendor/prism/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Lea Verou"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "client/package.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "client/yarn.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["weblate/addons/extractors/gettext/its/polkit.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = [
  "2008-2024 Red Hat, Inc.",
  "2009-2010 Andrew Psaltis",
  "2010 Antoine Jacoutot",
  "2011 Google Inc.",
  "2013 SUSE Linux GmbH",
  "2015 Tangent Space",
  "2016-2021 Free Software Foundation, Inc.",
  "2019 The Meson development team",
  "2019 Wu Xiaotian",
  "2020 Karl Ove Hufthammer"
]
SPDX-License-Identifier = "LGPL-2.0-or-later AND MIT"

[[annotations]]
path = ["weblate/addons/extractors/gettext/its/gtkbuilder.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = [
  "Copyright (C) 1986, 1987, 1998  The Open Group",
  "Copyright (C) 1991-1993, 1995, 1999-2010 Free Software Foundation, Inc.",
  "Copyright (C) 1993 Robert Nation",
  "Copyright (C) 1995, 1996, 1997, 1998 Steffen Beyer",
  "Copyright (C) 1995-2007 Peter Mattis, Spencer Kimball and Josh MacDonald",
  "Copyright (C) 1995-2007 Ryan Lortie",
  "Copyright (C) 1996-2007, 2009 Sun Microsystems, Inc.",
  "Copyright (C) 1997-2010 The GTK Team",
  "Copyright (C) 1998 Cesar Miquel and Shawn T. Amundson",
  "Copyright (C) 1998 David Abilleira Freijeiro <odaf@nexo.es>",
  "Copyright (C) 1998 Elliot Lee",
  "Copyright (C) 1998 Jiří Pavlovský <pavlovsk@ff.cuni.cz>",
  "Copyright (C) 1998 Lars Hamann and Stefan Jeske",
  "Copyright (C) 1998 Shawn T. Amundson",
  "Copyright (C) 1998 Stanislav Brabec <utx@k332.feld.cvut.cz>",
  "Copyright (C) 1998, 2002 Owen Taylor",
  "Copyright (C) 1998-2001, 2005, 2006 Tim Janik",
  "Copyright (C) 1998-2004 Tor Lillqvist",
  "Copyright (C) 1998-2020 Red Hat, Inc.",
  "Copyright (C) 1999 Mark Crichton, Larry Ewing",
  "Copyright (C) 1999 Michael Zucchi",
  "Copyright (C) 2000 SuSE Linux Ltd",
  "Copyright (C) 2000-2002 Keith Packard",
  "Copyright (C) 2001 Archaeopteryx Software Inc.",
  "Copyright (C) 2001 CodeFactory AB",
  "Copyright (C) 2001 Havoc Pennington",
  "Copyright (C) 2001 Stefan Ondrejicka",
  "Copyright (C) 2001,2002,2004 Anders Carlsson <andersca@gnu.org>",
  "Copyright (C) 2001-2003, 2006, 2007, 2009, 2010 Kristian Rietveld <kris@gtk.org>",
  "Copyright (C) 2001-2005 Hans Breuer",
  "Copyright (C) 2002 James Henstridge <james@daa.com.au>",
  "Copyright (C) 2002 Naba Kumar <kh_naba@users.sourceforge.net>",
  "Copyright (C) 2002 Sayed Jaffer Al-Mosawi <mosawi@arabeyes.org>",
  "Copyright (C) 2003 Alex Graveley",
  "Copyright (C) 2003 Apple Computer, Inc.",
  "Copyright (C) 2003 Ricardo Fernandez Pascual",
  "Copyright (C) 2003 Takuro Ashie",
  "Copyright (C) 2003, 2004 Dom Lachowicz <cinamod@hotmail.com>",
  "Copyright (C) 2003, 2004 Raymond Penners <raymond@dotsphinx.com>",
  "Copyright (C) 2003, 2004 Soeren Sandmann <sandmann@daimi.au.dk>",
  "Copyright (C) 2003, 2004, 2006, 2009 Matthias Clasen <mclasen@redhat.com>",
  "Copyright (C) 2003-2004 Kazuki IWAMOTO",
  "Copyright (c) 2004 James M. Cape <jcape@ignore-your.tv>",
  "Copyright (C) 2004 Lorenzo Gil Sanchez",
  "Copyright (C) 2004 Paolo Borelli",
  "Copyright (C) 2004-2006 Christian Hammond",
  "Copyright (C) 2004-2009 GNOME Foundation",
  "Copyright (C) 2004-2011 Nokia Corporation",
  "Copyright (C) 2005 Jamie McCracken <jamiemcc@gnome.org>",
  "Copyright (C) 2005 Novell, Inc.",
  "Copyright (C) 2005 Paolo Maggi",
  "Copyright (C) 2005 Ronald S. Bultje",
  "Copyright (C) 2005,2007-2009 Carlos Garnacho <carlosg@gnome.org>",
  "Copyright (C) 2005-2007 Emmanuele Bassi",
  "Copyright (C) 2005-2007 Vincent Untz",
  "Copyright (C) 2005-2008 Imendio AB",
  "Copyright (C) 2006 Alexander Larsson <alexl@redhat.com>",
  "Copyright (C) 2006 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>",
  "Copyright (C) 2006 John (J5) Palmieri <johnp@redhat.com>",
  "Copyright (C) 2006,2008 Jan Arne Petersen",
  "Copyright (C) 2006-2007 Async Open Source",
  "Copyright (C) 2006-2008, 2010 Christian Persch",
  "Copyright (C) 2006-2010 Openismus GmbH",
  "Copyright (C) 2007 John Stowers, Neil Jagdish Patel",
  "Copyright (C) 2007-2009 Cody Russell",
  "Copyright (C) 2008 Jaap Haitsma <jaap@haitsma.org>",
  "Copyright (C) 2008 Richard Hughes <richard@hughsie.com>",
  "Copyright (C) 2008 Tadej Borovšak <tadeboro@gmail.com>",
  "Copyright (C) 2008 Tristan Van Berkom <tristan.van.berkom@gmail.com>",
  "Copyright (C) 2009 Bastien Nocera",
  "Copyright (C) 2009 Ghee Teo <ghee.teo@sun.com>",
  "Copyright (C) 2009 Stefan Walter <stef@memberwebs.com>",
  "Copyright (C) 2010 Christian Dywan",
  "Copyright (C) 2010 Codethink Limited",
  "Copyright (C) 2010 Damyan Ivanov <dam+gnome@ktnx.net>",
  "Copyright (C) 2010 Israt Jahan <israt@ankur.org.bd>",
  "Copyright (C) 2010 Sadia Afroz <sadia@ankur.org.bd>",
  "Copyright (C) 2010 Xandru Armesto <xandru@softastur.org>",
  "Copyright (C) 2018 Microsoft",
  "Copyright (C) 2021 Philip Zander",
  "Copyright (C) Christian Kellner <gicmo@gnome.org>",
  "Copyright (C) David Zeuthen <davidz@redhat.com>",
  "Copyright (C) Federico Mena",
  "Copyright (C) Javier Jardón <jjardon@gnome.org>",
  "Copyright 2012 Collabora Ltd.",
  "Copyright 2012 Intel Corporation"
]
SPDX-License-Identifier = "LGPL-2.0-or-later"

[[annotations]]
path = ["weblate/addons/extractors/gettext/its/gschema.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = [
  "1991-2024 Free Software Foundation, Inc",
  "1995-1997 Ulrich Drepper",
  "1995-1998 Josh MacDonald",
  "1995-1998 Spencer Kimball",
  "1995-2011 Peter Mattis",
  "1995-2011 Peter Mattis, Spencer Kimball, Josh MacDonald, Sebastian Wilhelmi and others",
  "1997-2007 Tim Janik",
  "1998-2001 Owen Taylor",
  "1998-2001 Sebastian Wilhelmi; University of Karlsruhe",
  "1998-2004 Tor Lillqvist",
  "1999-2000 Craig Setera",
  "1999-2000 Scott Wimer",
  "1999-2000 Tom Tromey",
  "1999-2003 Red Hat Software",
  "2000 Eazel, Inc",
  "2000-2004 Ximian Inc",
  "2000-2024 Red Hat, Inc",
  "2001 Hidetoshi Tajima",
  "2001 James Henstridge",
  "2001 Ron Steinke",
  "2001-2003 Andrew Lanoix",
  "2001-2006 Behdad Esfahbod",
  "2001-2008 Hans Breuer",
  "2001-2022 GLib contributors",
  "2001-2023 Matthias Clasen",
  "2001-2023 Sebastian Wilhelmi",
  "2002 Manish Singh",
  "2002-2006 Sharif FarsiWeb, Inc",
  "2002-2007 Soeren Sandmann",
  "2002-2022 the author(s) of GLib",
  "2003 Noah Levitt",
  "2003-2006 Josh Parsons",
  "2004 Anders Carlsson",
  "2004-2005 Adam Weinberger",
  "2004-2005 Miloslav Trmac",
  "2005 Stefan Kost",
  "2005-2006 Alexander Larsson",
  "2005-2007 John McCutchan",
  "2005-2007 Marco Barisione",
  "2005-2008 Imendio AB",
  "2005-2023 Emmanuele Bassi",
  "2005-2024 Canonical Ltd",
  "2006 Lukas Novotny",
  "2006 Padraig O'Briain",
  "2006 Stefan Westerfeld",
  "2006 The GNOME Foundation",
  "2007 Andrew Walton",
  "2007 Francois Gouget",
  "2007 Jürg Billeter",
  "2007 Lennart Poettering",
  "2007 Patrick Hulin",
  "2007 Sebastian Dröge",
  "2007-2008 A. Walton",
  "2007-2010 Johan Dahlin",
  "2007-2010 Sven Herzberg",
  "2007-2011 The GNOME Project",
  "2007-2015 Ryan Lortie",
  "2008 Claus Tondering",
  "2008 Clemens N. Buss",
  "2008 litl, LLC",
  "2008 Philip Van Hoof",
  "2008 Samuel Cormier-Iijima",
  "2008-2010 Christian Kellner",
  "2008-2010 Novell, Inc",
  "2008-2011 Nokia Corporation",
  "2008-2013 Colin Walters",
  "2008-2014 Codethink Ltd",
  "2008-2024 Collabora Ltd",
  "2009 Benjamin Otte",
  "2009-2010 Christian Persch",
  "2009-2016 Sam Thursfield",
  "2009-2024 Christian Hergert",
  "2010 David Zeuthen",
  "2010 Intel Corp",
  "2010 Karo Mkrtchyan",
  "2010 Mikhail Zabaluev",
  "2010 Thiago Santos",
  "2010-2011 Allison Lortie",
  "2010-2012 Dan Winship",
  "2010-2013 Allison Karlitskaya",
  "2011 Carlos Garcia Campos",
  "2011 Laszlo Pandy",
  "2011 Murray Cumming",
  "2011 Sjoerd Simons",
  "2011 Torsten Schönfeld",
  "2011 William Hua",
  "2011-2012 Pavel Holejsovsky",
  "2011-2013 Stef Walter",
  "2011-2014 Giovanni Campagna",
  "2011-2022 Ray Strode",
  "2011-2022 systemd contributors",
  "2012 David King",
  "2012 Olivier Sessink",
  "2012 Pavel Vasin",
  "2012 Swecha telugu localisation Team",
  "2012-2020 Aleksander Morgado",
  "2012-2023 Simon McVittie",
  "2013 Martin Pitt",
  "2013-2015 Dieter Verfaillie",
  "2013-2015 Lars Uebernickel",
  "2014 NICE s.r.l",
  "2014 Robert Roth",
  "2014 Simon Feltman",
  "2014-2018 Jan-Michael Brummer",
  "2014-2019 Patrick Griffis",
  "2014-2020 Руслан Ижбулатов",
  "2014-2024 Chun-wei Fan",
  "2015 Ben Boeckel",
  "2015 Garrett Regier",
  "2016 GNOME i18n Project for Vietnamese",
  "2016 Jeremy Whiting",
  "2016-2020 Centricular",
  "2016-2020 Endless Mobile, Inc",
  "2017 Danny Forghieri",
  "2017 Nirbheek Chauhan",
  "2017-2018 Collabora Inc",
  "2017-2022 Endless OS Foundation, LLC",
  "2018 Arnaud Bonatti",
  "2018 Arthur Demchenkov",
  "2018 Iñigo Martínez",
  "2018 Kai Kang",
  "2018 Mathieu Duponchelle",
  "2018 Ninja-Koala",
  "2018 Pavlo Solntsev",
  "2018 pdknsk",
  "2018 Peter Wu",
  "2018 segfault",
  "2018 Sébastien Wilmet",
  "2018 Tomasz Miąsko",
  "2018 Will Thompson",
  "2018-2019 James Westman",
  "2018-2020 Alexander Kanavin",
  "2018-2020 Christoph Reiter",
  "2018-2021 Igalia S.L",
  "2018-2024 Carlos Garnacho",
  "2019 Aaron Boxer",
  "2019 GNOME",
  "2019 Joshua Watt",
  "2019 Sebastian Schwarz",
  "2019 Thibault Saunier",
  "2019 Ting-Wei Lan",
  "2019-2022 Emmanuel Fleury",
  "2019-2024 Philip Chimento",
  "2020 Gisle Vanem",
  "2020 Jan Tojnar",
  "2020 Matt Rose",
  "2020 Ruslan N. Marchenko",
  "2020 William Manley",
  "2020 Wouter Bolsterlee",
  "2020-2021 Frederic Martinsons",
  "2020-2021 Xavier Claessens",
  "2021 Alexandros Theodotou",
  "2021 Casper Dik",
  "2021 Cimbali",
  "2021 Iain Lane",
  "2021 John Ericson",
  "2021 Ole André Vadla Ravnås",
  "2021-2024 Unicode®, Inc",
  "2022 Alexander Richardson",
  "2022 Andoni Morales Alastruey",
  "2022 Marco Trevisan",
  "2022 Peter Bloomfield",
  "2022 Ryan Hope",
  "2022 Thomas Haller",
  "2022-2023 Alexander Shopov",
  "2022-2023 David Rheinsberg",
  "2022-2023 Philip Withnall",
  "2023 CaiJingLong",
  "2023 Daniel Carpenter",
  "2023 Eli Schwartz",
  "2023 Guido Günther",
  "2023 JCWasmx86",
  "2023 Luca Bacci",
  "2023 Todd Carson",
  "2023-2024 GNOME Foundation Inc.",
  "2024 Evan Welsh",
  "2024 Frank Dana",
  "2024 Future Crew LLC",
  "2024 twlvnn kraftwerk",
  "Croatiann team",
  "Matthew Waters"
]
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = ["weblate/addons/extractors/gettext/its/shared-mime-info.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2002, 2003 Thomas Leonard"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["weblate/addons/extractors/gettext/its/metainfo.*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Matthias Klumpp and Takao Fujiwara"
SPDX-License-Identifier = "FSFAP"
