# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lang', '0011_auto_20180215_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('source_hash', models.BigIntegerField(editable=False)),
                ('target', models.TextField()),
                ('origin', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_source', to='lang.Language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_target', to='lang.Language')),
            ],
            options={
                'ordering': ['source'],
            },
        ),
        migrations.AlterIndexTogether(
            name='memory',
            index_together=set([('source_language', 'target_language', 'source_hash')]),
        ),
    ]
