# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.4 on 2026-05-06 08:20

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("memory", "0001_squashed_weblate_5"),
        ("memory", "0002_memory_memory_md5_index"),
        ("memory", "0003_drop_hash_index"),
    ]

    initial = True

    dependencies = [
        ("lang", "0001_squashed_weblate_5"),
        ("trans", "0001_squashed_weblate_5"),
        ("weblate_auth", "0002_squashed_weblate_5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.TextField()),
                ("target", models.TextField()),
                ("origin", models.TextField()),
                ("from_file", models.BooleanField(default=False)),
                ("shared", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trans.project",
                    ),
                ),
                (
                    "source_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_source_set",
                        to="lang.language",
                    ),
                ),
                (
                    "target_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_target_set",
                        to="lang.language",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation memory entry",
                "verbose_name_plural": "Translation memory entries",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            models.F("source"), name="gin_trgm_ops"
                        ),
                        models.F("target_language"),
                        models.F("source_language"),
                        name="memory_source_trgm",
                    ),
                    models.Index(
                        django.db.models.functions.text.MD5("origin"),
                        django.db.models.functions.text.MD5("source"),
                        django.db.models.functions.text.MD5("target"),
                        models.F("source_language"),
                        models.F("target_language"),
                        name="memory_md5_index",
                    ),
                    models.Index(
                        models.F("from_file"),
                        condition=models.Q(("from_file", True)),
                        name="memory_from_file",
                    ),
                ],
            },
        ),
    ]
