# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('memory', '0001_initial'), ('memory', '0002_init_whoosh'), ('memory', '0003_auto_20180321_1554')]

    initial = True

    dependencies = [
        ('lang', '0011_auto_20180215_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('source_hash', models.BigIntegerField(editable=False)),
                ('target', models.TextField()),
                ('origin', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_source', to='lang.Language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_target', to='lang.Language')),
            ],
            options={
                'ordering': ['source'],
            },
        ),
        migrations.AlterIndexTogether(
            name='memory',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='memory',
            name='source_language',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='target_language',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
