# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('memory', '0001_initial'), ('memory', '0002_init_whoosh'), ('memory', '0003_auto_20180321_1554')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
