# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.9 on 2024-01-26 14:15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memory", "0001_squashed_weblate_5"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="memory",
            index=models.Index(
                django.db.models.functions.text.MD5("origin"),
                django.db.models.functions.text.MD5("source"),
                django.db.models.functions.text.MD5("target"),
                models.F("source_language"),
                models.F("target_language"),
                name="memory_md5_index",
            ),
        ),
        migrations.AddIndex(
            model_name="memory",
            index=models.Index(
                models.F("from_file"),
                condition=models.Q(("from_file", True)),
                name="memory_from_file",
            ),
        ),
    ]
