# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_init_whoosh'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='memory',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='memory',
            name='source_language',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='target_language',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
