# Generated by Django 3.0.4 on 2020-03-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0004_memory_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="from_file",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="memory",
            name="shared",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
