# Generated by Django 3.0.4 on 2020-03-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0005_auto_20200310_0810"),
    ]

    operations = []
