# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.3 on 2025-07-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memory", "0005_set_memory_status_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="context",
            field=models.TextField(blank=True, default=""),
        ),
    ]
