# -*- coding: utf-8 -*-
# Generated by Django 3.0.4 on 2020-03-10 08:30

from django.db import migrations

from weblate.memory.tasks import import_memory


def update_memory(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Project = apps.get_model("trans", "Project")
    for project in Project.objects.using(db_alias).all().iterator():
        import_memory.delay(project.pk)


class Migration(migrations.Migration):

    dependencies = [("memory", "0005_auto_20200310_0810")]

    operations = [
        migrations.RunPython(update_memory, migrations.RunPython.noop, elidable=True)
    ]
