# Generated by Django 3.1.7 on 2021-03-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0008_adjust_similarity"),
    ]

    operations = []
