# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.4 on 2026-05-06 08:13

import django.db.migrations.operations.special
from django.db import migrations, models

CATEGORY_MT = 2


def migrate_machinery(apps, schema_editor) -> None:
    Setting = apps.get_model("configuration", "Setting")

    for name in ("weblate", "weblate-translation-memory"):
        Setting.objects.create(category=CATEGORY_MT, name=name, value={})


class Migration(migrations.Migration):
    replaces = [
        ("configuration", "0001_squashed_weblate_5"),
        ("configuration", "0002_alter_setting_category"),
    ]

    initial = True

    dependencies = [
        ("trans", "0001_squashed_weblate_5"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[(1, "User Interface"), (2, "Machine Translation")]
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.JSONField()),
            ],
            options={
                "unique_together": {("category", "name")},
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.RunPython(
            code=migrate_machinery,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
