# Generated by Django 3.2 on 2021-05-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="setting",
            options={"verbose_name": "Setting", "verbose_name_plural": "Settings"},
        ),
    ]
