# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.1.1 on 2024-09-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0001_squashed_weblate_5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="category",
            field=models.IntegerField(
                choices=[(1, "User Interface"), (2, "Machine Translation")]
            ),
        ),
    ]
