# Generated by Django 3.1.3 on 2021-02-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("scope", models.SmallIntegerField()),
                ("relation", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("value", models.IntegerField(db_index=True)),
            ],
            options={
                "index_together": {("date", "scope", "relation", "name")},
            },
        ),
    ]
