# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.4 on 2026-05-06 08:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("metrics", "0001_squashed_weblate_5"),
        ("metrics", "0002_new_public_projects_metric_data"),
    ]

    initial = True

    dependencies = [
        ("accounts", "0001_squashed_weblate_5"),
        ("trans", "0001_squashed_weblate_5"),
        ("weblate_auth", "0002_squashed_weblate_5"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=datetime.date.today)),
                ("scope", models.SmallIntegerField()),
                ("relation", models.IntegerField()),
                ("secondary", models.IntegerField(default=0)),
                ("changes", models.IntegerField()),
                ("data", models.JSONField(null=True)),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
                "unique_together": {("scope", "relation", "secondary", "date")},
            },
        ),
    ]
