# Generated by Django 3.1.7 on 2021-03-19 14:42


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
        ("accounts", "0013_auto_20210217_1653"),
    ]

    operations = []
