# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-07-24 06:27

from itertools import zip_longest

from django.db import migrations


def insert_public_project_data_in_latest_metric(apps, schema_editor) -> None:
    access_public = 0
    access_protected = 1
    new_metric_order = [
        "all",
        "all_words",
        "translated",
        "translated_words",
        "approved",
        "approved_words",
        "allchecks",
        "allchecks_words",
        "dismissed_checks",
        "dismissed_checks_words",
        "suggestions",
        "suggestions_words",
        "comments",
        "comments_words",
        "languages",
        "source_strings",
        "source_words",
        "changes",
        "memory",
        "users",
        "contributors",
        "projects",
        "screenshots",
        "components",
        "translations",
        "machinery:internal",
        "machinery:external",
        "public_projects",
    ]
    Metric = apps.get_model("metrics", "Metric")
    Project = apps.get_model("trans", "Project")
    public_projects_count = Project.objects.filter(
        access_control__in={access_public, access_protected}
    ).count()
    if latest_metric := Metric.objects.order_by(
        "date"
    ).last():  # tests will not have Metric objects yet
        dict_data = dict(
            zip_longest(new_metric_order, latest_metric.data or [], fillvalue=0)
        )
        dict_data["public_projects"] = public_projects_count
        latest_metric.data = [dict_data.pop(name, 0) for name in new_metric_order]
        latest_metric.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0001_squashed_weblate_5"),
    ]

    operations = [
        migrations.RunPython(
            insert_public_project_data_in_latest_metric,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
