# Generated by Django 3.1.7 on 2021-03-30 06:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0004_auto_20210330_0633"),
        ("trans", "0130_glossary_target"),
        ("weblate_auth", "0013_rename_sources_group"),
    ]

    operations = []
