# Generated by Django 3.1.7 on 2021-03-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0005_add_missing_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="secondary",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="metric",
            unique_together={("date", "scope", "relation", "secondary", "name")},
        ),
    ]
