# Generated by Django 3.2 on 2021-05-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0007_auto_20210402_1205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="value",
            field=models.IntegerField(),
        ),
    ]
