# Generated by Django 3.2 on 2021-05-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0008_alter_metric_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(max_length=25),
        ),
    ]
