# Generated by Django 3.2.6 on 2021-09-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0010_alter_metric_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="kind",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
