# Generated by Django 4.1 on 2022-11-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0013_auto_20210930_1841"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
