# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.1.3 on 2023-01-05 09:30

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0013_auto_20210930_1841"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricFuture",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=datetime.date.today)),
                ("scope", models.SmallIntegerField()),
                ("relation", models.IntegerField()),
                ("secondary", models.IntegerField(default=0)),
                ("changes", models.IntegerField()),
                ("data", models.JSONField(null=True)),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
                "unique_together": {("date", "scope", "relation", "secondary")},
            },
        ),
    ]
