# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.5 on 2023-09-12 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0017_rename_metricfuture_metric"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="metric",
            unique_together={("scope", "relation", "secondary", "date")},
        ),
    ]
