# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_squashed_0143_auto_20180609_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexUpdate',
        ),
    ]
