# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.5 on 2023-09-21 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0002_change_screenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="access_control",
            field=models.IntegerField(
                choices=[
                    (0, "Public"),
                    (1, "Protected"),
                    (100, "Private"),
                    (200, "Custom"),
                ],
                db_index=True,
                default=settings.DEFAULT_ACCESS_CONTROL,
                help_text="How to restrict access to this project is detailed in the documentation.",
                verbose_name="Access control",
            ),
        ),
    ]
