# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.4 on 2026-05-06 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import weblate.trans.fields
import weblate.trans.validators
import weblate.utils.render
import weblate.utils.validators


class Migration(migrations.Migration):
    replaces = [
        ("trans", "0003_alter_project_access_control"),
        ("trans", "0004_alter_change_action"),
        ("trans", "0005_alter_change_alert_alter_change_announcement_and_more"),
        ("trans", "0006_alter_change_action"),
        ("trans", "0007_alter_change_action"),
        ("trans", "0008_workflowsetting"),
        ("trans", "0009_alter_change_action"),
        ("trans", "0010_unit_trans_unit_pending"),
        ("trans", "0011_alter_component_suggestion_autoaccept_and_more"),
        ("trans", "0012_alter_announcement_notify"),
        ("trans", "0013_alter_category_options_category_category_slug_unique_and_more"),
        ("trans", "0014_alter_component_repoweb_alter_project_web"),
        ("trans", "0015_alter_component_language_code_style"),
        ("trans", "0016_alter_component_repoweb"),
        ("trans", "0017_announcement_severity_change_category_and_more"),
        ("trans", "0017_alter_change_action"),
        ("trans", "0018_merge_20240529_1359"),
        ("trans", "0019_label_description"),
        ("trans", "0019_alter_change_action"),
        ("trans", "0020_merge_0019_alter_change_action_0019_label_description"),
        ("trans", "0021_component_processed_revision"),
        ("trans", "0022_project_enforced_2fa"),
        ("trans", "0023_alter_label_description"),
        ("trans", "0024_component_key_filter"),
        ("trans", "0025_alter_announcement_notify"),
    ]

    dependencies = [
        ("lang", "0001_squashed_weblate_5"),
        ("lang", "0003_alter_plural_type"),
        ("screenshots", "0001_squashed_weblate_5"),
        ("trans", "0002_change_screenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="alert",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trans.alert",
            ),
        ),
        migrations.AlterField(
            model_name="change",
            name="announcement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trans.announcement",
            ),
        ),
        migrations.AlterField(
            model_name="change",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trans.comment",
            ),
        ),
        migrations.AlterField(
            model_name="change",
            name="screenshot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="screenshots.screenshot",
            ),
        ),
        migrations.AlterField(
            model_name="change",
            name="suggestion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trans.suggestion",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="access_control",
            field=models.IntegerField(
                choices=[
                    (0, "Public"),
                    (1, "Protected"),
                    (100, "Private"),
                    (200, "Custom"),
                ],
                db_index=True,
                default=settings.DEFAULT_ACCESS_CONTROL,
                help_text="How to restrict access to this project is detailed in the documentation.",
                verbose_name="Access control",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_review",
                    models.BooleanField(
                        default=settings.DEFAULT_TRANSLATION_REVIEW,
                        help_text="Requires dedicated reviewers to approve translations.",
                        verbose_name="Enable reviews",
                    ),
                ),
                (
                    "enable_suggestions",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to allow translation suggestions at all.",
                        verbose_name="Turn on suggestions",
                    ),
                ),
                (
                    "suggestion_voting",
                    models.BooleanField(
                        default=False,
                        help_text="Users can only vote for suggestions and can’t make direct translations.",
                        verbose_name="Suggestion voting",
                    ),
                ),
                (
                    "suggestion_autoaccept",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Automatically accept suggestions with this number of votes, use 0 to turn it off.",
                        validators=[weblate.trans.validators.validate_autoaccept],
                        verbose_name="Automatically accept suggestions",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lang.language"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trans.project",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                models.F("translation"),
                models.F("pending"),
                condition=models.Q(("pending", True)),
                name="trans_unit_pending",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="suggestion_autoaccept",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Automatically accept suggestions with this number of votes, use 0 to turn it off.",
                validators=[weblate.trans.validators.validate_autoaccept],
                verbose_name="Automatically accept suggestions",
            ),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("project", "category", "slug"),
                name="category_slug_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("project", "category", "name"),
                name="category_name_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                fields=("project", "category", "slug"),
                name="component_slug_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                fields=("project", "category", "name"),
                name="component_name_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="web",
            field=models.URLField(
                help_text="Main website of translated project.",
                validators=[
                    weblate.utils.validators.WeblateURLValidator(),
                    weblate.utils.validators.validate_project_web,
                ],
                verbose_name="Project website",
                blank=not settings.WEBSITE_REQUIRED,
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="language_code_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Default based on the file format"),
                    ("posix", "POSIX style using underscore as a separator"),
                    (
                        "posix_lowercase",
                        "POSIX style using underscore as a separator, lower cased",
                    ),
                    ("bcp", "BCP style using hyphen as a separator"),
                    (
                        "posix_long",
                        "POSIX style using underscore as a separator, including country code",
                    ),
                    (
                        "posix_long_lowercase",
                        "POSIX style using underscore as a separator, including country code, lower cased",
                    ),
                    (
                        "bcp_long",
                        "BCP style using hyphen as a separator, including country code",
                    ),
                    (
                        "bcp_legacy",
                        "BCP style using hyphen as a separator, legacy language codes",
                    ),
                    ("bcp_lower", "BCP style using hyphen as a separator, lower cased"),
                    ("android", "Android style"),
                    ("appstore", "Apple App Store metadata style"),
                    ("googleplay", "Google Play metadata style"),
                    ("linux", "Linux style"),
                    ("linux_lowercase", "Linux style, lower cased"),
                ],
                default="",
                help_text="Customize language code used to generate the filename for translations created by Weblate.",
                max_length=20,
                verbose_name="Language code style",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="repoweb",
            field=models.CharField(
                blank=True,
                help_text="Link to repository browser, use {{branch}} for branch, {{filename}} and {{line}} as filename and line placeholders. You might want to strip leading directory by using {{filename|parentdir}}.",
                max_length=200,
                validators=[weblate.utils.render.validate_repoweb],
                verbose_name="Repository browser",
            ),
        ),
        migrations.RenameField(
            model_name="announcement",
            old_name="category",
            new_name="severity",
        ),
        migrations.AlterField(
            model_name="announcement",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Info (light blue)"),
                    ("warning", "Warning (yellow)"),
                    ("danger", "Danger (red)"),
                    ("success", "Success (green)"),
                ],
                default="info",
                help_text="Severity defines color used for the message.",
                max_length=25,
                verbose_name="Severity",
            ),
        ),
        migrations.AddField(
            model_name="change",
            name="category",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.category",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="change",
            name="action",
            field=models.IntegerField(
                choices=[
                    (0, "Resource updated"),
                    (1, "Translation completed"),
                    (2, "Translation changed"),
                    (5, "Translation added"),
                    (3, "Comment added"),
                    (4, "Suggestion added"),
                    (6, "Automatically translated"),
                    (7, "Suggestion accepted"),
                    (8, "Translation reverted"),
                    (9, "Translation uploaded"),
                    (13, "Source string added"),
                    (14, "Component locked"),
                    (15, "Component unlocked"),
                    (17, "Changes committed"),
                    (18, "Changes pushed"),
                    (19, "Repository reset"),
                    (20, "Repository merged"),
                    (21, "Repository rebased"),
                    (22, "Repository merge failed"),
                    (23, "Repository rebase failed"),
                    (28, "Repository push failed"),
                    (24, "Parsing failed"),
                    (25, "Translation removed"),
                    (26, "Suggestion removed"),
                    (27, "Translation replaced"),
                    (29, "Suggestion removed during cleanup"),
                    (30, "Source string changed"),
                    (31, "String added"),
                    (32, "Bulk status changed"),
                    (33, "Visibility changed"),
                    (34, "User added"),
                    (35, "User removed"),
                    (36, "Translation approved"),
                    (37, "Marked for edit"),
                    (38, "Component removed"),
                    (39, "Project removed"),
                    (41, "Project renamed"),
                    (42, "Component renamed"),
                    (43, "Moved component"),
                    (45, "Contributor joined"),
                    (46, "Announcement posted"),
                    (47, "Alert triggered"),
                    (48, "Language added"),
                    (49, "Language requested"),
                    (50, "Project created"),
                    (51, "Component created"),
                    (52, "User invited"),
                    (53, "Repository notification received"),
                    (54, "Translation replaced file by upload"),
                    (55, "License changed"),
                    (56, "Contributor agreement changed"),
                    (57, "Screenshot added"),
                    (58, "Screenshot uploaded"),
                    (59, "String updated in the repository"),
                    (60, "Add-on installed"),
                    (61, "Add-on configuration changed"),
                    (62, "Add-on uninstalled"),
                    (63, "String removed"),
                    (64, "Comment removed"),
                    (65, "Comment resolved"),
                    (66, "Explanation updated"),
                    (67, "Category removed"),
                    (68, "Category renamed"),
                    (69, "Category moved"),
                    (70, "Saving string failed"),
                    (71, "String added in the repository"),
                    (72, "String updated in the upload"),
                    (73, "String added in the upload"),
                    (74, "Translation updated by source upload"),
                    (75, "Component translation completed"),
                ],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="processed_revision",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="enforced_2fa",
            field=models.BooleanField(
                default=False,
                help_text="Requires contributors to have two-factor authentication configured before being able to contribute.",
                verbose_name="Enforced two-factor authentication",
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="Label description"
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="key_filter",
            field=weblate.trans.fields.RegexField(
                blank=True,
                default="",
                help_text="Regular expression used to filter keys. This is only available for monolingual formats.",
                max_length=500,
                verbose_name="Key filter",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="notify",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Send notification to subscribed users.",
                verbose_name="Notify users",
            ),
        ),
    ]
