# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 11:21
from __future__ import unicode_literals

from django.db import migrations
import weblate.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0005_auto_20180914_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='userdetails',
            field=weblate.utils.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
