# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.8 on 2024-01-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0009_alter_change_action"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                models.F("translation"),
                models.F("pending"),
                condition=models.Q(("pending", True)),
                name="trans_unit_pending",
            ),
        ),
    ]
