# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.9 on 2024-01-30 14:57

from django.db import migrations, models

import weblate.trans.validators


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0010_unit_trans_unit_pending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="suggestion_autoaccept",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Automatically accept suggestions with this number of votes, use 0 to turn it off.",
                validators=[weblate.trans.validators.validate_autoaccept],
                verbose_name="Automatically accept suggestions",
            ),
        ),
        migrations.AlterField(
            model_name="workflowsetting",
            name="suggestion_autoaccept",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Automatically accept suggestions with this number of votes, use 0 to turn it off.",
                validators=[weblate.trans.validators.validate_autoaccept],
                verbose_name="Automatically accept suggestions",
            ),
        ),
    ]
