# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("trans", "0011_component_merge_message")]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
