# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.3 on 2024-03-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lang", "0003_alter_plural_type"),
        ("trans", "0012_alter_announcement_notify"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("project", "category", "slug"),
                name="category_slug_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("project", "category", "name"),
                name="category_name_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                fields=("project", "category", "slug"),
                name="component_slug_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                fields=("project", "category", "name"),
                name="component_name_unique",
                nulls_distinct=False,
            ),
        ),
    ]
