# Generated by Django 1.11.17 on 2019-01-31 13:20

from django.conf import settings
from django.db import migrations, models

import weblate.utils.render


class Migration(migrations.Migration):

    dependencies = [("trans", "0012_auto_20190129_1325")]

    operations = [
        migrations.AddField(
            model_name="component",
            name="addon_message",
            field=models.TextField(
                default=settings.DEFAULT_ADDON_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_addon],
                verbose_name="Commit message when addon makes a change",
            ),
        )
    ]
