# Copyright © Michal Karol <m.karol@neurosys.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.4 on 2024-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0014_alter_component_repoweb_alter_project_web"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="key_separator",
            field=models.CharField(
                default=".",
                help_text="Customize key separator for JSON based formats.",
                max_length=1,
                verbose_name="Key separator",
            ),
        ),
    ]
