# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-05-20 09:00

from django.db import migrations, models

import weblate.utils.render


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0015_alter_component_language_code_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="repoweb",
            field=models.CharField(
                blank=True,
                help_text="Link to repository browser, use {{branch}} for branch, {{filename}} and {{line}} as filename and line placeholders. You might want to strip leading directory by using {{filename|parentdir}}.",
                max_length=200,
                validators=[weblate.utils.render.validate_repoweb],
                verbose_name="Repository browser",
            ),
        ),
    ]
