# Generated by Django 1.11.17 on 2019-03-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("trans", "0016_fix_alert_occurrence")]

    operations = [
        migrations.AddField(
            model_name="component",
            name="language_code_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Default based on the file format"),
                    ("posix", "POSIX style using underscore as a separator"),
                    ("bcp", "BCP style using hyphen as a separator"),
                    ("android", "Android style"),
                ],
                default="",
                help_text="Customize language code used to generate the filename for translations created by Weblate.",
                max_length=10,
                verbose_name="Language code style",
            ),
        )
    ]
