# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later


# Generated by Django 5.0.6 on 2024-05-29 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0017_alter_change_action"),
        ("trans", "0017_announcement_severity_change_category_and_more"),
    ]

    operations = []
