# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-06-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0018_merge_20240529_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="description",
            field=models.CharField(
                default="", max_length=250, verbose_name="Label description"
            ),
        ),
    ]
