# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-06-25 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0019_alter_change_action"),
        ("trans", "0019_label_description"),
    ]

    operations = []
