# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-07-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0020_merge_0019_alter_change_action_0019_label_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="processed_revision",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
