# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-07-01 14:46

from django.db import migrations

import weblate.trans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0020_merge_0019_alter_change_action_0019_label_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="key_filter",
            field=weblate.trans.fields.RegexField(
                blank=True,
                default=None,
                help_text="Regular expression used to filter keys.",
                max_length=500,
                null=True,
                verbose_name="Key filter",
            ),
        ),
    ]
