# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.7 on 2024-07-18 11:29

from django.db import migrations

import weblate.trans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0021_component_processed_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="key_filter",
            field=weblate.trans.fields.RegexField(
                blank=True,
                default="",
                help_text="Regular expression used to filter keys.",
                max_length=500,
                verbose_name="Key filter",
            ),
        ),
    ]
