# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.7 on 2024-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0021_component_processed_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="enforced_2fa",
            field=models.BooleanField(
                default=False,
                help_text="Requires contributors to have two-factor authentication configured before being able to contribute.",
                verbose_name="Enforced two-factor authentication",
            ),
        ),
    ]
