# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.7 on 2024-08-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0022_project_enforced_2fa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="Label description"
            ),
        ),
    ]
