# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.8 on 2024-08-12 10:23

from django.db import migrations

import weblate.trans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0022_project_enforced_2fa"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="key_filter",
            field=weblate.trans.fields.RegexField(
                blank=True,
                default="",
                help_text="Regular expression used to filter keys. This is only available for monolingual formats.",
                max_length=500,
                verbose_name="Key filter",
            ),
        ),
    ]
