# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.8 on 2024-08-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0023_alter_label_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="to_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="component",
            name="to_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="to_delete",
            field=models.BooleanField(default=False),
        ),
    ]
