# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-08-23 12:52

from django.db import migrations, models

import weblate.utils.render


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0023_alter_label_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="add_message",
            field=models.TextField(
                blank=True,
                default="Added translation using Weblate ({{ language_name }})\n\n",
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_commit],
                verbose_name="Commit message when adding translation",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="addon_message",
            field=models.TextField(
                blank=True,
                default='Update translation files\n\nUpdated by "{{ addon_name }}" add-on in Weblate.\n\nTranslation: {{ project_name }}/{{ component_name }}\nTranslate-URL: {{ url }}',
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_addon],
                verbose_name="Commit message when add-on makes a change",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="commit_message",
            field=models.TextField(
                blank=True,
                default="Translated using Weblate ({{ language_name }})\n\nCurrently translated at {{ stats.translated_percent }}% ({{ stats.translated }} of {{ stats.all }} strings)\n\nTranslation: {{ project_name }}/{{ component_name }}\nTranslate-URL: {{ url }}",
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_commit],
                verbose_name="Commit message when translating",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="delete_message",
            field=models.TextField(
                blank=True,
                default="Deleted translation using Weblate ({{ language_name }})\n\n",
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_commit],
                verbose_name="Commit message when removing translation",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="merge_message",
            field=models.TextField(
                blank=True,
                default="Merge branch '{{ component_remote_branch }}' into Weblate.\n\n",
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_component],
                verbose_name="Commit message when merging translation",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="merge_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merge", "Merge"),
                    ("rebase", "Rebase"),
                    ("merge_noff", "Merge without fast-forward"),
                ],
                default="rebase",
                help_text="Define whether Weblate should merge the upstream repository or rebase changes onto it.",
                max_length=10,
                verbose_name="Merge style",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="pull_message",
            field=models.TextField(
                blank=True,
                default="Translations update from {{ site_title }}\n\nTranslations update from [{{ site_title }}]({{ site_url }}) for [{{ project_name }}/{{ component_name }}]({{url}}).\n\n{% if component_linked_childs %}\nIt also includes following components:\n{% for linked in component_linked_childs %}\n* [{{ linked.project_name }}/{{ linked.name }}]({{ linked.url }})\n{% endfor %}\n{% endif %}\n\nCurrent translation status:\n\n![Weblate translation status]({{widget_url}})\n",
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_addon],
                verbose_name="Merge request message",
            ),
        ),
    ]
