# Generated by Django 5.0.6 on 2025-01-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0025_alter_announcement_notify"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowsetting",
            name="string_filter",
            field=models.CharField(
                blank=True,
                help_text="Only include strings matching the filter.",
                verbose_name="Filter strings",
            ),
        ),
    ]
