# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.1.8 on 2025-04-11 13:31

from django.db import migrations, models

import weblate.trans.validators


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0033_component_secondary_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="check_flags",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional comma-separated flags to influence Weblate behavior.",
                validators=[weblate.trans.validators.validate_check_flags],
                verbose_name="Translation flags",
            ),
        ),
    ]
