# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.1 on 2025-05-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0035_alter_comment_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="is_glossary",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Glossaries are different from regular translations but help keep track of and share consistent terminology.",
                verbose_name="Use as a glossary",
            ),
        ),
    ]
