# Generated by Django 2.2.1 on 2019-08-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0035_remove_source_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='language_code_style',
            field=models.CharField(blank=True, choices=[('', 'Default based on the file format'), ('posix', 'POSIX style using underscore as a separator'), ('bcp', 'BCP style using hyphen as a separator'), ('android', 'Android style'), ('java', 'Java style')], default='', help_text='Customize language code used to generate the filename for translations created by Weblate.', max_length=10, verbose_name='Language code style'),
        ),
    ]
