# Generated by Django 2.2.5 on 2019-09-06 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("trans", "0036_auto_20190829_1309")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contribute_shared_tm",
            field=models.BooleanField(
                default=settings.DEFAULT_SHARED_TM,
                help_text="Contributes to the pool of shared translations between projects.",
                verbose_name="Contribute to shared translation memory",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="use_shared_tm",
            field=models.BooleanField(
                default=settings.DEFAULT_SHARED_TM,
                help_text="Uses the pool of shared translations between projects.",
                verbose_name="Use shared translation memory",
            ),
        ),
    ]
