# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.1 on 2025-06-01 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0037_component_contribute_project_tm"),
        ("trans", "0037_pendingunitchange"),
    ]

    operations = []
