# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 5.2.1 on 2025-06-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0038_merge_20250601_1924"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingunitchange",
            name="details",
        ),
        migrations.AddField(
            model_name="pendingunitchange",
            name="add_unit",
            field=models.BooleanField(default=False),
        ),
    ]
