# Generated by Django 2.2.5 on 2019-09-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("trans", "0038_contribute_tm")]

    operations = [migrations.RemoveField(model_name="component", name="save_history")]
