# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 5.2.1 on 2025-06-13 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0040_auto_20250613_1813"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="unit",
            name="trans_unit_pending",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="pending",
        ),
    ]
