# Generated by Django 2.2.5 on 2019-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("trans", "0040_auto_20190930_1528")]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="original_state",
            field=models.IntegerField(
                choices=[
                    (0, "Empty"),
                    (10, "Needs editing"),
                    (20, "Translated"),
                    (30, "Approved"),
                    (100, "Read only"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Empty"),
                    (10, "Needs editing"),
                    (20, "Translated"),
                    (30, "Approved"),
                    (100, "Read only"),
                ],
                db_index=True,
                default=0,
            ),
        ),
    ]
