# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 5.2.3 on 2025-07-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0041_remove_unit_trans_unit_pending_remove_unit_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="commit_policy",
            field=models.IntegerField(
                choices=[
                    (0, "Commit all translations regardless of quality"),
                    (20, "Skip translations marked as needing editing"),
                    (30, "Only include approved translations"),
                ],
                default=0,
                help_text="Select which translations should be included when committing changes. More restrictive options will skip translations with potential quality issues.",
                verbose_name="Translation quality filter",
            ),
        ),
    ]
