# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.3 on 2025-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0041_remove_unit_trans_unit_pending_remove_unit_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="file_format_params",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="File format parameters"
            ),
        ),
    ]
