# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.3 on 2025-06-29 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0041_remove_unit_trans_unit_pending_remove_unit_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="autoclean_tm",
            field=models.BooleanField(
                default=settings.DEFAULT_AUTOCLEAN_TM,
                help_text="Automatically removes outdated and obsolete entries from translation memory.",
                verbose_name="Autoclean translation memory",
            ),
        ),
    ]
