# Generated by Django 2.2.5 on 2019-10-29 11:44

from django.db import migrations
from django.db.models import F


def migrate_original_state(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    apps.get_model("trans", "Unit").objects.using(db_alias).update(
        original_state=F("state")
    )


class Migration(migrations.Migration):

    dependencies = [("trans", "0041_auto_20191029_1144")]

    operations = [
        migrations.RunPython(
            migrate_original_state, migrations.RunPython.noop, elidable=True
        )
    ]
