# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 5.2.3 on 2025-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0042_project_commit_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingunitchange",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Empty"),
                    (10, "Needs editing"),
                    (20, "Translated"),
                    (30, "Approved"),
                    (100, "Read-only"),
                ],
                db_index=True,
                default=0,
            ),
        ),
    ]
