# Generated by Django 2.2.5 on 2019-11-03 09:13

from django.db import migrations, models

import weblate.trans.validators


class Migration(migrations.Migration):

    dependencies = [("trans", "0043_auto_20191030_1244")]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="check_flags",
            field=models.TextField(
                blank=True,
                default="",
                validators=[weblate.trans.validators.validate_check_flags],
                verbose_name="Translation flags",
            ),
        )
    ]
