# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.4 on 2025-07-21 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0042_project_autoclean_tm"),
        ("trans", "0043_alter_pendingunitchange_state"),
    ]

    operations = []
