# Generated by Django 2.2.5 on 2019-11-03 09:29

import django.utils.timezone
from django.db import migrations, models

import weblate.trans.validators


class Migration(migrations.Migration):

    dependencies = [("trans", "0044_translation_check_flags")]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="extra_context",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="unit",
            name="extra_flags",
            field=models.TextField(
                blank=True,
                default="",
                validators=[weblate.trans.validators.validate_check_flags],
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
