# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 5.2.4 on 2025-08-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0046_component_file_format_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingunitchange",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
