# Generated by Django 2.2.5 on 2019-11-08 13:49

from django.db import migrations, models

import weblate.trans.validators


class Migration(migrations.Migration):

    dependencies = [("trans", "0047_delete_source")]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="extra_context",
            field=models.TextField(
                blank=True, default="", verbose_name="Additional context"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="extra_flags",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "Additional comma-separated flags to influence quality checks. "
                    "Possible values can be found in the documentation."
                ),
                validators=[weblate.trans.validators.validate_check_flags],
                verbose_name="Translation flags",
            ),
        ),
    ]
