# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.5 on 2025-09-05 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lang", "0004_alter_language_direction"),
        ("screenshots", "0001_squashed_weblate_5"),
        ("trans", "0047_pendingunitchange_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="change",
            index=models.Index(
                condition=models.Q(("category__isnull", False)),
                fields=["category", "-timestamp", "action"],
                name="trans_change_category_idx",
            ),
        ),
    ]
