# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_auto_20150630_1208'),
        ('trans', '0048_auto_20151120_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupACL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(to='auth.Group')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lang.Language')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trans.Project')),
                ('subproject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trans.SubProject')),
            ],
            options={
                'verbose_name': 'Group-based ACL Configuration',
                'verbose_name_plural': 'Group-based ACL Configurations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupacl',
            unique_together=set([('project', 'subproject', 'language')]),
        ),
    ]
