# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.5 on 2025-08-24 15:12

from django.db import migrations, models

import weblate.trans.validators


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0049_component_hide_glossary_matches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="file_format_params",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[weblate.trans.validators.validate_file_format_parameters],
                verbose_name="File format parameters",
            ),
        ),
    ]
