# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.7 on 2025-11-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0050_alter_component_file_format_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingunitchange",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Empty"),
                    (10, "Needs editing"),
                    (11, "Needs rewriting"),
                    (12, "Needs checking"),
                    (20, "Translated"),
                    (30, "Approved"),
                    (100, "Read-only"),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="original_state",
            field=models.IntegerField(
                choices=[
                    (0, "Empty"),
                    (10, "Needs editing"),
                    (11, "Needs rewriting"),
                    (12, "Needs checking"),
                    (20, "Translated"),
                    (30, "Approved"),
                    (100, "Read-only"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Empty"),
                    (10, "Needs editing"),
                    (11, "Needs rewriting"),
                    (12, "Needs checking"),
                    (20, "Translated"),
                    (30, "Approved"),
                    (100, "Read-only"),
                ],
                default=0,
            ),
        ),
    ]
