# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0050_auto_20151222_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whiteboardmessage',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lang.Language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='whiteboardmessage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trans.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='whiteboardmessage',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trans.SubProject', verbose_name='Component'),
        ),
    ]
