# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.7 on 2025-11-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0051_alter_pendingunitchange_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="automatically_translated",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether this string was translated automatically.",
                verbose_name="Automatically translated",
            ),
        ),
    ]
