# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.8 on 2025-11-26 13:37

from django.db import migrations

from weblate.formats.ttkit import LaravelPhpFormat


def migrate_laravel(apps, schema_editor) -> None:
    Unit = apps.get_model("trans", "Unit")

    updates = []

    for unit in (
        Unit.objects.filter(translation__component__file_format="laravel")
        .prefetch_related("translation", "translation__component")
        .iterator(chunk_size=1000)
    ):
        context = unit.context
        # Strip return[]-> or return-> prefix for Laravel files
        if context.startswith("return[]->"):
            context = context[10:]  # Remove "return[]->"
        elif context.startswith("return->"):
            context = context[8:]  # Remove "return->"

        # Strip surrounding quotes if present
        if len(context) >= 2 and context[0] == context[-1] and context[0] in {"'", '"'}:
            unit.context = context[1:-1]
        else:
            unit.context = context

        unit.id_hash = LaravelPhpFormat.unit_class.calculate_id_hash(
            bool(unit.translation.component.template), unit.source, unit.context
        )
        updates.append(unit)
        if len(updates) > 1000:
            Unit.objects.bulk_update(updates, ["id_hash", "context"])
            updates.clear()

    if updates:
        Unit.objects.bulk_update(updates, ["id_hash", "context"])


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0051_alter_pendingunitchange_state_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_laravel, migrations.RunPython.noop, elidable=True),
    ]
