# Generated by Django 2.2.5 on 2019-12-12 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("trans", "0053_unitdata")]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_set",
                to="trans.Unit",
            ),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trans.Unit"
            ),
        ),
        migrations.AlterIndexTogether(name="comment", index_together=set()),
        migrations.AlterIndexTogether(name="suggestion", index_together=set()),
        migrations.RemoveField(model_name="comment", name="content_hash"),
        migrations.RemoveField(model_name="comment", name="language"),
        migrations.RemoveField(model_name="comment", name="project"),
        migrations.RemoveField(model_name="suggestion", name="content_hash"),
        migrations.RemoveField(model_name="suggestion", name="project"),
    ]
