# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.8 on 2025-11-29 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0052_migrate_laravel"),
        ("trans", "0053_migrate_automatically_translated_label_to_unit_field"),
    ]

    operations = []
