# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0054_auto_20160202_1219'),
    ]

    operations = [
    ]
