# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 12:21
from __future__ import unicode_literals

from django.db import migrations


def fill_in_unitid(apps, schema_editor):
    IndexUpdate = apps.get_model('trans', 'IndexUpdate')

    for update in IndexUpdate.objects.all():
        update.unitid = update.unit_id
        update.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0054_auto_20160202_1219'),
    ]

    operations = [
        migrations.RunPython(
            fill_in_unitid,
        ),
    ]
