# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.8 on 2025-12-01 07:20

from django.db import migrations, models

import weblate.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0056_alter_change_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="push",
            field=models.CharField(
                blank=True,
                help_text="URL of a push repository, pushing is turned off if empty.",
                max_length=300,
                validators=[weblate.utils.validators.validate_repo_url],
                verbose_name="Repository push URL",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="repo",
            field=models.CharField(
                help_text="URL of a repository, use weblate://project/component to share it with other component.",
                max_length=300,
                validators=[weblate.utils.validators.validate_repo_url],
                verbose_name="Source code repository",
            ),
        ),
    ]
