# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0056_auto_20160202_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexupdate',
            name='language_code',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
