# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.8 on 2025-12-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0057_alter_component_push_alter_component_repo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="push_branch",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Branch for pushing changes. Leave empty to use repository branch when pushing directly to the repository. When using pull/merge requests, specify a branch name different from the repository branch.",
                max_length=200,
                verbose_name="Push branch",
            ),
        ),
    ]
