# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0058_componentlist'),
    ]

    operations = [
    ]
