# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.9 on 2025-12-17 07:24

from django.db import migrations

import weblate.trans.fields
import weblate.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0059_alter_change_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="language_regex",
            field=weblate.trans.fields.RegexField(
                default="^[^.]+$",
                help_text="Regular expression used to filter translation files when scanning for file mask.",
                max_length=500,
                validators=[weblate.utils.validators.validate_re_nonempty],
                verbose_name="Language filter",
            ),
        ),
    ]
