# Generated by Django 2.2.9 on 2020-02-10 11:30

from django.db import migrations

import weblate.utils.fields


class Migration(migrations.Migration):

    dependencies = [("trans", "0059_auto_20200206_0937")]

    operations = [
        migrations.AddField(
            model_name="component",
            name="enforced_checks",
            field=weblate.utils.fields.JSONField(
                blank=True,
                default=[],
                help_text="List of checks which can not be ignored.",
                verbose_name="Enforced checks",
            ),
        )
    ]
