# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.9 on 2025-12-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0060_pendingunitchange_automatically_translated"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingunitchange",
            name="automatically_translated",
            field=models.BooleanField(default=False),
        ),
    ]
