# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0060_auto_20160310_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='track_important_languages',
            field=models.BooleanField(default=False, help_text='Show this project in the release manager dashboard', verbose_name='Track important languages'),
        ),
    ]
