# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.7 on 2025-11-05 14:56

from django.db import migrations

FILE_FORMAT_MAPPING: dict[str, tuple[str, dict[str, str]]] = {
    "strings": (
        "strings",
        {"strings_encoding": "utf-16"},
    ),
    "strings-utf8": (
        "strings",
        {"strings_encoding": "utf-8"},
    ),
    "properties": (
        "properties",
        {"properties_encoding": "iso-8859-1"},
    ),
    "properties-utf8": (
        "properties",
        {"properties_encoding": "utf-8"},
    ),
    "properties-utf16": (
        "properties",
        {"properties_encoding": "utf-16"},
    ),
    "csv": (
        "csv",
        {"csv_encoding": "auto"},
    ),
    "csv-utf-8": (
        "csv",
        {"csv_encoding": "utf-8"},
    ),
    "csv-simple": (
        "csv-simple",
        {"csv_simple_encoding": "auto"},
    ),
    "csv-simple-iso": (
        "csv-simple",
        {"csv_simple_encoding": "iso-8859-1"},
    ),
    "csv-simple-utf-8": (
        "csv-simple",
        {"csv_simple_encoding": "utf-8"},
    ),
    "gwt-iso": (
        "gwt",
        {"gwt_encoding": "iso-8859-1"},
    ),
    "gwt": (
        "gwt",
        {"gwt_encoding": "utf-8"},
    ),
}


def merge_file_format_with_encoding(apps, schema_editor):
    """Migrate file format with encoding."""
    Component = apps.get_model("trans", "Component")
    to_update = []
    for component in Component.objects.filter(
        file_format__in=FILE_FORMAT_MAPPING.keys()
    ):
        new_file_format, file_format_params = FILE_FORMAT_MAPPING[component.file_format]
        component.file_format = new_file_format
        component.file_format_params.update(file_format_params)
        to_update.append(component)

    Component.objects.bulk_update(to_update, ["file_format", "file_format_params"])


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0061_pendingunitchange_automatically_translated"),
    ]

    operations = [
        migrations.RunPython(
            merge_file_format_with_encoding, migrations.RunPython.noop, elidable=True
        ),
    ]
