# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0061_auto_20160404_1841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set([('translation', 'checksum')]),
        ),
    ]
