# -*- coding: utf-8 -*-
# Generated by Django 3.0.4 on 2020-03-10 14:47

from django.db import migrations


def create_index(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            "CREATE INDEX unit_source_fulltext ON trans_unit "
            "USING GIN (to_tsvector('english', source))"
        )
    elif vendor == "mysql":
        schema_editor.execute(
            "CREATE FULLTEXT INDEX unit_source_fulltext ON trans_unit(source)"
        )
    else:
        raise Exception("Unsupported database: {}".format(vendor))


def drop_index(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute("DROP INDEX unit_source_fulltext")
    elif vendor == "mysql":
        schema_editor.execute("ALTER TABLE trans_unit DROP INDEX unit_source_fulltext")
    else:
        raise Exception("Unsupported database: {}".format(vendor))


class Migration(migrations.Migration):

    dependencies = [("trans", "0063_auto_20200305_2202")]

    # This can't be atomic on MySQL
    operations = [
        migrations.RunPython(create_index, drop_index, elidable=False, atomic=False)
    ]
