# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.10 on 2026-02-03 10:13

from django.db import migrations, models

import weblate.utils.validators
from weblate.vcs.models import VCS_REGISTRY


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0063_file_format_encoding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="push",
            field=models.CharField(
                blank=True,
                help_text="URL of a push repository, pushing is turned off if empty. When using pull/merge requests, keep empty to fork the repository.",
                max_length=300,
                validators=[weblate.utils.validators.validate_repo_url],
                verbose_name="Repository push URL",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="vcs",
            field=models.CharField(
                choices=VCS_REGISTRY.get_choices(),
                default="git",
                help_text="Version control system to use to access your repository containing translations. You can also choose additional integration with third party providers to submit pull/merge requests.",
                max_length=20,
                verbose_name="Version control system",
            ),
        ),
    ]
