# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.11 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0065_alter_change_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="key",
            field=models.TextField(),
        ),
    ]
