# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.3 on 2026-04-01 15:39

from django.conf import settings
from django.db import migrations, models

import weblate.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0068_unit_source_tm_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="web",
            field=models.URLField(
                help_text="Main website of translated project.",
                validators=[weblate.utils.validators.WeblateURLValidator()],
                verbose_name="Project website",
                blank=not settings.WEBSITE_REQUIRED,
            ),
        ),
    ]
