# Generated by Django 6.0.3 on 2026-04-22 21:02

import weblate.utils.render
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0068_unit_source_tm_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='repoweb_translations',
            field=models.CharField(blank=True, help_text='Link to repository browser for translation files, use {{branch}} for branch, {{filename}} and {{line}} as filename and line placeholders. If left empty, the Repository browser above will be used. You might want to strip leading directory by using {{filename|parentdir}}.', max_length=200, validators=[weblate.utils.render.validate_repoweb], verbose_name='Repository browser for translations'),
        ),
    ]
