# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-02 15:42
from __future__ import unicode_literals

from django.db import migrations
import weblate.screenshots.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0068_auto_20161025_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='screenshot',
            field=weblate.screenshots.fields.ScreenshotField(blank=True, help_text='Upload JPEG or PNG images up to 2000x2000 pixels.', upload_to='screenshots/', verbose_name='Screenshot showing usage of this string'),
        ),
    ]
