# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.7 on 2026-04-01 00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.state import StateApps


def remove_xwiki_page_properties_encoding(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Remove legacy encoding params no longer applicable to XWiki page properties."""
    Component = apps.get_model("trans", "Component")
    to_update = []

    for component in Component.objects.filter(file_format="xwiki-page-properties"):
        if "properties_encoding" not in component.file_format_params:
            continue
        component.file_format_params.pop("properties_encoding", None)
        to_update.append(component)

    if to_update:
        Component.objects.bulk_update(to_update, ["file_format_params"])


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0069_alter_project_web"),
    ]

    operations = [
        migrations.RunPython(
            remove_xwiki_page_properties_encoding,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
