# Generated by Django 3.0.4 on 2020-03-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0069_auto_20200324_1121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterIndexTogether(
            name="change", index_together={("timestamp", "translation")},
        ),
    ]
