# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.7 on 2026-04-01 00:00

from django.db import migrations


def remove_xwiki_page_properties_encoding(apps, schema_editor):
    """Remove legacy encoding params no longer applicable to XWiki page properties."""
    Component = apps.get_model("trans", "Component")
    to_update = []

    for component in Component.objects.filter(file_format="xwiki-page-properties"):
        if "properties_encoding" not in component.file_format_params:
            continue
        component.file_format_params.pop("properties_encoding", None)
        to_update.append(component)

    if to_update:
        Component.objects.bulk_update(to_update, ["file_format_params"])


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0069_alter_project_web"),
    ]

    operations = [
        migrations.RunPython(
            remove_xwiki_page_properties_encoding,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
