# Generated by Django 3.0.4 on 2020-03-31 12:09

from django.db import migrations, models

import weblate.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0070_auto_20200327_1225"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="intermediate",
            field=models.CharField(
                blank=True,
                help_text="Filename of intermediate translation file. In most cases this is a translation file provided by developers and is used when creating actual source strings.",
                max_length=400,
                validators=[weblate.utils.validators.validate_filename],
                verbose_name="Intermediate language file",
            ),
        ),
    ]
