# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0 on 2026-04-13 00:00

from django.db import migrations
from django.db.models import F, Q


def add_translation_readonly_flag(check_flags: str) -> str:
    """Add the auto-managed translation read-only flag."""
    if "read-only" in check_flags:
        return check_flags
    if not check_flags:
        return "read-only"
    return f"read-only, {check_flags}"


def normalize_translation_readonly_flags(apps, schema_editor):
    """Add missing auto-managed translation read-only flags."""
    Translation = apps.get_model("trans", "Translation")
    to_update = []

    translations = (
        Translation.objects.select_related("component")
        .filter(
            Q(
                component__template="",
                language_id=F("component__source_language_id"),
            )
            | Q(
                ~Q(component__template=""),
                component__edit_template=False,
                filename=F("component__template"),
            )
        )
        .exclude(check_flags__contains="read-only")
    )

    for translation in translations.iterator():
        check_flags = add_translation_readonly_flag(
            translation.check_flags,
        )
        if translation.check_flags == check_flags:
            continue

        translation.check_flags = check_flags
        to_update.append(translation)

        if len(to_update) >= 500:
            Translation.objects.bulk_update(to_update, ["check_flags"])
            to_update.clear()

    if to_update:
        Translation.objects.bulk_update(to_update, ["check_flags"])


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0070_remove_xwiki_page_properties_encoding"),
    ]

    operations = [
        migrations.RunPython(
            normalize_translation_readonly_flags,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
