# Generated by Django 3.0.5 on 2020-04-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("trans", "0071_component_intermediate")]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="revision",
            field=models.CharField(blank=True, default="", max_length=200),
        )
    ]
