# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-09 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0072_auto_20170209_1234'),
    ]

    operations = [
    ]
