# Generated by Django 3.0.5 on 2020-04-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0072_auto_20200403_1311"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="enable_review",
            new_name="translation_review",
        ),
        migrations.AddField(
            model_name="project",
            name="source_review",
            field=models.BooleanField(
                default=False,
                help_text="Requires dedicated reviewers to approve source strings.",
                verbose_name="Enable source reviews",
            ),
        ),
    ]
