# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.3 on 2026-04-05 12:34

from django.db import migrations


def migrate_gettext_header_settings(apps, schema_editor):
    Component = apps.get_model("trans", "Component")
    to_update = []
    for component in (
        Component.objects.filter(file_format__in=("po", "po-mono"))
        .select_related("project")
        .only("file_format_params", "project")
    ):
        file_format_params = component.file_format_params or {}
        file_format_params["po_set_language_team"] = component.project.set_language_team
        file_format_params["po_set_last_translator"] = True
        file_format_params["po_set_x_generator"] = True
        file_format_params["po_report_msgid_bugs_to"] = True
        to_update.append(component)
    Component.objects.bulk_update(to_update, ["file_format_params"])


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0072_alter_change_action"),
    ]

    operations = [
        migrations.RunPython(
            migrate_gettext_header_settings, migrations.RunPython.noop, elidable=True
        ),
    ]
