# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.4 on 2026-04-24 18:09

from django.db import migrations
from django.db.models import Q


def remove_dos_eol_flag(flags: str) -> str:
    parts = [item.strip() for item in flags.split(",")]
    return ",".join(item for item in parts if item and item != "dos-eol")


def migrate_dos_eol_flags_to_file_format_params(apps, schema_editor):
    Project = apps.get_model("trans", "Project")
    Component = apps.get_model("trans", "Component")
    Translation = apps.get_model("trans", "Translation")
    Unit = apps.get_model("trans", "Unit")
    units_to_update = []
    components_to_update = []
    projects_to_update = []
    translations_to_update = []
    for component in Component.objects.filter(
        Q(check_flags__icontains="dos-eol")
        | Q(project__check_flags__icontains="dos-eol")
    ):
        file_format_params = component.file_format_params or {}
        file_format_params["dos_eol"] = True
        component.file_format_params = file_format_params

        # remove stale flag from components
        if "dos-eol" in component.check_flags:
            component.check_flags = remove_dos_eol_flag(component.check_flags)

        components_to_update.append(component)

    # remove stale flag from units
    for unit in Unit.objects.filter(extra_flags__icontains="dos-eol"):
        unit.extra_flags = remove_dos_eol_flag(unit.extra_flags)
        units_to_update.append(unit)

    # remove stale flag from translations
    for translation in Translation.objects.filter(check_flags__icontains="dos-eol"):
        translation.check_flags = remove_dos_eol_flag(translation.check_flags)
        translations_to_update.append(translation)

    # remove stale flag from projects
    for project in Project.objects.filter(Q(check_flags__icontains="dos-eol")):
        project.check_flags = remove_dos_eol_flag(project.check_flags)
        projects_to_update.append(project)

    Unit.objects.bulk_update(units_to_update, ["extra_flags"])
    Translation.objects.bulk_update(translations_to_update, ["check_flags"])
    Component.objects.bulk_update(
        components_to_update, ["file_format_params", "check_flags"]
    )
    Project.objects.bulk_update(projects_to_update, ["check_flags"])


def reverse_migration(apps, schema_editor):
    # the flag is only restored at component level
    Component = apps.get_model("trans", "Component")
    components_to_update = []
    for component in Component.objects.filter(
        file_format_params__dos_eol__isnull=False
    ):
        if component.file_format_params["dos_eol"]:
            existing = [
                item for item in component.check_flags.split(",") if item.strip()
            ]
            component.check_flags = ",".join([*existing, "dos-eol"])

        component.file_format_params.pop("dos_eol", None)
        components_to_update.append(component)

    Component.objects.bulk_update(
        components_to_update, ["file_format_params", "check_flags"]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0073_alter_change_action"),
    ]

    operations = [
        migrations.RunPython(
            migrate_dos_eol_flags_to_file_format_params, reverse_code=reverse_migration
        ),
    ]
