# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-09 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0004_auto_20161222_1459'),
        ('trans', '0073_auto_20170209_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='contentsum',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='contentsum',
        ),
        migrations.AlterUniqueTogether(
            name='check',
            unique_together=set([('content_hash', 'project', 'language', 'check')]),
        ),
        migrations.RemoveField(
            model_name='check',
            name='contentsum',
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('id_hash', 'subproject')]),
        ),
        migrations.RemoveField(
            model_name='source',
            name='checksum',
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set([('translation', 'id_hash')]),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='contentsum',
        ),
    ]
