# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.4 on 2026-04-13 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0074_migrate_gettext_header_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="set_language_team",
        ),
    ]
