# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0074_auto_20170209_1412'),
        ('screenshots', '0002_auto_20170215_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'permissions': (('edit_priority', 'Can edit priority'), ('edit_flags', 'Can edit check flags'))},
        ),
        migrations.RemoveField(
            model_name='source',
            name='screenshot',
        ),
    ]
