# Generated by Django 3.0.5 on 2020-05-07 10:59

from django.db import migrations

import weblate.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0075_auto_20200501_1428"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="userdetails",
            field=weblate.utils.fields.JSONField(default={}),
        ),
    ]
