# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import weblate.trans.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0075_auto_20170215_1750'),
        ('permissions', '0002_auto_20170317_1123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupacl',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='groupacl',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='groupacl',
            name='language',
        ),
        migrations.RemoveField(
            model_name='groupacl',
            name='project',
        ),
        migrations.RemoveField(
            model_name='groupacl',
            name='subproject',
        ),
        migrations.AlterField(
            model_name='check',
            name='check',
            field=models.CharField(choices=[('end_space', 'Trailing space'), (b'inconsistent', 'Inconsistent'), ('begin_newline', 'Starting newline'), ('max-length', 'Maximum length of translation'), ('zero-width-space', 'Zero-width space'), ('escaped_newline', 'Mismatched \\n'), ('same', 'Unchanged translation'), ('end_question', 'Trailing question'), (b'angularjs_format', 'AngularJS interpolation string'), (b'python_brace_format', 'Python brace format'), ('end_newline', 'Trailing newline'), (b'c_format', 'C format'), ('end_exclamation', 'Trailing exclamation'), ('end_ellipsis', 'Trailing ellipsis'), ('end_colon', 'Trailing colon'), ('xml-tags', 'XML tags mismatch'), (b'python_format', 'Python format'), (b'plurals', 'Missing plurals'), (b'javascript_format', 'Javascript format'), ('begin_space', 'Starting spaces'), ('bbcode', 'Mismatched BBcode'), (b'php_format', 'PHP format'), ('xml-invalid', 'Invalid XML markup'), (b'same-plurals', 'Same plurals'), (b'translated', 'Has been translated'), ('end_stop', 'Trailing stop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='commit_message',
            field=models.TextField(default='Translated using Weblate (%(language_name)s)\n\nCurrently translated at %(translated_percent)s%% (%(translated)s of %(total)s strings)\n\nTranslation: %(project)s/%(component)s\nTranslate-URL: %(url)s', help_text='You can use format strings for various information, please check documentation for more details.', validators=[weblate.trans.validators.validate_commit_message], verbose_name='Commit message when translating'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='file_format',
            field=models.CharField(choices=[('aresource', 'Android String Resource'), ('auto', 'Automatic detection'), ('csv', 'CSV file'), ('csv-simple', 'Simple CSV file'), ('csv-simple-iso', 'Simple CSV file (ISO-8859-1)'), ('joomla', 'Joomla Language File'), ('json', 'JSON file'), ('php', 'PHP strings'), ('po', 'Gettext PO file'), ('po-mono', 'Gettext PO file (monolingual)'), ('poxliff', 'XLIFF Translation File with PO extensions'), ('properties', 'Java Properties (ISO-8859-1)'), ('properties-utf16', 'Java Properties (UTF-16)'), ('properties-utf8', 'Java Properties (UTF-8)'), ('resx', '.Net resource file'), ('ruby-yaml', 'Ruby YAML file'), ('strings', 'OS X Strings'), ('strings-utf8', 'OS X Strings (UTF-8)'), ('ts', 'Qt Linguist Translation File'), ('xliff', 'XLIFF Translation File'), ('yaml', 'YAML file')], default='auto', help_text='Automatic detection might fail for some formats and is slightly slower.', max_length=50, verbose_name='File format'),
        ),
        migrations.DeleteModel(
            name='GroupACL',
        ),
    ]
