# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.4 on 2026-05-06 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0075_setting_change_history"),
        ("trans", "0076_remove_project_set_language_team"),
    ]

    operations = []
