# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.5 on 2026-05-20

from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.state import StateApps


def update_alert_severities(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    alert = apps.get_model("trans", "Alert")
    alert.objects.filter(
        name__in={
            "MissingScreenshots",
            "MissingTranslationFlags",
            "RecommendedCleanupAddon",
            "RecommendedConfigureAddon",
            "RecommendedDjangoAddon",
            "RecommendedGenerateMoAddon",
            "RecommendedLanguageConsistencyAddon",
            "RecommendedLinguasAddon",
            "RecommendedMesonAddon",
            "RecommendedSphinxAddon",
            "RecommendedXgettextAddon",
        }
    ).update(severity=10)
    alert.objects.filter(
        name__in={
            "MissingPushURL",
            "MissingRepositoryHook",
            "MissingSafeHTMLFlag",
            "MissingTranslationInstructions",
            "UnusedScreenshot",
        }
    ).update(severity=50)


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0078_user_access_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="severity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "Information"),
                    (50, "Warning"),
                    (100, "Error"),
                ],
                db_index=True,
                default=100,
            ),
        ),
        migrations.RunPython(update_alert_severities, migrations.RunPython.noop),
    ]
