# Generated by Django 3.0.6 on 2020-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0079_auto_20200519_1436"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="extra_context",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional explanation to clarify meaning or usage of the string.",
                verbose_name="Explanation",
            ),
        ),
    ]
