# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django on 2026-05-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0079_alert_severity"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this project belongs to. Standalone projects do not need one.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="workspaces.workspace",
                verbose_name="Workspace",
            ),
        ),
    ]
