# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0081_auto_20170323_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='old',
            field=models.TextField(blank=True, default=''),
        ),
    ]
