# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.5 on 2026-05-27 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import weblate.utils.render
from weblate.utils.licenses import get_license_choices


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0082_project_move_change"),
        ("workspaces", "0002_workspace_add_message_workspace_addon_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributoragreement",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="component",
            name="inherit_add_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the commit message when adding translation configured in the project.",
                verbose_name="Inherit commit message when adding translation",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="inherit_addon_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the commit message when add-on makes a change configured in the project.",
                verbose_name="Inherit commit message when add-on makes a change",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="inherit_agreement",
            field=models.BooleanField(
                default=False,
                help_text="Use the contributor license agreement configured in the project.",
                verbose_name="Inherit contributor license agreement",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="inherit_commit_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the commit message when translating configured in the project.",
                verbose_name="Inherit commit message when translating",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="inherit_delete_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the commit message when removing translation configured in the project.",
                verbose_name="Inherit commit message when removing translation",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="inherit_language_code_style",
            field=models.BooleanField(
                default=False,
                help_text="Use the language code style configured in the project.",
                verbose_name="Inherit language code style",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="inherit_license",
            field=models.BooleanField(
                default=False,
                help_text="Use the translation license configured in the project.",
                verbose_name="Inherit translation license",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="inherit_merge_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the commit message when merging translation configured in the project.",
                verbose_name="Inherit commit message when merging translation",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="inherit_new_lang",
            field=models.BooleanField(
                default=False,
                help_text="Use the adding new translations setting configured in the project.",
                verbose_name="Inherit adding new translations",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="inherit_pull_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the merge request message configured in the project.",
                verbose_name="Inherit merge request message",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="inherit_secondary_language",
            field=models.BooleanField(
                default=False,
                help_text="Use the secondary language configured in the project.",
                verbose_name="Inherit secondary language",
            ),
        ),
        migrations.AddField(
            model_name="contributoragreement",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.project",
            ),
        ),
        migrations.AddField(
            model_name="contributoragreement",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="add_message",
            field=models.TextField(
                default=settings.DEFAULT_ADD_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_commit],
                verbose_name="Commit message when adding translation",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="addon_message",
            field=models.TextField(
                default=settings.DEFAULT_ADDON_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_addon],
                verbose_name="Commit message when add-on makes a change",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="agreement",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contributor license agreement which needs to be approved before a user can translate components in this project.",
                verbose_name="Contributor license agreement",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="commit_message",
            field=models.TextField(
                default=settings.DEFAULT_COMMIT_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_commit],
                verbose_name="Commit message when translating",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="delete_message",
            field=models.TextField(
                default=settings.DEFAULT_DELETE_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_commit],
                verbose_name="Commit message when removing translation",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inherit_add_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the commit message when adding translation configured in the workspace.",
                verbose_name="Inherit commit message when adding translation",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inherit_addon_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the commit message when add-on makes a change configured in the workspace.",
                verbose_name="Inherit commit message when add-on makes a change",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inherit_agreement",
            field=models.BooleanField(
                default=False,
                help_text="Use the contributor license agreement configured in the workspace.",
                verbose_name="Inherit contributor license agreement",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inherit_commit_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the commit message when translating configured in the workspace.",
                verbose_name="Inherit commit message when translating",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inherit_delete_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the commit message when removing translation configured in the workspace.",
                verbose_name="Inherit commit message when removing translation",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inherit_language_code_style",
            field=models.BooleanField(
                default=False,
                help_text="Use the language code style configured in the workspace.",
                verbose_name="Inherit language code style",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inherit_license",
            field=models.BooleanField(
                default=False,
                help_text="Use the translation license configured in the workspace.",
                verbose_name="Inherit translation license",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inherit_merge_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the commit message when merging translation configured in the workspace.",
                verbose_name="Inherit commit message when merging translation",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inherit_new_lang",
            field=models.BooleanField(
                default=False,
                help_text="Use the adding new translations setting configured in the workspace.",
                verbose_name="Inherit adding new translations",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inherit_pull_message",
            field=models.BooleanField(
                default=False,
                help_text="Use the merge request message configured in the workspace.",
                verbose_name="Inherit merge request message",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inherit_secondary_language",
            field=models.BooleanField(
                default=False,
                help_text="Use the secondary language configured in the workspace.",
                verbose_name="Inherit secondary language",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="language_code_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Default based on the file format"),
                    ("posix", "POSIX style using underscore as a separator"),
                    (
                        "posix_lowercase",
                        "POSIX style using underscore as a separator, lower cased",
                    ),
                    ("bcp", "BCP style using hyphen as a separator"),
                    (
                        "posix_long",
                        "POSIX style using underscore as a separator, including country code",
                    ),
                    (
                        "posix_long_lowercase",
                        "POSIX style using underscore as a separator, including country code, lower cased",
                    ),
                    (
                        "bcp_long",
                        "BCP style using hyphen as a separator, including country code",
                    ),
                    (
                        "bcp_legacy",
                        "BCP style using hyphen as a separator, legacy language codes",
                    ),
                    ("bcp_lower", "BCP style using hyphen as a separator, lower cased"),
                    ("android", "Android style"),
                    ("appstore", "Apple App Store metadata style"),
                    ("googleplay", "Google Play metadata style"),
                    ("linux", "Linux style"),
                    ("linux_lowercase", "Linux style, lower cased"),
                ],
                default="",
                help_text="Customize language code used to generate the filename for translations created by Weblate.",
                max_length=20,
                verbose_name="Language code style",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="license",
            field=models.CharField(
                blank=not settings.LICENSE_REQUIRED,
                choices=get_license_choices(),
                default="",
                max_length=150,
                verbose_name="Translation license",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="merge_message",
            field=models.TextField(
                default=settings.DEFAULT_MERGE_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_component],
                verbose_name="Commit message when merging translation",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="new_lang",
            field=models.CharField(
                choices=[
                    ("contact", "Contact maintainers"),
                    ("url", "Point to translation instructions URL"),
                    ("add", "Create new language file"),
                    ("none", "Disable adding new translations"),
                ],
                default="add",
                help_text="How to handle requests for creating new translations.",
                max_length=10,
                verbose_name="Adding new translation",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="pull_message",
            field=models.TextField(
                default=settings.DEFAULT_PULL_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_addon],
                verbose_name="Merge request message",
            ),
        ),
        migrations.AlterField(
            model_name="contributoragreement",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.component",
            ),
        ),
        migrations.AddConstraint(
            model_name="contributoragreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("component__isnull", False),
                        ("project__isnull", True),
                        ("workspace__isnull", True),
                    ),
                    models.Q(
                        ("component__isnull", True),
                        ("project__isnull", False),
                        ("workspace__isnull", True),
                    ),
                    models.Q(
                        ("component__isnull", True),
                        ("project__isnull", True),
                        ("workspace__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="contributor_agreement_single_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="contributoragreement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("component__isnull", False)),
                fields=("user", "component"),
                name="contributor_agreement_unique_component",
            ),
        ),
        migrations.AddConstraint(
            model_name="contributoragreement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("user", "project"),
                name="contributor_agreement_unique_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="contributoragreement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", False)),
                fields=("user", "workspace"),
                name="contributor_agreement_unique_workspace",
            ),
        ),
    ]
