# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0082_change_old'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'permissions': (('manage_acl', 'Can manage ACL rules for a project'), ('access_project', 'Can access project')), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
