# Generated by Django 3.0.6 on 2020-06-02 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0082_component_push_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="restricted",
            field=models.BooleanField(
                default=settings.DEFAULT_RESTRICTED_COMPONENT,
                db_index=True,
                help_text="Restrict access to the component to only those explicitly given permission.",
                verbose_name="Restricted component",
            ),
        ),
    ]
