# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.5 on 2026-05-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0084_consolidate_inherited_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="inherit_add_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the commit message when adding translation configured in the project.",
                verbose_name="Inherit commit message when adding translation",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="inherit_addon_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the commit message when add-on makes a change configured in the project.",
                verbose_name="Inherit commit message when add-on makes a change",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="inherit_agreement",
            field=models.BooleanField(
                default=True,
                help_text="Use the contributor license agreement configured in the project.",
                verbose_name="Inherit contributor license agreement",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="inherit_commit_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the commit message when translating configured in the project.",
                verbose_name="Inherit commit message when translating",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="inherit_delete_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the commit message when removing translation configured in the project.",
                verbose_name="Inherit commit message when removing translation",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="inherit_language_code_style",
            field=models.BooleanField(
                default=True,
                help_text="Use the language code style configured in the project.",
                verbose_name="Inherit language code style",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="inherit_license",
            field=models.BooleanField(
                default=True,
                help_text="Use the translation license configured in the project.",
                verbose_name="Inherit translation license",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="inherit_merge_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the commit message when merging translation configured in the project.",
                verbose_name="Inherit commit message when merging translation",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="inherit_new_lang",
            field=models.BooleanField(
                default=True,
                help_text="Use the adding new translations setting configured in the project.",
                verbose_name="Inherit adding new translations",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="inherit_pull_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the merge request message configured in the project.",
                verbose_name="Inherit merge request message",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="inherit_secondary_language",
            field=models.BooleanField(
                default=True,
                help_text="Use the secondary language configured in the project.",
                verbose_name="Inherit secondary language",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inherit_add_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the commit message when adding translation configured in the workspace.",
                verbose_name="Inherit commit message when adding translation",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inherit_addon_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the commit message when add-on makes a change configured in the workspace.",
                verbose_name="Inherit commit message when add-on makes a change",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inherit_agreement",
            field=models.BooleanField(
                default=True,
                help_text="Use the contributor license agreement configured in the workspace.",
                verbose_name="Inherit contributor license agreement",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inherit_commit_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the commit message when translating configured in the workspace.",
                verbose_name="Inherit commit message when translating",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inherit_delete_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the commit message when removing translation configured in the workspace.",
                verbose_name="Inherit commit message when removing translation",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inherit_language_code_style",
            field=models.BooleanField(
                default=True,
                help_text="Use the language code style configured in the workspace.",
                verbose_name="Inherit language code style",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inherit_license",
            field=models.BooleanField(
                default=True,
                help_text="Use the translation license configured in the workspace.",
                verbose_name="Inherit translation license",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inherit_merge_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the commit message when merging translation configured in the workspace.",
                verbose_name="Inherit commit message when merging translation",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inherit_new_lang",
            field=models.BooleanField(
                default=True,
                help_text="Use the adding new translations setting configured in the workspace.",
                verbose_name="Inherit adding new translations",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inherit_pull_message",
            field=models.BooleanField(
                default=True,
                help_text="Use the merge request message configured in the workspace.",
                verbose_name="Inherit merge request message",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="inherit_secondary_language",
            field=models.BooleanField(
                default=True,
                help_text="Use the secondary language configured in the workspace.",
                verbose_name="Inherit secondary language",
            ),
        ),
    ]
