# Generated by Django 3.0.6 on 2020-06-09 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0001_initial"),
        ("trans", "0084_auto_20200605_0648"),
    ]

    operations = [
        migrations.AddField(
            model_name="change",
            name="glossary_term",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="glossary.Term",
            ),
        ),
    ]
