# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0084_auto_20170406_0858'),
        ('permissions', '0006_auto_20170404_1637'),
    ]

    operations = [
    ]
