# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0085_auto_20170406_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owners',
        ),
    ]
