# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0086_remove_project_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
