# Generated by Django 3.0.7 on 2020-07-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0089_auto_20200630_1321"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
