# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170512010505 on 2017-07-18 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0089_auto_20170713_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name to display', max_length=60, unique=True, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='Name used in URLs and file names.', max_length=60, unique=True, verbose_name='URL slug'),
        ),
    ]
