# Generated by Django 3.0.7 on 2020-07-23 08:41

from django.db import migrations


def report_progress(previous, current):
    if previous != current and current % 5 == 0:
        print(f"Migrating JSON strings ... {current}%")
    return current


def migrate_componentlist(apps, schema_editor):
    Unit = apps.get_model("trans", "Unit")
    db_alias = schema_editor.connection.alias
    units = Unit.objects.using(db_alias).filter(
        translation__component__file_format__in=(
            "json",
            "arb",
            "go-i18n-json",
            "i18next",
            "webextension",
            "json-nested",
        )
    )
    count = units.count()
    if not count:
        return
    progress = -1
    for pos, unit in enumerate(units.iterator()):
        if unit.context.startswith("."):
            unit.context = unit.context[1:]
            unit.save(update_fields=["context"])
        progress = report_progress(progress, 100 * pos // count)
    report_progress(progress, 100)


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0090_alert_updated"),
    ]

    operations = [
        migrations.RunPython(
            migrate_componentlist, migrations.RunPython.noop, elidable=True
        ),
    ]
