# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170512010505 on 2017-07-19 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0091_auto_20170719_1612'),
    ]

    operations = [
    ]
