# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170512010505 on 2017-07-19 14:16
from __future__ import unicode_literals

from django.db import migrations


def migrate_push_on_commit(apps, schema_editor):
    Project = apps.get_model('trans', 'Project')
    for project in Project.objects.all():
        project.subproject_set.update(
            push_on_commit=project.push_on_commit
        )


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0091_auto_20170719_1612'),
    ]

    operations = [
        migrations.RunPython(migrate_push_on_commit),
    ]
