# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170512010505 on 2017-07-19 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0092_auto_20170719_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='push_on_commit',
        ),
    ]
