# Generated by Django
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trans', '0093_project_workspace_tm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trans.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'unit review',
                'verbose_name_plural': 'unit reviews',
                'unique_together': {('unit', 'user')},
            },
        ),
    ]
