# -*- coding: utf-8 -*-
# Generated by Django 1.11.4.dev20170727124559 on 2017-08-13 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0093_remove_project_push_on_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='pending',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
