# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170816164241 on 2017-09-25 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0096_auto_20170925_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='access_control',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Protected'), (100, 'Private')], default=0, help_text='How to restrict access to this project, please check documentation for more details.', verbose_name='Access control'),
        ),
    ]
