# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170816164241 on 2017-09-25 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_auto_20170510_1036'),
        ('trans', '0098_migrate_acl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='enable_acl',
        ),
    ]
