# Generated by Django 3.0.7 on 2020-09-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0101_fix_rename_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="source_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.Unit",
            ),
        ),
    ]
