# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170816164241 on 2017-11-20 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0103_auto_20171120_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
