# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

# Generated by Django 6.0.8 on 2026-09-21 07:03
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0105_contributor_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="manage_units",
            field=models.BooleanField(
                default=False,
                help_text="Enables adding, removing, and editing source strings and keys in Weblate. If your strings are extracted from the source code or managed externally you probably want to keep it disabled.",
                verbose_name="Manage strings",
            ),
        ),
    ]
