# Generated by Django 3.1.1 on 2020-10-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0105_auto_20201006_1254"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="content_hash",
        ),
    ]
