# Generated by Django 3.1.4 on 2021-01-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0106_remove_unit_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="links",
            field=models.ManyToManyField(
                blank=True,
                help_text="Choose additional projects where this component will be listed.",
                related_name="shared_components",
                to="trans.Project",
                verbose_name="Share in projects",
            ),
        ),
    ]
