# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170816164241 on 2017-11-21 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0107_migrate_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='fuzzy',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='translated',
        ),
    ]
