# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170816164241 on 2017-11-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0109_auto_20171121_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translation',
            name='approved_words',
            field=models.IntegerField(default=0),
        ),
    ]
