# -*- coding: utf-8 -*-
# Generated by Django 1.11.8.dev20171123183638 on 2017-11-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0111_count_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='approved_suggestions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translation',
            name='approved_suggestions_words',
            field=models.IntegerField(default=0),
        ),
    ]
