# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0113_auto_20171205_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='enabled',
        ),
    ]
