# Generated by Django 3.1.4 on 2021-01-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0113_component_new_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="component",
            old_name="new_unit",
            new_name="manage_units",
        ),
        migrations.AlterField(
            model_name="component",
            name="manage_units",
            field=models.BooleanField(
                default=False,
                help_text="Enables adding and removing strings straight from Weblate. If your strings are extracted from the source code or managed externally you probably want to keep it disabled.",
                verbose_name="Manage strings",
            ),
        ),
    ]
