# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

# Generated by Django 6.0.8 on 2026-10-05 07:36
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0114_alter_project_public_sharing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="contribute_shared_tm",
            field=models.BooleanField(
                default=True,
                help_text="Publishes source strings, translations, and project and component origin to the global shared translation memory. Project access control does not restrict this shared data.",
                verbose_name="Contribute to shared translation memory",
            ),
        ),
    ]
