# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0115_auto_20171213_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_review',
            field=models.BooleanField(default=False, help_text='Enable this if you intend to use dedicated reviewers to approve translations.', verbose_name='Enable reviews'),
        ),
    ]
