# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0117_auto_20180104_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
