# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0118_delete_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='approved_suggestions',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='approved_suggestions_words',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='approved_words',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='failing_checks',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='failing_checks_words',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='fuzzy',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='fuzzy_words',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='have_comment',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='have_suggestion',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='total',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='total_words',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='translated',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='translated_words',
        ),
    ]
