# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0007_migrate_plurals'),
        ('trans', '0119_auto_20180124_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='plural',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lang.Plural'),
        ),
    ]
