# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0122_auto_20180129_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='content_hash',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_hash',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='source',
            name='id_hash',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='content_hash',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id_hash',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='priority',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterIndexTogether(
            name='unit',
            index_together=set([('priority', 'position'), ('translation', 'pending')]),
        ),
    ]
