# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0011_auto_20180215_1158'),
        ('trans', '0123_auto_20180215_1147'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='check',
            index_together=set([('project', 'language', 'content_hash')]),
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('project', 'language', 'content_hash')]),
        ),
        migrations.AlterIndexTogether(
            name='suggestion',
            index_together=set([('project', 'language', 'content_hash')]),
        ),
    ]
