# Generated by Django 3.1.4 on 2021-03-05 09:18

from django.db import migrations


def disable_glossary_new_lang(apps, schema_editor):
    Component = apps.get_model("trans", "Component")
    db_alias = schema_editor.connection.alias
    Component.objects.using(db_alias).filter(is_glossary=True, new_lang="add").update(
        new_lang="none"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0123_fix_enforced_checks"),
    ]

    operations = [migrations.RunPython(disable_glossary_new_lang, elidable=True)]
