# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0125_auto_20180309_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboardmessage',
            name='message_html',
            field=models.BooleanField(default=False, help_text='When disabled, URLs will be converted to links and any markup will be escaped.', verbose_name='Render as HTML'),
        ),
    ]
