# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0128_componentlist_show_dashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['priority', 'position'], 'permissions': (('save_translation', 'Can save translation'), ('save_template', 'Can save template'), ('review_translation', 'Can review translation'), ('ignore_check', 'Can ignore check results'))},
        ),
    ]
