# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0129_auto_20180416_1541'),
    ]

    database_operations = [
        migrations.AlterUniqueTogether(
            name='check',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='check',
            index_together=set([]),
        ),
        migrations.AlterModelTable('Check', 'checks_check')
    ]

    state_operations = [
        migrations.DeleteModel('Check')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
