# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    # This can not be done atomic on SQLite
    atomic = False

    dependencies = [
        ('lang', '0011_auto_20180215_1158'),
        ('trans', '0130_auto_20180416_1503'),
        ('addons', '0005_unwrapped_po'),
        ('gitexport', '0001_initial'),
        ('permissions', '0001_initial'),
        ('screenshots', '0001_initial'),

    ]

    operations = [
        migrations.RenameModel(
            old_name='SubProject',
            new_name='Component',
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['priority', 'project__name', 'name'], 'permissions': (('lock_component', 'Can lock translation for translating'), ('change_subproject', 'Can change component'), ('can_see_git_repository', 'Can see VCS repository URL'), ('access_vcs', 'Can access VCS repository'), ('view_reports', 'Can display reports')), 'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.RenameField(
            model_name='change',
            old_name='subproject',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='subproject',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='subproject',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='whiteboardmessage',
            old_name='subproject',
            new_name='component',
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('id_hash', 'component')]),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set([('component', 'language')]),
        ),
    ]
