# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0131_auto_20180416_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['priority', 'project__name', 'name'], 'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ['source']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['language__name']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['priority', 'position']},
        ),
    ]
