# Generated by Django 3.2 on 2021-05-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0131_alter_unit_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Empty"),
                    (10, "Needs editing"),
                    (20, "Translated"),
                    (30, "Approved"),
                    (100, "Read only"),
                ],
                default=0,
            ),
        ),
    ]
