# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0132_auto_20180517_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='extra_commit_file',
        ),
        migrations.RemoveField(
            model_name='component',
            name='post_add_script',
        ),
        migrations.RemoveField(
            model_name='component',
            name='post_commit_script',
        ),
        migrations.RemoveField(
            model_name='component',
            name='post_push_script',
        ),
        migrations.RemoveField(
            model_name='component',
            name='post_update_script',
        ),
        migrations.RemoveField(
            model_name='component',
            name='pre_commit_script',
        ),
    ]
