# Generated by Django 3.2 on 2021-05-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0133_glossary_missing_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="remote_revision",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
