# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0136_auto_20180521_1048'),
    ]

    operations = [
    ]
