# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import weblate.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0137_commit_formatting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='add_message',
            field=models.TextField(default=settings.DEFAULT_ADD_MESSAGE, help_text='You can use template language for various information, please check documentation for more details.', validators=[weblate.utils.validators.validate_render], verbose_name='Commit message when adding translation'),
        ),
        migrations.AlterField(
            model_name='component',
            name='commit_message',
            field=models.TextField(default=settings.DEFAULT_COMMIT_MESSAGE, help_text='You can use template language for various information, please check documentation for more details.', validators=[weblate.utils.validators.validate_render], verbose_name='Commit message when translating'),
        ),
        migrations.AlterField(
            model_name='component',
            name='delete_message',
            field=models.TextField(default=settings.DEFAULT_DELETE_MESSAGE, help_text='You can use template language for various information, please check documentation for more details.', validators=[weblate.utils.validators.validate_render], verbose_name='Commit message when removing translation'),
        ),
    ]
