# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0138_auto_20180521_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='context',
            field=models.TextField(blank=True, default=''),
        ),
    ]
