# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-23 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0139_source_context'),
    ]

    operations = [
    ]
