# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-28 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0140_change_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='linked_component',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='trans.Component', verbose_name='Project'),
        ),
    ]
