# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-28 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0141_component_linked_component'),
    ]

    operations = [
    ]
