# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0142_linked_component_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='access_control',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Protected'), (100, 'Private'), (200, 'Custom')], default=0, help_text='How to restrict access to this project is detailed in the documentation.', verbose_name='Access control'),
        ),
        migrations.AlterField(
            model_name='project',
            name='enable_review',
            field=models.BooleanField(default=False, help_text='Requires dedicated reviewers to approve translations.', verbose_name='Enable reviews'),
        ),
        migrations.AlterField(
            model_name='project',
            name='set_translation_team',
            field=models.BooleanField(default=True, help_text='Whether the "Translation-Team" field in file headers should be updated by Weblate.', verbose_name='Set "Translation-Team" header'),
        ),
    ]
