# Generated by Django 4.0.4 on 2022-05-17 08:11

from django.db import migrations

from weblate.utils.hash import calculate_hash


def fix_convert_context(apps, schema_editor):
    Unit = apps.get_model("trans", "Unit")
    units = Unit.objects.using(schema_editor.connection.alias).filter(
        translation__component__file_format__in=(
            "html",
            "idml",
            "rc",
            "txt",
            "dokuwiki",
            "mediawiki",
        )
    )

    for unit in units.iterator():
        unit.location = unit.context
        unit.context = ""
        unit.id_hash = calculate_hash(unit.source)
        unit.save(update_fields=["location", "context", "id_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0149_component_pull_message"),
    ]

    operations = [migrations.RunPython(fix_convert_context, elidable=True)]
