# Generated by Django 4.0.5 on 2022-10-18 21:24

from django.db import migrations, models

import weblate.trans.validators
import weblate.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0157_alter_alert_details_alter_component_enforced_checks"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="screenshot_filemask",
            field=models.CharField(
                blank=True,
                help_text="Path of screenshots relative to repository root,for example: docs/screenshots/*.png.",
                max_length=400,
                validators=[
                    weblate.trans.validators.validate_filemask,
                    weblate.utils.validators.validate_filename,
                ],
                verbose_name="Screenshot file mask",
            ),
        ),
    ]
