# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.1 on 2023-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0167_pending_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
