# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-04 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0176_jsonfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="details",
        ),
        migrations.RemoveField(
            model_name="change",
            name="details",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="userdetails",
        ),
        migrations.RemoveField(
            model_name="component",
            name="enforced_checks",
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="userdetails",
        ),
    ]
