# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-04 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0177_remove_alert_details_remove_change_details_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alert",
            old_name="details_new",
            new_name="details",
        ),
        migrations.RenameField(
            model_name="change",
            old_name="details_new",
            new_name="details",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="userdetails_new",
            new_name="userdetails",
        ),
        migrations.RenameField(
            model_name="component",
            old_name="enforced_checks_new",
            new_name="enforced_checks",
        ),
        migrations.RenameField(
            model_name="suggestion",
            old_name="userdetails_new",
            new_name="userdetails",
        ),
    ]
