# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-08 12:10

from django.db import migrations


def change_duplicate_language(apps, schema_editor):
    Change = apps.get_model("trans", "Change")
    Change.objects.using(schema_editor.connection.alias).filter(action=40).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0179_alter_change_action"),
    ]

    operations = [
        migrations.RunPython(
            change_duplicate_language, migrations.RunPython.noop, elidable=True
        )
    ]
