# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-23 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0182_category_component_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="component",
            unique_together=set(),
        ),
    ]
