# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-09-05 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trans", "0186_alter_unit_translation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variant",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="alert",
            name="component",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.component",
            ),
        ),
        migrations.AlterField(
            model_name="contributoragreement",
            name="user",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="project",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.project",
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="component",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.component",
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="component",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.component",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="suggestion",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.suggestion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variant",
            unique_together={("component", "key", "variant_regex")},
        ),
    ]
