# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.5 on 2023-09-18 07:46

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("glossary", "0001_initial"),
        ("glossary", "0002_migrate_dictionary"),
        ("glossary", "0003_fulltext"),
        ("glossary", "0004_glossary_source_language"),
        ("glossary", "0005_set_source_language"),
        ("glossary", "0006_auto_20210203_1342"),
    ]

    initial = True

    dependencies = []

    operations = []
