# Generated by Django 3.1.4 on 2021-02-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0117_remove_change_glossary_term"),
        ("glossary", "0005_set_source_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="term",
            name="glossary",
        ),
        migrations.RemoveField(
            model_name="term",
            name="language",
        ),
        migrations.DeleteModel(
            name="Glossary",
        ),
        migrations.DeleteModel(
            name="Term",
        ),
    ]
