# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vcs", "0001_cleanup_ssh_hosts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("github", "GitHub")],
                        default="github",
                        max_length=20,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "installation_id",
                    models.CharField(max_length=50, verbose_name="Installation ID"),
                ),
                (
                    "target_type",
                    models.CharField(
                        help_text="Organization or User",
                        max_length=20,
                        verbose_name="Target type",
                    ),
                ),
                (
                    "target_login",
                    models.CharField(
                        help_text="Hosting organization or user login",
                        max_length=255,
                        verbose_name="Target login",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        default="github.com",
                        max_length=255,
                        verbose_name="Hostname",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "repositories",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Available repositories"
                    ),
                ),
                ("repositories_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "code-hosting installation",
                "verbose_name_plural": "code-hosting installations",
                "unique_together": {("provider", "hostname", "installation_id")},
            },
        ),
    ]
