# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
        ("vcs", "0002_githubinstallation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubinstallation",
            name="created_by",
        ),
        migrations.AddField(
            model_name="githubinstallation",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="github_installations",
                to="workspaces.workspace",
                verbose_name="Workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="githubinstallation",
            unique_together={("hostname", "installation_id", "workspace")},
        ),
    ]
