# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.3

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vcs", "0003_githubinstallation_workspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubAppCredentials",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="GitHub hostname",
                    ),
                ),
                (
                    "app_id",
                    models.CharField(max_length=50, verbose_name="App ID"),
                ),
                (
                    "app_slug",
                    models.CharField(max_length=255, verbose_name="App slug"),
                ),
                (
                    "private_key",
                    models.TextField(verbose_name="Private key (PEM)"),
                ),
                (
                    "client_id",
                    models.CharField(max_length=255, verbose_name="OAuth client ID"),
                ),
                (
                    "client_secret",
                    models.CharField(
                        max_length=255, verbose_name="OAuth client secret"
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(max_length=255, verbose_name="Webhook secret"),
                ),
                (
                    "webhook_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Webhook token",
                    ),
                ),
                ("html_url", models.URLField(blank=True, verbose_name="App URL")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Weblate GitHub App credentials",
                "verbose_name_plural": "Weblate GitHub App credentials",
            },
        ),
    ]
