# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vcs", "0005_githubinstallation_proxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingInstallation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("github", "GitHub")],
                        max_length=20,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        max_length=255,
                        verbose_name="Hostname",
                    ),
                ),
                (
                    "installation_id",
                    models.CharField(
                        max_length=50,
                        verbose_name="Installation ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Webhook payload",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pending code-hosting installation",
                "verbose_name_plural": "pending code-hosting installations",
                "unique_together": {("provider", "hostname", "installation_id")},
            },
        ),
    ]
