# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.3

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vcs", "0005_githubappcredentials_webhook_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubInstallation",
            fields=[],
            options={
                "verbose_name": "connected GitHub account",
                "verbose_name_plural": "connected GitHub accounts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vcs.installation",),
        ),
    ]
