# Generated by Django 1.11.13 on 2018-06-21 13:00

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tos", models.DateField(default=datetime.date(1970, 1, 1))),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("address", models.GenericIPAddressField(null=True)),
                ("user_agent", models.CharField(default="", max_length=200)),
            ],
            options={"ordering": ["user__username"]},
        )
    ]
