# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170816164241 on 2017-08-21 15:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='tos',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
    ]
