# Generated by Django 3.2 on 2021-05-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0001_squashed_0002_auto_20190516_1224"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agreement",
            options={
                "verbose_name": "TOS agreement",
                "verbose_name_plural": "TOS agreements",
            },
        ),
    ]
