# Generated by Django 2.2 on 2019-05-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("legal", "0001_squashed_0004_copy_auditlog")]

    operations = [migrations.AlterModelOptions(name="agreement", options={})]
