# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_auto_20170821_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='user_agent',
            field=models.CharField(default='', max_length=200),
        ),
    ]
