# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_auto_20180416_1405'),
    ]

    operations = [
    ]
