# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wladmin", "0001_squashed_0003_auto_20180215_1127")]

    operations = [
        migrations.AlterField(
            model_name="configurationerror",
            name="ignored",
            field=models.BooleanField(db_index=True, default=False),
        )
    ]
