# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wladmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationerror',
            options={'ordering': ['-timestamp']},
        ),
    ]
