# Generated by Django 2.2 on 2019-05-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wladmin", "0002_auto_20181127_2116")]

    operations = [migrations.AlterModelOptions(name="configurationerror", options={})]
