# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wladmin', '0002_auto_20180118_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationerror',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configurationerror',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterIndexTogether(
            name='configurationerror',
            index_together=set([('ignored', 'timestamp')]),
        ),
    ]
