# Generated by Django 3.2 on 2021-05-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wladmin", "0002_supportstatus_discoverable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backuplog",
            options={
                "verbose_name": "Backup log",
                "verbose_name_plural": "Backup logs",
            },
        ),
        migrations.AlterModelOptions(
            name="backupservice",
            options={
                "verbose_name": "Support service",
                "verbose_name_plural": "Support services",
            },
        ),
        migrations.AlterModelOptions(
            name="configurationerror",
            options={
                "verbose_name": "Configuration error",
                "verbose_name_plural": "Configuration errors",
            },
        ),
        migrations.AlterModelOptions(
            name="supportstatus",
            options={
                "verbose_name": "Support status",
                "verbose_name_plural": "Support statuses",
            },
        ),
    ]
