# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.1 on 2025-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wladmin", "0002_update_default_focus_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportstatus",
            name="backup_repository",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="supportstatus",
            name="has_subscription",
            field=models.BooleanField(default=False),
        ),
    ]
