# Generated by Django 3.2.7 on 2021-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wladmin", "0003_auto_20210512_1955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupservice",
            name="repository",
            field=models.CharField(
                default="",
                help_text="Use /path/to/repo for local backups or user@host:/path/to/repo or ssh://user@host:port/path/to/backups for remote SSH backups.",
                max_length=500,
                verbose_name="Backup repository URL",
            ),
        ),
    ]
