# Generated by Django 2.2.4 on 2019-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wladmin", "0003_auto_20190516_1250")]

    operations = [
        migrations.CreateModel(
            name="SupportStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("secret", models.CharField(max_length=400)),
                ("expiry", models.DateTimeField(db_index=True, null=True)),
            ],
        )
    ]
