# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.4 on 2025-07-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wladmin", "0003_supportstatus_backup_repository_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportstatus",
            name="enabled",
            field=models.BooleanField(blank=True, db_index=True, default=True),
        ),
    ]
