# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0 on 2026-04-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wladmin", "0004_supportstatus_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuplog",
            name="warning",
            field=models.BooleanField(default=False),
        ),
    ]
