# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.1.3 on 2023-01-19 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wladmin", "0005_alter_backuplog_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="configurationerror",
            new_name="wladmin_con_ignored_fb498d_idx",
            old_fields=("ignored", "timestamp"),
        ),
    ]
