# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wladmin", "0005_backuplog_warning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backuplog",
            name="event",
            field=models.CharField(
                choices=[
                    ("backup", "Backup performed"),
                    ("error", "Backup failed"),
                    ("database", "Database backup performed"),
                    ("database-error", "Database backup failed"),
                    ("prune", "Deleted the oldest backups"),
                    ("cleanup", "Cleaned up backup storage"),
                    ("init", "Repository initialization"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
