# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.1 on 2023-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wladmin",
            "0006_rename_configurationerror_ignored_timestamp_wladmin_con_ignored_fb498d_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="supportstatus",
            name="limits",
            field=models.JSONField(default=dict),
        ),
    ]
