# Generated by Django 2.2.5 on 2019-09-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wladmin", "0006_auto_20190926_1218")]

    operations = [
        migrations.AlterField(
            model_name="backupservice",
            name="enabled",
            field=models.BooleanField(default=True),
        )
    ]
