# Generated by Django 2.2.5 on 2019-10-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wladmin", "0007_auto_20190926_1406")]

    operations = [
        migrations.AlterField(
            model_name="backuplog",
            name="event",
            field=models.CharField(
                choices=[
                    ("backup", "Backup performed"),
                    ("error", "Backup failed"),
                    ("prune", "Deleted the oldest backups"),
                    ("init", "Repository initialization"),
                ],
                max_length=100,
            ),
        )
    ]
