# Generated by Django 3.2 on 2021-05-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fonts", "0001_squashed_0007_auto_20190517_1907"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="font",
            options={"verbose_name": "Font", "verbose_name_plural": "Fonts"},
        ),
        migrations.AlterModelOptions(
            name="fontgroup",
            options={
                "verbose_name": "Font group",
                "verbose_name_plural": "Font groups",
            },
        ),
        migrations.AlterModelOptions(
            name="fontoverride",
            options={
                "verbose_name": "Font override",
                "verbose_name_plural": "Font overrides",
            },
        ),
    ]
