#!/bin/sh
set -e

TMPDIR=$(mktemp -d)
trap "rm -rf -- '$TMPDIR'" EXIT HUP INT TERM

virtualenv --system-site-packages "$TMPDIR"
. "$TMPDIR/bin/activate"

pip install "Django>=1.6,<1.7"
pip install south

export PYTHONPATH=`pwd`
django-admin.py migrate "$@"
