# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

from copy import deepcopy
from io import StringIO
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

from django.core.management import call_command
from django.test import SimpleTestCase

from weblate.addons.automation_schema import SCHEMA, action_schema, object_schema


class AutomationDocumentationTest(SimpleTestCase):
    def test_schema_updates_preserve_manual_descriptions(self) -> None:
        with TemporaryDirectory() as directory:
            output = Path(directory) / "automation.rst"
            output.write_text("Manual introduction.\n\n", encoding="utf-8")
            call_command("list_automation", output=output, stdout=StringIO())
            text = output.read_text(encoding="utf-8").replace(
                ".. AUTOGENERATED END: action-weblate.bulk_edit\n",
                ".. AUTOGENERATED END: action-weblate.bulk_edit\n\n"
                "Manual action description.\n\n",
            )
            self.assertIn(".. list-table:: Result fields", text)
            self.assertIn("``warnings_omitted``", text)
            text += "\nManual cookbook example.\n"
            output.write_text(text, encoding="utf-8")
            schema = deepcopy(SCHEMA)
            schema["$defs"]["action"]["oneOf"].append(
                action_schema(
                    "weblate.future",
                    "Future operation",
                    "2099.1",
                    object_schema(
                        {
                            "future_parameter": {
                                "type": "array",
                                "items": {"type": ["integer", "null"], "minimum": 1},
                                "minItems": 1,
                                "maxItems": 5,
                                "uniqueItems": True,
                            }
                        },
                        [],
                    ),
                )
            )
            with patch(
                "weblate.addons.management.commands.list_automation.SCHEMA", schema
            ):
                call_command("list_automation", output=output, stdout=StringIO())
                updated = output.read_text(encoding="utf-8")
                self.assertTrue(updated.startswith("Manual introduction."))
                self.assertIn("Manual action description.", updated)
                self.assertTrue(updated.endswith("Manual cookbook example.\n"))
                self.assertIn("Future operation", updated)
                self.assertIn(".. versionadded:: 2099.1", updated)
                self.assertIn("``settings.future_parameter``", updated)
                self.assertIn("List of (integer or null; minimum 1)", updated)
                self.assertIn("minimum items 1; maximum items 5; unique items", updated)
                call_command("list_automation", output=output, stdout=StringIO())
                self.assertEqual(output.read_text(encoding="utf-8"), updated)
