# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

name: pre-commit setup
description: Prepare pre-commit environment

runs:
  using: composite
  steps:
  - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9   # v6.1.0
    with:
      path: |
        ~/.cache/prek
        ~/.cache/kingfisher
      key: ${{ runner.os }}-${{ runner.arch }}-prek-${{ hashFiles('.pre-commit-config.yaml') }}
      restore-keys: |
        ${{ runner.os }}-${{ runner.arch }}-prek-
  - name: Setup Python
    uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1   # v6.3.0
    with:
      python-version: '3.14'
  - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39   # v8.2.0
    with:
      version: 0.11.26
