# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

name: pre-commit setup
description: Prepare pre-commit environment

runs:
  using: composite
  steps:
  - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9   # v6.1.0
    with:
      path: |
        ~/.cache/prek
        ~/.cache/kingfisher
      key: ${{ runner.os }}-${{ runner.arch }}-prek-${{ hashFiles('.pre-commit-config.yaml') }}
      restore-keys: |
        ${{ runner.os }}-${{ runner.arch }}-prek-
  - name: Setup Python
    uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97   # v7.0.0
    with:
      python-version: '3.14'
  - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990   # v8.3.2
    with:
      version: 0.11.29
