#!/bin/sh

set -e

cd weblate
../manage.py makemessages -l $1 -i 'repos/*' -i 'docs/*'
../manage.py makemessages -l $1 -i 'repos/*' -i 'docs/*' -d djangojs
git add locale/$1/
git commit -m "Added $1 language"
