#!/usr/bin/env python3
#
# Copyright © 2012 - 2018 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Helper script to generate Python code from language-data repository
# see https://github.com/WeblateOrg/language-data

import csv

HEADER = '''# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2018 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

############################################################################
# This is automatically generated file, see scripts/generate-language-data #
############################################################################
# pylint: disable=line-too-long,too-many-lines

from __future__ import unicode_literals
'''

TEMPLATE = '''    (
        '{}',
        _('{}'),
        {},
        '{}',
    ),
'''

# Read languages
with open('scripts/language-data/languages.csv', 'r') as csvfile:
    reader = csv.reader(csvfile, delimiter=';')
    LANGUAGES = list(reader)

# Read extra plurals
with open('scripts/language-data/extraplurals.csv', 'r') as csvfile:
    reader = csv.reader(csvfile, delimiter=';')
    EXTRAPLURALS = list(reader)

# Write language definitions
with open('weblate/langdata/languages.py', 'w') as output:
    output.write(HEADER)
    output.write(
        'from django.utils.translation import ugettext_noop as _\n\n'
    )
    output.write('# Language definitions\n')
    output.write('LANGUAGES = (\n')
    for row in LANGUAGES:
        output.write(TEMPLATE.format(
            row[0],
            row[1].replace("'", "\\'"),
            row[2],
            row[3],
        ))
    output.write(')\n\n')
    output.write('# Additional plural rules definitions\n')
    output.write('EXTRAPLURALS = (\n')
    for row in EXTRAPLURALS:
        output.write(TEMPLATE.format(
            row[0],
            row[1].replace("'", "\\'"),
            row[2],
            row[3],
        ))
    output.write(')\n')

# Generate same check blacklist
words = set()
for row in LANGUAGES:
    words.update(
        row[1].replace('(', ' ').replace(')', ' ').replace('-', ' ').lower().split()
    )

# Write same check blacklist
with open('weblate/trans/checks/languages.py', 'w') as output:
    output.write(HEADER)
    output.write('\n\n')
    output.write('# Language names to ignore in same check\n')
    output.write('LANGUAGES = frozenset((\n')
    for word in sorted(words):
        output.write('    \'{}\',\n'.format(
            word.replace("'", "\\'")
        ))
    output.write('))\n')
