#!/usr/bin/python

import json
import urllib2
import imp
import PyICU

URL = 'http://hosted.weblate.org/exports/stats/weblate/master/'
THRESHOLD = 20


def print_language(lang, fmt='{0} ({1})'):
    '''
    Prints language code with it's name.
    '''
    locale = PyICU.Locale(lang)
    print(
        fmt.format(
            lang,
            locale.getDisplayName(locale).capitalize().encode('utf-8')
        )
    )


def main():
    # load data
    handle = urllib2.urlopen(URL)
    data = handle.read()
    handle.close()
    # parse data
    data = json.loads(data)

    # select languages
    languages = []
    for lang in data:
        if lang['translated_percent'] > THRESHOLD:
            languages.append(lang['code'])
    languages.sort()
    print 'Expected setup:'
    for lang in languages:
        print_language(lang, fmt="    ('{0}', u'{1}'),")

    # prepare for checking
    languages = set(languages)
    # we always want english language
    languages.add('en')
    # load settings
    extra = set()
    settings = imp.load_source('settings', './weblate/settings_example.py')
    for lang in settings.LANGUAGES:
        if lang[0] in languages:
            languages.remove(lang[0])
        else:
            extra.add(lang[0])
    # Print results
    if len(extra) > 0:
        print 'Extra languages:'
        for lang in extra:
            print_language(lang)
    if len(languages) > 0:
        print 'Missing languages:'
        for lang in languages:
            print_language(lang)

if __name__ == "__main__":
    main()
