#!/bin/sh

for icon in weblate/static/icons/*.svg ; do 
    echo $icon
    scour --strip-xml-prolog --remove-metadata --no-line-breaks --enable-id-stripping --enable-comment-stripping --indent=none --remove-descriptive-elements $icon $icon.tmp
    sed '/!DOCTYPE/d' < $icon.tmp  > $icon
    rm $icon.tmp
done
