#!/bin/sh
# Packs test data for Weblate
set -e

# Output directory
OUT=`pwd`/weblate/trans/tests/data/

# Working directory
WD=`mktemp -d`
cd $WD

# Close bare Git repo
git clone --bare https://github.com/WeblateOrg/test.git test-base-repo.git
cd test-base-repo.git
git gc --aggressive
cd ..

# Create test data without VCS metadata
mkdir test-data
cd test-base-repo.git 
git archive master | tar -x -v -f - -C ../test-data
cd ..

#  Create Mercurial repo with same content as Git
cp -r test-data test-base-repo.hg 
cd test-base-repo.hg
hg init . 
hg add .
hg commit --date 1970-01-01 -m 'Import git files

Zkouška'
hg update null
cd ..

# Create SVN repo with same content as Git
svnadmin create --compatible-version 1.6 test-base-repo.svn
cd test-data
svn import -m 'Import git files

Zkouška' . file://$WD/test-base-repo.svn/trunk
cd ..

# Pack them
reproducible_tar() {
    tar --sort=name \
      --mtime="1970-01-01" \
      --owner=0 --group=0 --numeric-owner \
      -cf "$@"
}
reproducible_tar $OUT/test-base-repo.hg.tar --owner=root --group=root --numeric-owner --sort=name test-base-repo.hg
reproducible_tar $OUT/test-base-repo.git.tar --owner=root --group=root --numeric-owner --sort=name test-base-repo.git
reproducible_tar $OUT/test-base-repo.svn.tar --owner=root --group=root --numeric-owner --sort=name test-base-repo.svn

# Remove working dir
rm -rf $WD
