#!/bin/sh
# Packs test data for Weblate

# Output directory
OUT=`pwd`/weblate/trans/tests/data/

# Working directory
WD=`mktemp -d`
cd $WD

# Clone and cleanup Mercurial repo
hg clone https://bitbucket.org/nijel/weblate-test test-base-repo.hg
cd test-base-repo.hg
hg update null
cd ..

# Close bare Git repo
git clone --bare https://github.com/WeblateOrg/test.git test-base-repo.git


# Create SVN repo with same content as Git
git clone --reference test-base-repo.git https://github.com/WeblateOrg/test.git test-data
svnadmin create test-base-repo.svn
svn import -m 'Import po files' test-data/po file://$WD/test-base-repo.svn/svn-test/trunk/po

# Pack them
tar cf $OUT/test-base-repo.hg.tar test-base-repo.hg
tar cf $OUT/test-base-repo.git.tar test-base-repo.git
tar cf $OUT/test-base-repo.svn.tar test-base-repo.svn

# Remove working dir
rm -rf $WD
