#!/bin/sh
set -e

if [ -z "$1" ] ; then
    echo 'Usage: ./scripts/set-version VERSION'
    exit 1
fi

sed -i "s/^VERSION =.*/VERSION = \"$1-dev\"/" weblate/__init__.py
sed -i "s/version =.*/version = \"$1\"/" docs/conf.py
sed -i "s/version=.*,/version=\"$1\",/" setup.py

# Update docs/changes.rst
tmp=`mktemp`
cp docs/changes.rst $tmp
cat > docs/changes.rst <<EOT
Weblate $1
-------------

Not yet released.

EOT
cat >> docs/changes.rst < $tmp
rm $tmp

git commit -m "Setting version to $1" weblate/__init__.py docs/conf.py docs/changes.rst setup.py
