#!/usr/bin/env python

# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

import re
import tomllib

print(
    """
.. Table is generated using scripts/show-extras

.. list-table:: Optional dependencies
     :header-rows: 1

     * - pip extra
       - Python Package
       - Weblate feature
"""
)

with open("pyproject.toml", "rb") as handle:
    toml_dict = tomllib.load(handle)

for section, data in toml_dict["project"]["optional-dependencies"].items():
    if section == "all":
        continue
    for index, dependency in enumerate(data):
        dependency = re.split(r"[;<>=[]", dependency)[0].strip()
        section = f"``{section}``" if index == 0 else ""
        print(
            f"""
        * - {section}
        - `{dependency} <https://pypi.org/project/{dependency}>`_
        -
    """
        )
