#!/bin/sh

# Widgets
cp scripts/graphics/widgets/*.png weblate/static/widget-images/

# SVG
cp scripts/graphics/logo/weblate.svg scripts/graphics/logo/weblate-black.svg weblate/static/
./scripts/optimize-svg weblate/static/weblate*.svg

# favicon
cp scripts/graphics/logo/weblate.ico weblate/static/favicon.ico

# Scaled logos
for size in 128 150 180 192 512 ; do
    cp scripts/graphics/logo/weblate-background-$size.png weblate/static/weblate-$size.png
done
for size in 16 32 128 1024 ; do
    cp scripts/graphics/logo/weblate-logo-$size.png weblate/static/logo-$size.png
done

# Widgets
cp scripts/graphics/open-graph/Og-Template.png weblate/static/widget-images/open-graph.png
