#!/bin/sh

# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Wrapper around yarn to update our javascript dependencies
set -e

cd scripts/yarn/

yarn install --check-files

# Source Sans/Code Pro fonts
sed '/font-family/ a font-display: swap;' < node_modules/source-sans/source-sans-3.css > ../../weblate/static/vendor/font-source/source-sans-3.css
sed '/font-family/ a font-display: swap;' < node_modules/source-code-pro/source-code-pro.css > ../../weblate/static/vendor/font-source/source-code-pro.css
find node_modules/source-sans/WOFF node_modules/source-sans/WOFF2 node_modules/source-sans/TTF node_modules/source-code-pro/ \
    -name 'SourceSans3-ExtraLight.*' \
    -o -name 'SourceSans3-Light.*' \
    -o -name 'SourceSans3-Semibold.*' \
    -o -name 'SourceSans3-Black.*' \
    -o -name 'SourceSans3-Bold.*' \
    -o -name 'SourceSans3-Regular.*' \
    -o -name 'SourceSans3-It.*' \
    -o -name 'SourceSans3-BoldIt.*' \
    -o -name 'SourceCodePro-Medium.*' \
    -o -name 'SourceCodePro-Regular.*' \
    -o -name 'SourceCodePro-Bold.*' \
    -o -name 'SourceCodePro-Semibold.*' | while read -r name; do
    target=$(echo "$name" | sed 's@node_modules/source-\(sans\|code-pro\)/@../../weblate/static/vendor/font-source/@')
    dir=$(dirname "$target")
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
    cp "$name" "$target"
done

# Not updated:
# Bootstrap, use online customizer
# bootstrap-rtl as the version in yarn is outdated
