#!/bin/sh
# Script to install Leiptonica and Tesseract
set -e

rm -rf $TESSERACT_INSTALL

TMPDIR=`mktemp -d`
OLDDIR=`pwd`
cd $TMPDIR

wget http://www.leptonica.org/source/leptonica-1.74.1.tar.gz
tar xzf leptonica-1.74.1.tar.gz
cd leptonica-1.74.1
./configure --prefix=$TESSERACT_INSTALL
make install
cd ..

export LIBLEPT_HEADERSDIR="$TESSERACT_INSTALL/include"
export LDFLAGS="-L$TESSERACT_INSTALL/lib"
export CFLAGS="-I$TESSERACT_INSTALL/include"

wget https://github.com/tesseract-ocr/tesseract/archive/3.04.01.tar.gz
tar xzf 3.04.01.tar.gz
cd tesseract-3.04.01
./configure --prefix=$TESSERACT_INSTALL
make install

