#!/bin/sh
# Install and start Sauce Connect
set -e

NAME=sc-4.5.4-linux.tar.gz

rm -f ~/.sauce-ready
rm -f ~/.sauce-log

SC_TEMP=`mktemp -d -t sc.XXXX`
wget -O - https://saucelabs.com/downloads/$NAME | tar -x -z -C $SC_TEMP

daemon --unsafe -- $SC_TEMP/*/bin/sc \
    --tunnel-identifier ${TRAVIS_JOB_NUMBER}${DRONE_BUILD_NUMBER} \
    --readyfile ~/.sauce-ready \
    --logfile ~/.sauce-log \
    --pidfile ~/.sauce-pid

PID=$!

if [ $? -ne 0 ] ; then 
    cat ~/.sauce-log
    exit 1
fi

echo "Waiting for Sauce Connect readyfile"
while [ ! -f ~/.sauce-ready ]; do
    sleep .5
    cat ~/.sauce-log
done
