#!/bin/sh
# Install and start Sauce Connect
set -e

NAME=sc-4.4.9-linux.tar.gz

SC_TEMP=`mktemp -d -t sc.XXXX`
wget -O - https://saucelabs.com/downloads/$NAME | tar -x -z -C $SC_TEMP

$SC_TEMP/*/bin/sc \
    -i ${TRAVIS_JOB_NUMBER} \
    -f $SC_TEMP/ready \
    -l $SC_TEMP/log &

echo $! > ~/.sauce-pid

echo "Waiting for Sauce Connect readyfile"
while [ ! -f $SC_TEMP/ready ]; do
    sleep .5
done
