#!/bin/sh
# Install and start Sauce Connect
set -e

NAME=sc-4.5.3-linux.tar.gz

rm -f ~/.sauce-ready
rm -f ~/.sauce-log

SC_TEMP=`mktemp -d -t sc.XXXX`
wget -O - https://saucelabs.com/downloads/$NAME | tar -x -z -C $SC_TEMP

$SC_TEMP/*/bin/sc \
    -i ${TRAVIS_JOB_NUMBER} \
    -f ~/.sauce-ready \
    -l ~/.sauce-log &

PID=$!

if [ $? -ne 0 ] ; then 
    cat ~/.sauce-log
    exit 1
fi

echo $PID > ~/.sauce-pid

echo "Waiting for Sauce Connect readyfile"
while [ ! -f ~/.sauce-ready ]; do
    sleep .5
done
