#!/bin/sh
# PIP deps installer
set -e
set -x

pip install $CI_PIP_DEPS
pip install Cython
pip install tesserocr==1.2.1rc2
pip install \
    -r requirements-optional.txt \
    -r ci/requirements-${CI_REQUIREMENTS}.txt \
    -r ci/requirements-${CI_DATABASE:-sqlite}.txt
