#!/bin/sh
# PIP deps installer
set -e
set -x

# Install tesseract
# TODO: Use cached version if exists
find $TESSERACT_INSTALL
rm -rf $TESSERACT_INSTALL

TMPDIR=`mktemp -d`
cd $TMPDIR

wget http://www.leptonica.org/source/leptonica-1.74.1.tar.gz
tar xzf leptonica-1.74.1.tar.gz
cd leptonica-1.74.1
./configure --prefix=$TESSERACT_INSTALL
make install
cd ..

export LIBLEPT_HEADERSDIR="$TESSERACT_INSTALL/include"
export LDFLAGS="-L$TESSERACT_INSTALL/lib"
export CFLAGS="-I$TESSERACT_INSTALL/include"

env
pkg-config --debug lept


wget https://github.com/tesseract-ocr/tesseract/archive/3.04.01.tar.gz
tar xzf 3.04.01.tar.gz
cd tesseract-3.04.01
./configure --prefix=$TESSERACT_INSTALL
make install

cd

find $TESSERACT_INSTALL

# Install PyPI packages
pip install $CI_PIP_DEPS
pip install Cython
pip install \
    -r requirements-optional.txt \
    -r ci/requirements-${CI_REQUIREMENTS}.txt \
    -r ci/requirements-${CI_DATABASE:-sqlite}.txt
