#!/bin/sh
# PIP deps installer
set -e
set -x

pip_install() {
    pip install --download-cache ~/.pip-cache/ "$@"
}

pip_install $CI_DJANGO
pip_install \
    -r requirements-optional.txt \
    -r requirements-django-1.6.txt \
    -r ci/requirements-${CI_REQUIREMENTS}.txt \
    -r ci/requirements-${CI_DATABASE:-sqlite}.txt
