#!/bin/sh
# Migration ordering testing
set -e
set -x

for app in trans lang accounts ; do 
    rm -f weblate.db
    ./manage.py migrate --noinput --settings weblate.settings_test sessions
    ./manage.py migrate --settings weblate.settings_test --traceback $app
done
