#!/bin/sh

set -e -x

python -m pip install --upgrade pip wheel
# Install cython and pycairo first, these are needed during install of others
if [ ${1:-latest} = minimal ] ; then
    pip install Cython==0.29.14 pycairo==1.11.1
    pip install requirements-builder
    requirements-builder --req requirements.txt --req requirements-optional.txt --level min > requirements-min.txt
    pip install -r requirements-min.txt
else:
    pip install Cython pycairo
    pip install -r requirements-optional.txt -r requirements-postgresql.txt
fi
pip install -r requirements-test.txt -r requirements-postgresql.txt
