#!/bin/sh

set -e -x

# Install CI requirements
python -m pip install -r requirements-ci.txt

# Workaround for
# SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)
pip install --no-binary :all: cffi

if [ ${1:-latest} = minimal ] ; then
    # Build list of minimal requirements
    requirements-builder --req requirements-test.txt --level min > requirements-min.txt

    # Install cython and pycairo first, these are needed during install of others
    pip install $(grep -E '^(Cython|pycairo)[>=<]' requirements-min.txt)

    pip install -r requirements-min.txt
else
    # Install cython and pycairo first, these are needed during install of others
    pip install $(grep -E '^(Cython|pycairo)[>=<]' requirements.txt)

    pip install --upgrade-strategy eager -U -r requirements-test.txt
    if [ ${1:-latest} = edge ] ; then
        # Install from git / pre-release
        pip install --upgrade https://github.com/translate/translate/archive/master.zip
        pip install --upgrade https://github.com/WeblateOrg/language-data/archive/main.zip
        pip install --upgrade https://github.com/WeblateOrg/translation-finder/archive/main.zip
        pip install --upgrade --pre Django
    fi
fi

# Verify that deps are consistent
pip check
