#!/bin/sh

. ci/lib

cleanup_database

if [ $CI_DATABASE = "mysql" ] ; then
    mysql -e 'SHOW VARIABLES LIKE "%version%";' -uroot
fi
if [ $CI_DATABASE = "postgresql" ] ; then
    if [ -n "$CI_DB_PASSWORD" ] ; then
        export PGPASSWORD="$CI_DB_PASSWORD"
    fi
    psql -c 'SELECT version();' -U postgres
fi
