#!/bin/sh
# List versions used for the test

. ci/lib

print_step "Chrome"
print_version chromium-browser chromium google-chrome chrome

print_step "Chromedriver"
print_version chromedriver

print_step "Python"
print_version python

print_step "Compiler"
print_version gcc clang
