#!/bin/sh
# Setup test executor

. ci/lib

INSTALL_DIR=`mktemp -d`

trap "rm -rf $INSTALL_DIR" EXIT

run_coverage ./setup.py build
check

run_coverage ./setup.py install --root="$INSTALL_DIR"
check

run_coverage ./setup.py sdist
check

INSTALLED_DIR=`find $INSTALL_DIR -name '*-packages' -type d`
BIN_DIR=`find $INSTALL_DIR -name 'bin' -type d`

diff -ruNp weblate/html $INSTALLED_DIR/weblate/html
check

PYTHONPATH=$INSTALLED_DIR:$PYTHONPATH coverage run --source $INSTALLED_DIR --append $BIN_DIR/weblate check
check
