#!/bin/sh
# Selenium testsuite executor

. ci/lib

run_coverage ./manage.py collectstatic --noinput
check

export DO_SELENIUM=1

travis_wait run_coverage ./manage.py test -v 2 -p test_selenium.py
check
