#!/bin/sh
# Migrations test executor

. ci/lib

TAGS="weblate-3.1.1 weblate-3.2.2 weblate-3.3 weblate-3.4 weblate-3.5.1 weblate-3.7.1"
DBS="sqlite mysql postgresql"

for CI_DATABASE in $DBS ; do
    export CI_DATABASE

    for tag in $TAGS ; do
        echo
        echo "Testing migration from $tag on $CI_DATABASE..."
        rm -f weblate.db
        git fetch --depth 1 origin tag $tag
        check
        git checkout $tag
        check
        run_coverage ./manage.py migrate
        check
        ./manage.py shell -c 'from weblate.lang.models import Language; Language.objects.all().delete()'
        check
        # Load basic project fixture
        ./manage.py loaddata simple-project.json
        check
        # Enable suggestion voting
        ./manage.py shell -c 'from weblate.trans.models import Component; Component.objects.all().update(suggestion_voting=True, suggestion_autoaccept=2)'
        check
        # Add suggestions
        ./manage.py add_suggestions test test cs weblate/trans/tests/data/cs.po
        check
        # Add vote for suggestion
        ./manage.py shell -c 'from weblate.trans.models import Vote, Suggestion; s = Suggestion.objects.all()[0]; vote = Vote(suggestion=s, user=s.user); vote.value = 1; vote.positive = True; vote.save()'
        check
        git checkout $TRAVIS_COMMIT
        run_coverage ./manage.py migrate
        check
    done
done

./manage.py makemigrations
check
if [ `git status -s | grep -c /migrations/` -gt 0 ] ; then
    echo 'There are untracked migrations:'
    git status -s --porcelain | grep /migrations/ | sed -n '/^??/ s/^?? \(.*\)/\1/p' | while read migration ; do
        echo $migration
        cat $migration
        echo
    done
    exit 1
fi
