#!/bin/sh
# Testsuite executor

. ci/lib

run_coverage ./manage.py migrate --noinput --traceback
check

run_coverage ./manage.py collectstatic --noinput
check

run_coverage ./manage.py check
check

run_coverage ./manage.py test -v 2
check
