#!/bin/sh
# Linter for our code
./scripts/generate-locales
echo pep8
pep8 --exclude south_migrations,migrations weblate openshift
pep_ret=$?
echo pylint
pylint --rcfile=pylint.rc weblate
pylint_ret=$?
echo pyflakes
pyflakes `find . -name '*.py' -not -name '__init__.py' -not -name 'settings_test_*.py' -not -name 'settings_test.py' -not -name 'settings_openshift.py'`
pyflakes_ret=$?

exit $(($pep_ret + $pylint_ret + $pyflakes_ret))
