#!/bin/sh

set -e

if [ ! -f services-up ] ; then
    cd ci
fi

filename="docker-compose-$1.yml"

if [ ! -f "$filename" ] ; then
    echo "Skipping: $filename"
else
    docker-compose --file "$filename" up -d
fi
