#!/bin/sh

# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

if [ ! -f services-down ]; then
    cd ci
fi

if [ -n "$2" ] && [ "$2" != "valkey" ]; then
    filename="docker-compose-$1-$2.yml"
else
    filename="docker-compose-$1.yml"
fi

docker compose --file "$filename" logs
docker compose --file "$filename" down --remove-orphans
