#!/bin/sh

set -e

if [ ! -f services-down ] ; then
    cd ci
fi

filename="docker-compose-$1.yml"

if [ ! -f "$filename" ] ; then
    echo "Skipping: $filename"
else
    docker-compose --file "$filename" logs
    docker-compose --file "$filename" down
fi
