#!/bin/sh
# Environment setup
set -e
set -x
mysql -e 'DROP DATABASE IF EXISTS weblate;' -uroot
mysql -e 'CREATE DATABASE weblate CHARACTER SET utf8 COLLATE utf8_general_ci;' -uroot
psql -c 'DROP DATABASE IF EXISTS weblate;' -U postgres
psql -c 'CREATE DATABASE weblate;' -U postgres
