# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.4 on 2026-05-06 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("addons", "0001_squashed_weblate_5"),
        ("addons", "0002_remove_addon_project_scope_addon_project_and_more"),
        ("addons", "0003_addonactivitylog"),
        ("addons", "0004_alter_addonactivitylog_event_alter_event_event"),
    ]

    initial = True

    dependencies = [
        ("trans", "0001_squashed_weblate_5"),
        ("trans", "0004_alter_change_action"),
        ("trans", "0012_alter_announcement_notify"),
    ]

    operations = [
        migrations.CreateModel(
            name="Addon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "component",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trans.component",
                    ),
                ),
                ("repo_scope", models.BooleanField(db_index=True, default=False)),
                ("configuration", models.JSONField(default=dict)),
                ("state", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trans.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "add-on",
                "verbose_name_plural": "add-ons",
            },
        ),
        migrations.CreateModel(
            name="AddonActivityLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.IntegerField(
                        choices=[
                            (1, "Repository post-push"),
                            (2, "Repository post-update"),
                            (3, "Repository pre-commit"),
                            (4, "Repository post-commit"),
                            (5, "Repository post-add"),
                            (6, "Unit pre-create"),
                            (7, "Storage post-load"),
                            (8, "Unit post-save"),
                            (9, "Repository pre-update"),
                            (10, "Repository pre-push"),
                            (11, "Daily"),
                            (12, "Component update"),
                        ]
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="addons.addon"
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trans.component",
                    ),
                ),
            ],
            options={
                "verbose_name": "add-on activity log",
                "verbose_name_plural": "add-on activity logs",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.IntegerField(
                        choices=[
                            (1, "Repository post-push"),
                            (2, "Repository post-update"),
                            (3, "Repository pre-commit"),
                            (4, "Repository post-commit"),
                            (5, "Repository post-add"),
                            (6, "Unit pre-create"),
                            (7, "Storage post-load"),
                            (8, "Unit post-save"),
                            (9, "Repository pre-update"),
                            (10, "Repository pre-push"),
                            (11, "Daily"),
                            (12, "Component update"),
                        ]
                    ),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addons.addon",
                    ),
                ),
            ],
            options={
                "unique_together": {("addon", "event")},
                "verbose_name": "add-on event",
                "verbose_name_plural": "add-on events",
            },
        ),
    ]
