# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 21:59
from __future__ import print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0002_auto_20180203_2258'),
    ]

    operations = [
    ]
