# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0003_alter_event_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="addon",
            name="configuration_new",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="addon",
            name="state_new",
            field=models.JSONField(default=dict),
        ),
    ]
