# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.1.3 on 2024-11-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0003_addonactivitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addonactivitylog",
            name="event",
            field=models.IntegerField(
                choices=[
                    (1, "Repository post-push"),
                    (2, "Repository post-update"),
                    (3, "Repository pre-commit"),
                    (4, "Repository post-commit"),
                    (5, "Repository post-add"),
                    (6, "Unit pre-create"),
                    (7, "Storage post-load"),
                    (8, "Unit post-save"),
                    (9, "Repository pre-update"),
                    (10, "Repository pre-push"),
                    (11, "Daily"),
                    (12, "Component update"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event",
            field=models.IntegerField(
                choices=[
                    (1, "Repository post-push"),
                    (2, "Repository post-update"),
                    (3, "Repository pre-commit"),
                    (4, "Repository post-commit"),
                    (5, "Repository post-add"),
                    (6, "Unit pre-create"),
                    (7, "Storage post-load"),
                    (8, "Unit post-save"),
                    (9, "Repository pre-update"),
                    (10, "Repository pre-push"),
                    (11, "Daily"),
                    (12, "Component update"),
                ]
            ),
        ),
    ]
