# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 12:00
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0004_auto_20180309_1300'),
    ]

    operations = [
    ]
