# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2 on 2025-05-07 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0005_alter_addonactivitylog_event_alter_event_event"),
        ("trans", "0034_project_check_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addonactivitylog",
            name="component",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.component",
            ),
        ),
    ]
