# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-04 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0005_jsonfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addon",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="addon",
            name="state",
        ),
    ]
