# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0005_unwrapped_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='project_scope',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
