# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-08-04 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0006_remove_addon_configuration_remove_addon_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addon",
            old_name="configuration_new",
            new_name="configuration",
        ),
        migrations.RenameField(
            model_name="addon",
            old_name="state_new",
            new_name="state",
        ),
    ]
