# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0006_addon_project_scope'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addon',
            unique_together=set([]),
        ),
    ]
