# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-09-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0007_rename_configuration_new_addon_configuration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="addon",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="addons.addon",
            ),
        ),
    ]
