# Generated by Django 1.11.16 on 2018-12-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("addons", "0009_auto_20181207_1322")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event",
            field=models.IntegerField(
                choices=[
                    (10, "pre push"),
                    (1, "post push"),
                    (9, "pre update"),
                    (2, "post update"),
                    (3, "pre commit"),
                    (4, "post commit"),
                    (5, "post add"),
                    (6, "unit post create"),
                    (8, "unit post save"),
                    (7, "store post load"),
                ]
            ),
        )
    ]
