# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.5 on 2025-09-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0010_alter_addonactivitylog_event_alter_event_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonactivitylog",
            name="pending",
            field=models.BooleanField(default=False),
        ),
    ]
