# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.3 on 2026-03-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0013_alter_addonactivitylog_event_alter_event_event"),
        ("trans", "0065_alter_change_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="addon",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.category",
            ),
        ),
    ]
