# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.9 on 2026-04-15 00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations

from weblate.addons.events import AddonEvent
from weblate.addons.utils import adjust_addon_events

if TYPE_CHECKING:
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.state import StateApps


def add_manual_event_to_extract_pot_addons(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    adjust_addon_events(
        apps,
        schema_editor,
        [
            "weblate.gettext.xgettext",
            "weblate.gettext.meson",
            "weblate.gettext.django",
            "weblate.gettext.sphinx",
        ],
        [AddonEvent.EVENT_MANUAL],
        [],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0016_alter_addonactivitylog_event_alter_event_event"),
    ]

    operations = [
        migrations.RunPython(
            add_manual_event_to_extract_pot_addons,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
