# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.5 on 2026-05-12

from __future__ import annotations

from django.conf import settings
from django.db import migrations

from weblate.addons.events import AddonEvent


def migrate_cleanup_setting(
    apps, name: str, configuration: dict[str, int | None]
) -> None:
    Addon = apps.get_model("addons", "Addon")
    Event = apps.get_model("addons", "Event")

    addons = Addon.objects.filter(
        component__isnull=True,
        category__isnull=True,
        project__isnull=True,
        name=name,
    )
    installed = list(addons)
    if not installed:
        installed = [Addon.objects.create(name=name, configuration=configuration)]
    else:
        addons.update(configuration=configuration)

    for addon in installed:
        Event.objects.get_or_create(addon=addon, event=int(AddonEvent.EVENT_DAILY))


def migrate_cleanup_settings(apps, _schema_editor) -> None:
    comment_cleanup_days = getattr(settings, "COMMENT_CLEANUP_DAYS", None)
    if comment_cleanup_days and comment_cleanup_days > 0:
        migrate_cleanup_setting(
            apps,
            "weblate.removal.comments",
            {"age": comment_cleanup_days},
        )

    suggestion_cleanup_days = getattr(settings, "SUGGESTION_CLEANUP_DAYS", None)
    if suggestion_cleanup_days and suggestion_cleanup_days > 0:
        migrate_cleanup_setting(
            apps,
            "weblate.removal.suggestions",
            {"age": suggestion_cleanup_days, "votes": None},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0017_add_manual_event_to_extract_pot_addons"),
    ]

    operations = [
        migrations.RunPython(migrate_cleanup_settings, migrations.RunPython.noop),
    ]
