# Generated by Django 2.2.5 on 2019-09-27 15:00

from django.db import migrations


def update_resx_addon(apps, schema_editor):
    Addon = apps.get_model("addons", "Addon")
    db_alias = schema_editor.connection.alias
    Addon.objects.using(db_alias).filter(
        component__file_format="resx", name="weblate.cleanup.generic"
    ).update(name="weblate.resx.update")


class Migration(migrations.Migration):

    dependencies = [("addons", "0017_auto_format_fixup")]

    operations = [
        migrations.RunPython(
            update_resx_addon, migrations.RunPython.noop, elidable=True
        )
    ]
