# Generated by Django 2.2.9 on 2020-02-10 10:05

from django.db import migrations

from weblate.addons.events import EVENT_COMPONENT_UPDATE, EVENT_POST_UPDATE


def update_addon(apps, schema_editor):
    """Update the repo_scope flag."""
    Addon = apps.get_model("addons", "Addon")
    Event = apps.get_model("addons", "Event")
    db_alias = schema_editor.connection.alias
    for addon in Addon.objects.using(db_alias).filter(
        name__in=("weblate.autotranslate.autotranslate", "weblate.flags.bulk")
    ):
        Event.objects.using(db_alias).get_or_create(
            addon=addon, event=EVENT_COMPONENT_UPDATE
        )
        addon.event_set.filter(event=EVENT_POST_UPDATE).delete()


class Migration(migrations.Migration):

    dependencies = [("addons", "0019_auto_20200210_0957")]

    operations = [
        migrations.RunPython(update_addon, migrations.RunPython.noop, elidable=True)
    ]
