# Generated by Django 2.2.9 on 2020-02-14 11:40

from django.db import migrations

from weblate.addons.events import EVENT_DAILY
from weblate.addons.utils import adjust_addon_events


def update_addon(apps, schema_editor):
    """Update the repo_scope flag."""
    adjust_addon_events(
        apps,
        schema_editor,
        ("weblate.gettext.linguas", "weblate.gettext.configure"),
        [EVENT_DAILY],
        [],
    )


class Migration(migrations.Migration):

    dependencies = [("addons", "0020_component_update")]

    operations = [
        migrations.RunPython(update_addon, migrations.RunPython.noop, elidable=True)
    ]
