# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 07:49
from __future__ import unicode_literals
from __future__ import print_function

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
    ]
