# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:33
from __future__ import unicode_literals

from django.db import migrations
import weblate.screenshots.fields


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0002_auto_20170215_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=weblate.screenshots.fields.ScreenshotField(help_text='Upload JPEG or PNG images up to 2000x2000 pixels.', upload_to='screenshots/', verbose_name='Image'),
        ),
    ]
