# Generated by Django 2.2 on 2019-05-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("screenshots", "0002_auto_20180826_0839")]

    operations = [migrations.AlterModelOptions(name="screenshot", options={})]
