# Generated by Django 2.2.5 on 2019-11-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0046_source_strings"),
        ("screenshots", "0003_auto_20190516_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="units",
            field=models.ManyToManyField(
                blank=True, related_name="screenshots", to="trans.Unit"
            ),
        )
    ]
