# Generated by Django 2.2.5 on 2019-11-03 13:37

from django.db import migrations


def migrate_source_strings(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Unit = apps.get_model("trans", "Unit")
    Screenshot = apps.get_model("screenshots", "Screenshot")
    for screenshot in Screenshot.objects.using(db_alias).iterator():
        for source in screenshot.sources.iterator():
            try:
                unit = Unit.objects.using(db_alias).filter(
                    id_hash=source.id_hash, component=source.component
                )[0]
            except IndexError:
                continue
            screenshot.units.add(unit)


class Migration(migrations.Migration):

    dependencies = [
        ("screenshots", "0004_screenshot_units"),
        ("trans", "0045_auto_20191103_1029"),
    ]

    operations = [
        migrations.RunPython(
            migrate_source_strings, migrations.RunPython.noop, elidable=True
        )
    ]
