# Generated by Django 4.0.5 on 2022-10-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screenshots", "0005_alter_screenshot_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="repository_filename",
            field=models.CharField(
                blank=True,
                help_text="Scan for screenshot file change on repository update.",
                max_length=200,
                verbose_name="Repository path to screenshot",
            ),
        ),
    ]
