# Generated by Django 2.2.5 on 2019-11-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("screenshots", "0005_source_strings")]

    operations = [migrations.RemoveField(model_name="screenshot", name="sources")]
