# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.3 on 2023-07-17 08:01

from django.db import migrations

import weblate.screenshots.fields


class Migration(migrations.Migration):
    dependencies = [
        ("screenshots", "0006_screenshot_repository_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screenshot",
            name="image",
            field=weblate.screenshots.fields.ScreenshotField(
                help_text="Upload image up to 2000x2000 pixels.",
                upload_to="screenshots/",
                verbose_name="Image",
            ),
        ),
    ]
