# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.5 on 2026-05-27 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import weblate.trans.validators
import weblate.utils.render
from weblate.utils.licenses import get_license_choices


class Migration(migrations.Migration):
    dependencies = [
        ("lang", "0007_alter_language_code"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="add_message",
            field=models.TextField(
                default=settings.DEFAULT_ADD_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_commit],
                verbose_name="Commit message when adding translation",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="addon_message",
            field=models.TextField(
                default=settings.DEFAULT_ADDON_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_addon],
                verbose_name="Commit message when add-on makes a change",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="agreement",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contributor license agreement which needs to be approved before a user can translate components in this workspace.",
                verbose_name="Contributor license agreement",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="check_flags",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional comma-separated flags to influence Weblate behavior.",
                validators=[weblate.trans.validators.validate_check_flags],
                verbose_name="Translation flags",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="commit_message",
            field=models.TextField(
                default=settings.DEFAULT_COMMIT_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_commit],
                verbose_name="Commit message when translating",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="delete_message",
            field=models.TextField(
                default=settings.DEFAULT_DELETE_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_commit],
                verbose_name="Commit message when removing translation",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="language_code_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Default based on the file format"),
                    ("posix", "POSIX style using underscore as a separator"),
                    (
                        "posix_lowercase",
                        "POSIX style using underscore as a separator, lower cased",
                    ),
                    ("bcp", "BCP style using hyphen as a separator"),
                    (
                        "posix_long",
                        "POSIX style using underscore as a separator, including country code",
                    ),
                    (
                        "posix_long_lowercase",
                        "POSIX style using underscore as a separator, including country code, lower cased",
                    ),
                    (
                        "bcp_long",
                        "BCP style using hyphen as a separator, including country code",
                    ),
                    (
                        "bcp_legacy",
                        "BCP style using hyphen as a separator, legacy language codes",
                    ),
                    ("bcp_lower", "BCP style using hyphen as a separator, lower cased"),
                    ("android", "Android style"),
                    ("appstore", "Apple App Store metadata style"),
                    ("googleplay", "Google Play metadata style"),
                    ("linux", "Linux style"),
                    ("linux_lowercase", "Linux style, lower cased"),
                ],
                default="",
                help_text="Customize language code used to generate the filename for translations created by Weblate.",
                max_length=20,
                verbose_name="Language code style",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="license",
            field=models.CharField(
                blank=not settings.LICENSE_REQUIRED,
                choices=get_license_choices(),
                default="",
                max_length=150,
                verbose_name="Translation license",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="merge_message",
            field=models.TextField(
                default=settings.DEFAULT_MERGE_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_component],
                verbose_name="Commit message when merging translation",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="new_lang",
            field=models.CharField(
                choices=[
                    ("contact", "Contact maintainers"),
                    ("url", "Point to translation instructions URL"),
                    ("add", "Create new language file"),
                    ("none", "Disable adding new translations"),
                ],
                default="add",
                help_text="How to handle requests for creating new translations.",
                max_length=10,
                verbose_name="Adding new translation",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="pull_message",
            field=models.TextField(
                default=settings.DEFAULT_PULL_MESSAGE,
                help_text="You can use template language for various info, please consult the documentation for more details.",
                validators=[weblate.utils.render.validate_render_addon],
                verbose_name="Merge request message",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="secondary_language",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Additional language to show together with the source language while translating.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_secondary_languages",
                to="lang.language",
                verbose_name="Secondary language",
            ),
        ),
    ]
