# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 4.2.8 on 2023-12-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lang", "0001_squashed_weblate_5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plural",
            name="source",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Default plural"),
                    (1, "gettext plural formula"),
                    (3, "CLDR plural with zero"),
                    (4, "CLDR v38+ plural"),
                    (5, "Android plural"),
                    (6, "Qt Linguist plural"),
                    (2, "Manually entered formula"),
                ],
                default=0,
                verbose_name="Plural definition source",
            ),
        ),
    ]
