# Generated by Django 2.2 on 2019-05-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("lang", "0001_squashed_0011_auto_20180215_1158")]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name": "Language", "verbose_name_plural": "Languages"},
        ),
        migrations.AlterModelOptions(
            name="plural",
            options={
                "verbose_name": "Plural form",
                "verbose_name_plural": "Plural forms",
            },
        ),
    ]
