# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_auto_20150630_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
