# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_auto_20150630_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='nplurals',
            field=models.SmallIntegerField(default=2),
        ),
    ]
