# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0003_auto_20160721_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.SlugField(unique=True, verbose_name='Language code'),
        ),
        migrations.AlterField(
            model_name='language',
            name='direction',
            field=models.CharField(choices=[('ltr', 'Left to right'), ('rtl', 'Right to left')], default='ltr', max_length=3, verbose_name='Text direction'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Language name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='nplurals',
            field=models.SmallIntegerField(default=2, verbose_name='Number of plurals'),
        ),
        migrations.AlterField(
            model_name='language',
            name='plural_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'One/other (classic plural)'), (2, 'One/few/other (Slavic languages)'), (3, 'Arabic languages'), (11, 'Zero/one/other'), (4, 'One/two/other'), (6, 'One/two/few/other'), (5, 'One/two/three/other'), (7, 'One/other/zero'), (8, 'One/few/many/other'), (9, 'Two/other'), (10, 'One/two/few/many/other'), (666, 'Unknown')], default=1, verbose_name='Plural type'),
        ),
        migrations.AlterField(
            model_name='language',
            name='pluralequation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Plural equation'),
        ),
    ]
