# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.1.1 on 2024-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lang", "0003_alter_plural_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="direction",
            field=models.CharField(
                choices=[
                    ("", "Automatically detect text direction"),
                    ("ltr", "Left to right"),
                    ("rtl", "Right to left"),
                ],
                default="",
                max_length=3,
                verbose_name="Text direction",
            ),
        ),
    ]
