# Generated by Django 2.2.4 on 2019-08-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lang", "0003_auto_20190721_1810")]

    operations = [
        migrations.AlterField(
            model_name="plural",
            name="source",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Default plural"),
                    (1, "Plural gettext formula"),
                    (2, "Manually entered formula"),
                ],
                default=0,
                verbose_name="Plural definition source",
            ),
        )
    ]
