# Generated by Django 2.2.9 on 2020-02-12 12:39

from django.db import migrations, models

import weblate.utils.validators


class Migration(migrations.Migration):

    dependencies = [("lang", "0004_auto_20190809_0930")]

    operations = [
        migrations.AlterField(
            model_name="plural",
            name="equation",
            field=models.CharField(
                default="n != 1",
                max_length=600,
                validators=[weblate.utils.validators.validate_plural_formula],
                verbose_name="Plural equation",
            ),
        )
    ]
