# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.10 on 2026-01-14 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lang", "0004_alter_language_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plural",
            name="number",
            field=models.SmallIntegerField(
                default=2,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Number of plurals",
            ),
        ),
    ]
