# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lang", "0005_alter_plural_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plural",
            name="number",
            field=models.SmallIntegerField(
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Number of plurals",
            ),
        ),
    ]
