# Generated by Django 3.0.4 on 2020-03-09 13:36

from django.db import migrations

import weblate.lang.models


class Migration(migrations.Migration):

    dependencies = [("lang", "0005_auto_20200212_1239")]

    operations = [
        migrations.AlterModelManagers(
            name="language",
            managers=[("objects", weblate.lang.models.LanguageManager())],
        )
    ]
