# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.5 on 2026-05-19 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lang", "0006_alter_plural_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid language code.",
                        regex="^[A-Za-z0-9]+(?:[-_@][A-Za-z0-9]+)*\\Z",
                    )
                ],
                verbose_name="Language code",
            ),
        ),
    ]
