# Generated by Django 3.0.5 on 2020-04-04 11:11

from django.db import migrations, models

import weblate.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("lang", "0006_auto_20200309_1436"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plural", old_name="equation", new_name="formula",
        ),
        migrations.AlterField(
            model_name="plural",
            name="formula",
            field=models.CharField(
                default="n != 1",
                max_length=600,
                validators=[weblate.utils.validators.validate_plural_formula],
                verbose_name="Plural formula",
            ),
        ),
    ]
