# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0006_plural'),
    ]

    operations = [
    ]
