# Generated by Django 3.0.5 on 2020-04-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lang", "0007_auto_20200404_1111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="direction",
            field=models.CharField(
                choices=[("", ""), ("ltr", "Left to right"), ("rtl", "Right to left")],
                default="",
                max_length=3,
                verbose_name="Text direction",
            ),
        ),
    ]
