# Generated by Django 4.1a1 on 2022-07-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lang", "0015_population"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plural",
            name="source",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Default plural"),
                    (1, "gettext plural formula"),
                    (3, "stringsdict plural"),
                    (4, "CLDR v38+ plural"),
                    (5, "Android plural"),
                    (2, "Manually entered formula"),
                ],
                default=0,
                verbose_name="Plural definition source",
            ),
        ),
    ]
