# Generated by Django 2.2.5 on 2019-12-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0052_auto_20191212_1403"),
        ("checks", "0001_squashed_0002_auto_20180416_1509"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trans.Unit",
            ),
        ),
        migrations.AlterUniqueTogether(name="check", unique_together=set()),
    ]
