# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.2.3 on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0001_squashed_weblate_5"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="check",
            index=models.Index(
                condition=models.Q(("dismissed", False)),
                fields=["unit"],
                name="checks_active_unit_idx",
            ),
        ),
    ]
