# Generated by Django 2.2.5 on 2019-12-12 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("trans", "0054_auto_20191212_1441"), ("checks", "0002_check_unit")]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trans.Unit"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="check", unique_together={("unit", "check")}
        ),
        migrations.AlterIndexTogether(name="check", index_together=set()),
        migrations.RemoveField(model_name="check", name="content_hash"),
        migrations.RemoveField(model_name="check", name="language"),
        migrations.RemoveField(model_name="check", name="project"),
    ]
