# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: API

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
    - dependabot/**
    - copilot/**
    - codex/**
  pull_request:

permissions:
  contents: read

jobs:
  api-lint:
    runs-on: ubuntu-24.04
    name: API Lint
    env:
      CI_REDIS_HOST: 127.0.0.1
      CI_REDIS_PORT: '6379'
      CI_DB_PASSWORD: weblate
      CI_DB_HOST: 127.0.0.1
      CI_DB_PORT: '5432'
      CI_SELENIUM: '1'
      DJANGO_SETTINGS_MODULE: weblate.settings_test
      PYTHONWARNINGS: default,ignore:unclosed:ResourceWarning
      PYTHONUNBUFFERED: 1
    services:
      database:
        image: postgres:18.4-alpine@sha256:1b1689b20d16a014a3d195653381cf2caa75a41a92d93b255a9d6ea29fd353aa
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: weblate
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      cache:
        image: valkey/valkey:9.1.0-alpine@sha256:a35428eba9043cc0b79dbe54100f0c92784f2de00ad09b01182bfb1c5c83d1bd
        ports:
        - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Set up Python
      id: setup_python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'
    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        save-cache: ${{ github.ref == 'refs/heads/main' }}
        cache-suffix: ${{ steps.setup_python.outputs.python-version }}
        version: 0.11.21
    - name: Install apt dependencies
      run: sudo ./ci/apt-install
    - name: Used versions
      run: ./ci/print-versions
    - name: Install Python dependencies
      run: ./ci/pip-install latest
    - name: Prepare database
      run: ./ci/prepare-database
    - name: Migrate database
      run: uv run --frozen ./manage.py migrate --noinput --traceback
    - name: Generate OpenAPI
      run: |
        echo "::add-matcher::.github/matchers/spectacular.json"
        make -C docs update-openapi
        echo "::remove-matcher owner=spectacular::"
    - name: openapi-lint
      run: npx @redocly/cli lint --format github-actions docs/specs/openapi.yaml
    - name: Verify OpenAPI spec is up to date
      run: git diff --exit-code
    - uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
      if: always()
      with:
        msg: 'chore(docs): update OpenAPI schema'
