# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: API

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
    - dependabot/**
  pull_request:

permissions:
  contents: read

jobs:
  api-lint:
    runs-on: ubuntu-24.04
    name: API Lint
    env:
      CI_REDIS_HOST: 127.0.0.1
      CI_REDIS_PORT: '6379'
      CI_DB_PASSWORD: weblate
      CI_DB_HOST: 127.0.0.1
      CI_DB_PORT: '5432'
      CI_SELENIUM: '1'
      DJANGO_SETTINGS_MODULE: weblate.settings_test
      PYTHONWARNINGS: default,ignore:unclosed:ResourceWarning
      PYTHONUNBUFFERED: 1
    services:
      database:
        image: postgres:18.3-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: weblate
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      cache:
        image: valkey/valkey:9.0.3-alpine@sha256:e1095c6c76ee982cb2d1e07edbb7fb2a53606630a1d810d5a47c9f646b708bf5
        ports:
        - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Set up Python
      id: setup_python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'
    - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
      with:
        save-cache: ${{ github.ref == 'refs/heads/main' }}
        cache-suffix: ${{ steps.setup_python.outputs.python-version }}
        version: 0.11.6
    - name: Install apt dependencies
      run: sudo ./ci/apt-install
    - name: Used versions
      run: ./ci/print-versions
    - name: Install Python dependencies
      run: ./ci/pip-install latest
    - name: Prepare database
      run: ./ci/prepare-database
    - name: Migrate database
      run: uv run --frozen ./manage.py migrate --noinput --traceback
    - name: Generate OpenAPI
      run: |
        echo "::add-matcher::.github/matchers/spectacular.json"
        make -C docs update-openapi
        echo "::remove-matcher owner=spectacular::"
    - name: openapi-lint
      run: npx @redocly/cli lint --format github-actions docs/specs/openapi.yaml
    - name: Verify OpenAPI spec is up to date
      run: git diff --exit-code
    - uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
      if: always()
      with:
        msg: 'chore(docs): update OpenAPI schema'
