# Copyright © Weblate contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: ClusterFuzzLite Builds

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  build-fuzzers:
    runs-on: ubuntu-24.04
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
        - address
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Build Fuzzers (${{ matrix.sanitizer }})
      uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
      with:
        language: python
        github-token: ${{ secrets.GITHUB_TOKEN }}
        sanitizer: ${{ matrix.sanitizer }}
        upload-build: true
