# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: FOSSA

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  fossa-scan:
    runs-on: ubuntu-slim
    if: ${{ github.repository == 'WeblateOrg/weblate' }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      with:
        persist-credentials: false
    - name: Run FOSSA Scan
      uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # v1.9.0
      with:
        api-key: ${{secrets.fossaApiKey}} # zizmor: ignore[secrets-outside-env]

    - name: Run FOSSA Test
      uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # v1.9.0
      with:
        api-key: ${{secrets.fossaApiKey}} # zizmor: ignore[secrets-outside-env]
        run-tests: true
