# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/WeblateOrg/meta/
name: Issue labeled

on:
  issues:
    types: [labeled]

permissions: {}

jobs:
  issue-labeled:
    if: ${{ ! github.event.issue.pull_request && github.event.label.name == 'good first issue' }}
    permissions:
      contents: read  # for actions/checkout
      issues: write  # for gh issue comment
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Add good first issue comment
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: gh issue comment "$ISSUE_NUMBER" --body-file .github/comments/issue-newbie.md
