# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: licenses update

on:
  push:
    branches:
    - renovate/**
    - dependabot/**
    - main
    paths:
    - .github/workflows/licenses-update.yml
    - scripts/generate-license-data.py
    - scripts/spdx-license-list

permissions:
  contents: read

jobs:
  licenses-update:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      with:
        persist-credentials: false
        submodules: true
    - uses: ./.github/actions/pre-commit-setup
    - run: ./scripts/generate-license-data.py

    - name: Prepare maintenance patch (pre-commit-ci-lite)
      uses: ./.github/actions/auto-commit
      with:
        message: 'utils: Update SPDX license data'
