# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/WeblateOrg/meta/
name: Pull request automation

on: # zizmor: ignore[dangerous-triggers]
  pull_request_target:
    types: opened

permissions: {}

jobs:
  weblate-automerge:
    runs-on: ubuntu-slim
    name: Weblate automerge
    if: github.actor == 'weblate'
    steps:
    - name: Enable Pull Request Automerge
      run: gh pr merge --repo "$GITHUB_REPOSITORY" --rebase --auto "$PR_NUMBER"
      env:
        GH_TOKEN: ${{ secrets.WEBLATE_CI_TOKEN }} # zizmor: ignore[secrets-outside-env]
        PR_NUMBER: ${{ github.event.pull_request.number }}
