# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

name: pylint check

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
    - dependabot/**
    - copilot/**
    - codex/**
  pull_request:

permissions:
  contents: read

jobs:
  pylint:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - name: Install apt dependencies
      run: sudo ./ci/apt-install
    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      id: setup_python
      with:
        python-version: '3.14'
    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        save-cache: ${{ github.ref == 'refs/heads/main' }}
        cache-suffix: ${{ steps.setup_python.outputs.python-version }}
        version: 0.11.19
    - name: Install deps
      run: uv sync --no-binary-package lxml --no-binary-package xmlsec --all-extras --group pylint
    - name: Run pylint
      run: uv run --no-sync pylint --output-format=github weblate/ scripts/
