# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

name: pylint check

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
    - dependabot/**
    - copilot/**
    - codex/**
  pull_request:

permissions:
  contents: read

jobs:
  pylint:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Install apt dependencies
      run: sudo ./ci/apt-install
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      id: setup_python
      with:
        python-version: '3.14'
    - uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
      with:
        save-cache: ${{ github.ref == 'refs/heads/main' }}
        cache-suffix: ${{ steps.setup_python.outputs.python-version }}
        version: 0.11.26
    - name: Install deps
      run: uv sync --no-binary-package lxml --no-binary-package xmlsec --all-extras --group pylint
    - name: Run pylint
      run: uv run --no-sync pylint --output-format=github weblate/ scripts/
