# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: jsonschema update

on:
  push:
    branches:
    - renovate/**
    - dependabot/**
    - main
    paths:
    - .github/workflows/schema-update.yml
    - pyproject.toml
    - docs/Makefile
    - scripts/get-schemas-dir.py
  workflow_dispatch:

permissions:
  contents: read

jobs:
  jsonschema-update:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0   # v7.0.0
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        enable-cache: false
        version: 0.11.23
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'
    - name: Install Python dependencies
      run: |
        uv sync --only-group schemas --only-group pre-commit
    - run: make -C docs update-schemas

    - name: Prepare maintenance patch
      uses: ./.github/actions/auto-commit
