name: jsonschema update

on:
  push:
    branches:
    - dependabot/**
    - deepsource-fix-**
    - renovate/**
    - main
    paths:
    - .github/workflows/schema-update.yml
    - requirements.txt
    - docs/Makefile

jobs:
  jsonschema-update:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3.3.0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install $(grep -E '^(weblate-schemas)==' requirements.txt) -r requirements-lint.txt
    - run: make -C docs update-schemas
    - run: pre-commit run --files $(git diff --name-only)
      continue-on-error: true
    - name: Update dependabot branch
      if: github.ref != 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'docs: Update JSON schemas'
    - name: Create Pull Request
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@v4
      with:
        branch: create-pull-request/jsonschema-update
        title: 'docs: Update JSON schemas'
        commit-message: 'docs: Update JSON schemas'
        labels: |
          dependencies
          automerge
